/**
 * Las etiquetas del editor, indexadas **por el propio espanol**.
 *
 * Es el segundo mecanismo de traduccion de la aplicacion: la funcion `tf`
 * busca aqui, pasandole el espanol, en vez de usar una clave. Se quedo asi porque el editor tiene cientos
 * de etiquetas cortas y ponerle clave a cada una no aportaba nada.
 */
export const FIELDS_EN: Record<string, string> = {
  // Labels de config por acción
  'RUTA DE LA APLICACIÓN': 'APPLICATION PATH',
  'ARGUMENTOS (OPCIONAL)': 'ARGUMENTS (OPTIONAL)',
  'URL': 'URL',
  'RUTA DEL ARCHIVO O CARPETA': 'FILE OR FOLDER PATH',
  'INTÉRPRETE': 'INTERPRETER',
  'SCRIPT': 'SCRIPT',
  'GUARDAR SALIDA EN VARIABLE (opcional)': 'SAVE OUTPUT TO VARIABLE (optional)',
  'DISPOSITIVO DE AUDIO': 'AUDIO DEVICE',
  'COMBINACIÓN DE TECLAS': 'KEY COMBINATION',
  'TEXTO A COPIAR AL PORTAPAPELES': 'TEXT TO COPY TO CLIPBOARD',
  'TEXTO A ESCRIBIR AUTOMÁTICAMENTE': 'TEXT TO TYPE AUTOMATICALLY',
  'NOMBRE DEL PROCESO': 'PROCESS NAME',
  'NIVEL DE VOLUMEN': 'VOLUME LEVEL',
  'NIVEL DE BRILLO': 'BRIGHTNESS LEVEL',
  'TÍTULO': 'TITLE',
  'MENSAJE': 'MESSAGE',
  'NOMBRE DE VARIABLE': 'VARIABLE NAME',
  'VALOR (acepta {otraVariable})': 'VALUE (accepts {otherVariable})',
  'DELTA (entero — usa negativo para restar)': 'DELTA (integer — use negative to subtract)',
  'MÉTODO': 'METHOD',
  'HEADERS (JSON, opcional)': 'HEADERS (JSON, optional)',
  'BODY (acepta {variables})': 'BODY (accepts {variables})',
  'TEXTO A LEER (acepta {variables})': 'TEXT TO READ (accepts {variables})',
  'DISPOSITIVO RGB': 'RGB DEVICE',
  'COLOR (HEX)': 'COLOR (HEX)',
  'MODO / EFECTO': 'MODE / EFFECT',
  'COLOR (OPCIONAL — SOLO PARA MODOS QUE LO USAN)': 'COLOR (OPTIONAL — ONLY FOR MODES THAT USE IT)',
  'BRILLO 0-100 (OPCIONAL)': 'BRIGHTNESS 0-100 (OPTIONAL)',
  'PERFIL RGB': 'RGB PROFILE',
  'POSICIÓN / TAMAÑO': 'POSITION / SIZE',
  'PROCESO A SNAPEAR (opcional — vacío = ventana activa)': 'PROCESS TO SNAP (optional — empty = active window)',
  'CONDICIÓN: SI {variable}': 'CONDITION: IF {variable}',
  'ENTONCES (acción si VERDADERO)': 'THEN (action if TRUE)',
  'SI NO (acción si FALSO — opcional)': 'ELSE (action if FALSE — optional)',
  'TIEMPO DE ESPERA (milisegundos)': 'WAIT TIME (milliseconds)',
  'PASOS DE LA MACRO': 'MACRO STEPS',
  // Labels de estilo / widget / disparadores
  'ETIQUETA DEL BOTÓN': 'BUTTON LABEL',
  'SUB-ETIQUETA (OPCIONAL)': 'SUB-LABEL (OPTIONAL)',
  'ICONO (EMOJI O SÍMBOLO — VACÍO = ÍCONO DEL TIPO)': 'ICON (EMOJI OR SYMBOL — EMPTY = TYPE ICON)',
  'ICONO DE MARCA ANIMADO (DOT-MATRIX)': 'ANIMATED BRAND ICON (DOT-MATRIX)',
  'GLIFO PERSONAL 5×7 (DOT-MATRIX)': 'CUSTOM 5×7 GLYPH (DOT-MATRIX)',
  'IMAGEN PERSONALIZADA (PNG / JPG / GIF)': 'CUSTOM IMAGE (PNG / JPG / GIF)',
  'COLOR DE FONDO': 'BACKGROUND COLOR',
  'COLOR DE TEXTO / ÍCONO': 'TEXT / ICON COLOR',
  'GRUPO RADIO (toggles mutuamente exclusivos)': 'RADIO GROUP (mutually exclusive toggles)',
  'WIDGET (MUESTRA DATOS EN EL BOTÓN)': 'WIDGET (SHOWS LIVE DATA ON THE BUTTON)',
  'VISIBLE SOLO SI ESTA APP ESTÁ ACTIVA (opcional)': 'VISIBLE ONLY IF THIS APP IS ACTIVE (optional)',
  'VISIBLE SOLO SI SENSOR (opcional)': 'VISIBLE ONLY IF SENSOR (optional)',
  'DISPARAR AUTOMÁTICAMENTE A LA HORA (HH:MM)': 'TRIGGER AUTOMATICALLY AT TIME (HH:MM)',
  'DISPARAR CUANDO SENSOR (opcional)': 'TRIGGER WHEN SENSOR (optional)',
  // Placeholders
  'Buscar preset...': 'Search preset...',
  'ruta o comando': 'path or command',
  'ruta': 'path',
  'Script...': 'Script...',
  'Script de desactivación...': 'Deactivation script...',
  'Ej: Auriculares (Realtek HD Audio)': 'E.g. Headphones (Realtek HD Audio)',
  'Texto a escribir': 'Text to type',
  'texto al portapapeles': 'text to clipboard',
  'Texto de la notificación...': 'Notification text...',
  'Texto que se escribirá con SendKeys...': 'Text that will be typed with SendKeys...',
  'Texto, URL, código, etc.': 'Text, URL, code, etc.',
  'Título': 'Title',
  'Mensaje': 'Message',
  'Nombre': 'Name',
  'Nombre de variable (ej. tomas)': 'Variable name (e.g. takes)',
  'nombre_variable': 'variable_name',
  'contador': 'counter',
  'contador, lastApp, etc.': 'counter, lastApp, etc.',
  'valor': 'value',
  'valor o {variable}': 'value or {variable}',
  'Valor (ej. 80)': 'Value (e.g. 80)',
  'Valor (ej. 85)': 'Value (e.g. 85)',
  'variable': 'variable',
  'Descripción corta': 'Short description',
  'Mi Botón': 'My Button',
  'Prefijo (ej. 🎬 )': 'Prefix (e.g. 🎬 )',
  'Etiqueta debajo': 'Label below',
  'Etiqueta (ej. CPU)': 'Label (e.g. CPU)',
  'vacío = sin atajo global': 'empty = no global hotkey',
  'ej: modo_audio, perfil_rgb...': 'e.g. audio_mode, rgb_profile...',
  'ej: resultado_cpu': 'e.g. cpu_result',
  '--flag valor': '--flag value',
  'https://ejemplo.com': 'https://example.com',
  'proceso.exe': 'process.exe',
  // ── Editor de botones: textos sueltos ──
  'PRESETS RÁPIDOS': 'QUICK PRESETS',
  'Sin resultados': 'No results',
  'TIPO DE ACCIÓN': 'ACTION TYPE',
  '+ AÑADIR ACCIÓN ADICIONAL': '+ ADD EXTRA ACTION',
  'Sin acción configurada.': 'No action configured.',
  'Buscar': 'Browse',
  'CMD (Símbolo del sistema)': 'CMD (Command Prompt)',
  'MOSTRAR SALIDA DEL SCRIPT EN PANTALLA': 'SHOW SCRIPT OUTPUT ON SCREEN',
  '⟳ RECARGAR': '⟳ RELOAD',
  'Cargando dispositivos...': 'Loading devices...',
  '⟳ REINTENTAR': '⟳ RETRY',
  'O ingresa el nombre exacto del dispositivo (como aparece en Configuración → Sonido):': 'Or type the exact device name (as it appears in Settings → Sound):',
  'No se detectaron dispositivos automáticamente.': 'No devices were detected automatically.',
  'Ingresa el nombre exacto del dispositivo (como aparece en Configuración → Sonido):': 'Type the exact device name (as it appears in Settings → Sound):',
  'PREDETERMINADO': 'DEFAULT',
  '✓ SELECCIONADO': '✓ SELECTED',
  'Presiona la combinación deseada...': 'Press the combination you want...',
  'Ej: Ctrl+Alt+T · Ctrl+Shift+F9 · Ctrl+Z · V · Space': 'E.g. Ctrl+Alt+T · Ctrl+Shift+F9 · Ctrl+Z · V · Space',
  'El texto se escribe en la ventana activa. Caracteres especiales (+, ^, %, %, (, )) se escapan automáticamente.': 'The text is typed into the active window. Special characters (+, ^, %, %, (, )) are escaped automatically.',
  'Controla el brillo del monitor principal via WMI.': 'Controls the main monitor brightness via WMI.',
  'Abre la herramienta nativa de captura de región de Windows (Win+Shift+S). El recorte queda en el portapapeles.': 'Opens the native Windows region-capture tool (Win+Shift+S). The clip goes to the clipboard.',
  'OpenRGB no conectado. Conecta desde la pantalla RGB para listar dispositivos. La acción seguirá funcionando si OpenRGB está activo cuando se ejecute el botón.': 'OpenRGB is not connected. Connect from the RGB screen to list devices. The action still works if OpenRGB is running when the button is pressed.',
  'Todos los dispositivos': 'All devices',
  'CARGAR PRESET ADOBE': 'LOAD ADOBE PRESET',
  'Esta acción no necesita configuración adicional.': 'This action needs no further configuration.',
  'contiene': 'contains',
  'está vacío': 'is empty',
  'no está vacío': 'is not empty',
  'Pausa la secuencia este tiempo antes de continuar con la siguiente acción.': 'Pauses the sequence for this long before continuing to the next action.',
  'MODO TOGGLE — el botón alterna entre activado / desactivado': 'TOGGLE MODE — the button switches between on and off',
  'ACCIÓN AL DESACTIVAR (opcional — si vacío, repite la misma acción)': 'ACTION WHEN TURNING OFF (optional — if empty, repeats the same action)',
  'ACCIÓN AL MANTENER PRESIONADO (~500 MS)': 'ACTION ON PRESS AND HOLD (~500 MS)',
  'MOSTRAR EN MENÚ DEL TRAY (acción rápida)': 'SHOW IN TRAY MENU (quick action)',
  'Elegir imagen': 'Choose image',
  'Quitar': 'Remove',
  'Cambiar': 'Change',
  'Editar puntos': 'Edit dots',
  'Restaurar': 'Reset',
  'Elegir icono de marca': 'Choose brand icon',
  'Editar': 'Edit',
  'Dibujar glifo': 'Draw glyph',
  'ANIMACIÓN SIEMPRE ACTIVA — si está desactivado, anima solo cuando el botón está encendido (toggle ON)': 'ANIMATION ALWAYS ON — when off, it only animates while the button is on (toggle ON)',
  '68 iconos · Fondo transparente · Superpone al color de fondo del botón': '68 icons · Transparent background · Drawn over the button background colour',
  '5×7 puntos hechos a mano. Coherente con la firma del producto.': 'Hand-drawn 5×7 dots. Consistent with the product signature.',
  'Incompatible con acción de Audio: el widget oculta el nombre del dispositivo.': 'Incompatible with an Audio action: the widget hides the device name.',
  'NINGUNO': 'NONE',
  'RELOJ': 'CLOCK',
  'CLIMA': 'WEATHER',
  'MÚSICA': 'MUSIC',
  'Sustituye el ícono/etiqueta con datos en vivo. El botón sigue siendo ejecutable.': 'Replaces the icon/label with live data. The button still runs its action.',
  'Muestra el valor en vivo de una variable. Combínalo con acciones "Incrementar variable" / "Asignar variable" para hacer contadores. Las variables sin valor se muestran como 0.': 'Shows the live value of a variable. Combine it with the "Increment variable" / "Set variable" actions to build counters. Variables with no value show as 0.',
  'Nombre del proceso sin .exe. Vacío = siempre visible.': 'Process name without .exe. Empty = always visible.',
  'Formato 24h. Solo se dispara cuando la página del botón está activa.': '24h format. Only fires while the button page is active.',
  'Aparece cuando el sensor cumple la condición. Combinable con app de arriba.': 'Appears when the sensor meets the condition. Can be combined with the app above.',
  'Ejecuta la acción cuando se cumple la condición. Cooldown evita que se redispare cada poll (default 60s).': 'Runs the action when the condition is met. The cooldown stops it re-firing on every poll (default 60s).',
  'No se pudo obtener la lista. Verifica que el audio esté activo o reinicia la aplicación.': 'The list could not be read. Check that audio is active, or restart the app.',
  'mayor o igual': 'greater or equal',
  'menor o igual': 'less or equal',
  'acción adicional': 'extra action',
  'acciones adicionales': 'extra actions',
  'Cuad. sup-izq': 'Top-left qdr.',
  'Mitad superior': 'Top half',
  'Cuad. sup-der': 'Top-right qdr.',
  'Mitad izq': 'Left half',
  'Centro 50%': 'Center 50%',
  'Mitad der': 'Right half',
  'Cuad. inf-izq': 'Bottom-left qdr.',
  'Mitad inferior': 'Bottom half',
  'Cuad. inf-der': 'Bottom-right qdr.',
  'Maximizar': 'Maximize',
  'C:\\Users\\...\\archivo.lnk': 'C:\\Users\\...\\file.lnk',
  'Hola, son las {hora}': 'Hello, it is {hora}',
  'HOTKEY GLOBAL DEL SO (ej. Ctrl+Alt+1)': 'GLOBAL OS HOTKEY (e.g. Ctrl+Alt+1)',
  'Texto al portapapeles': 'Text to clipboard',
  'texto a escribir': 'text to type',
};
