/**
 * Diccionario ingles.
 *
 * Vive fuera de `i18n.tsx` porque el archivo llegaba a 1135 lineas y crecia
 * con cada texto nuevo: los tres diccionarios son datos, y mezclados con el
 * proveedor hacian ilegible lo poco que ahi es logica.
 *
 * Las claves son estables (no el texto). El orden importa solo para leerlo.
 */
import type { Dict } from './tipos';

export const EN: Dict = {
  'settings.theme': 'THEME',
  'settings.theme.dark': 'DARK',
  'settings.theme.light': 'LIGHT',
  'settings.theme.system': 'SYSTEM',
  'settings.language': 'LANGUAGE',
  'settings.language.system': 'SYSTEM',
  'settings.autostart': 'START WITH WINDOWS',
  'settings.alwaysOnTop': 'ALWAYS ON TOP',
  'settings.uiscale': 'INTERFACE SCALE',
  'settings.tiles': 'BUTTON SHAPE',
  'settings.tiles.square': 'SQUARE',
  'settings.tiles.fill': 'FILL',
  'main.search.placeholder': 'Label, app, URL, shortcut...',
  'main.search.title': 'FIND BUTTON',
  'main.search.empty': 'No buttons configured',
  'main.search.nomatch': 'No matches',
  'main.search.nav': '↑↓ NAVIGATE',
  'main.search.edit': '↵ EDIT',
  'main.search.exit': 'ESC CLOSE',
  'update.ready': 'Update {version} ready.',
  'update.restart': 'RESTART',
  'update.later': 'LATER',
  'onb.step': 'STEP {n} / 0{total}',
  'onb.skip': 'Skip',
  'onb.back': 'Back',
  'onb.next': 'Next',
  'onb.start': 'Get started',
  'onb.1.title': 'VIRTUALDECK',
  'onb.1.body': 'Your software Stream Deck. A grid of buttons that fire actions: open apps, websites and folders, switch audio, control music, run shortcuts, macros and more.',
  'onb.1.hint': 'Everything saves itself. No cloud, no accounts: 100% local.',
  'onb.2.title': 'YOUR BUTTONS',
  'onb.2.body': 'Click any empty cell to set it up. Pick a label, an icon and the action it should run. A normal click fires it; the context menu (right-click) edits, duplicates or clears it.',
  'onb.2.hint': 'Ctrl+click selects multiple buttons for bulk operations.',
  'onb.3.title': 'PAGES & GRID',
  'onb.3.body': 'Organize your buttons across several pages (tabs at the top). Switch between them with keys 1-9 or by swiping. Each page can have its own grid size.',
  'onb.3.hint': 'Drag a button onto another page tab to move it there.',
  'onb.4.title': 'WIDGETS & FULLSCREEN',
  'onb.4.body': 'A button can show a clock, weather, PC sensors, a variable or the music playing right now. Go fullscreen to use VirtualDeck as a dedicated panel on a tablet or second monitor.',
  'onb.4.hint': 'The music widget detects Spotify, YouTube, browsers and more.',
  'onb.5.title': 'HELP ALWAYS AT HAND',
  'onb.5.body': 'Press Ctrl+K to find any button instantly. Under ⚙ → Help & About you will find the docs, bug reporting and this tutorial in case you want to replay it.',
  'onb.5.hint': 'Ready? Create your first button.',
  'hint.firstButton': 'Click an empty cell to create your first button.',
  'hint.settings': 'Theme, language, scale and more live here in Settings.',
  'hint.search': 'Tip: Ctrl+K finds any button instantly.',
  'hint.dismiss': 'Got it',
  'help.title': 'HELP & ABOUT',
  'help.docs': '📖 DOCUMENTATION',
  'help.report': '🐞 REPORT BUG',
  'help.check': '⟳ CHECK UPDATE',
  'help.checking': 'CHECKING…',
  'help.support': '♥ SUPPORT',
  'help.donateIntro': 'VirtualDeck is free. If it helps you, you can support its development:',
  'help.openLog': 'OPEN LOG',
  'help.exportLog': 'EXPORT LOG',
  'help.replay': '🎓 REPLAY TUTORIAL',
  'help.credits': 'CREDITS & LICENSES',
  'help.bundled': ' (bundled)',
  'help.upd.ready': 'Update {version} ready — restart to apply.',
  'help.upd.downloading': 'Downloading update {version}…',
  'help.upd.error': 'Could not check for updates.',
  'help.upd.disabled': 'Auto-update not available in this build (dev mode).',
  'help.upd.checkError': 'Error checking for updates.',
  'help.upd.checking': 'Checking for updates…',
  'tip.export': 'Export configuration',
  'tip.import': 'Import configuration',
  'tip.bar': 'Floating column of tiles over the desktop',
  'tip.rgb': 'RGB manager',
  'tip.settings': 'Settings',
  'tip.fullscreen': 'Fullscreen mode',
  'tip.minimize': 'Minimize',
  'tip.close': 'Close (minimizes to tray)',
  'wp.back': '← BACK',
  'wp.preview': 'PREVIEW',
  'wp.select': 'SELECT WALLPAPER',
  'wp.applied': '✓ APPLIED',
  'wp.apply': 'APPLY →',
  'wp.selected': '● SELECTED',
  'wp.autosave': 'Changes are saved automatically when you press Apply.',
  'wp.name.solid': 'Solid',
  'wp.name.gradient': 'Blue Gradient',
  'wp.name.dotgrid': 'Dot Grid',
  'wp.name.scanlines': 'Scanlines',
  'wp.name.crt': 'CRT',
  'wp.name.mesh': 'Tech Mesh',
  'wp.name.photo': 'Neon',
  'wp.name.grid-blue': 'Blue Grid',
  'ed.title': 'CONFIGURE BUTTON',
  'ed.preview': 'PREVIEW',
  'ed.step.action': 'ACTION',
  'ed.step.config': 'CONFIGURE',
  'ed.step.style': 'STYLE',
  'ed.back': '← BACK',
  'ed.cancel': 'CANCEL',
  'ed.next': 'NEXT →',
  'ed.save': 'SAVE ✓',
  'ed.stepN': 'STEP {n} / {total}',
  'ed.toggleMode': 'TOGGLE MODE',
  // — Action types (editor picker) —
  'act.none.label': 'None', 'act.none.desc': 'No action assigned',
  'act.app.label': 'Open App', 'act.app.desc': 'Launch an application',
  'act.web.label': 'Website', 'act.web.desc': 'Open a URL in the browser',
  'act.shortcut.label': 'Shortcut', 'act.shortcut.desc': 'Open a file or folder',
  'act.script.label': 'Script', 'act.script.desc': 'Run PowerShell or CMD',
  'act.audio-device.label': 'Audio', 'act.audio-device.desc': 'Switch output device',
  'act.hotkey.label': 'Hotkey', 'act.hotkey.desc': 'Send a key combination',
  'act.clipboard.label': 'Clipboard', 'act.clipboard.desc': 'Copy text to clipboard',
  'act.type-text.label': 'Type Text', 'act.type-text.desc': 'Type text automatically',
  'act.kill-process.label': 'Kill App', 'act.kill-process.desc': 'Terminate a process by name',
  'act.volume-set.label': 'Exact Vol.', 'act.volume-set.desc': 'Set volume to an exact %',
  'act.folder.label': 'Folder', 'act.folder.desc': 'Open a sub-deck of buttons',
  'act.media-play-pause.label': 'Play/Pause', 'act.media-play-pause.desc': 'Play / Pause',
  'act.media-next.label': 'Next', 'act.media-next.desc': 'Next track',
  'act.media-prev.label': 'Previous', 'act.media-prev.desc': 'Previous track',
  'act.volume-up.label': 'Vol. ＋', 'act.volume-up.desc': 'Volume up',
  'act.volume-down.label': 'Vol. −', 'act.volume-down.desc': 'Volume down',
  'act.mute.label': 'Mute', 'act.mute.desc': 'Mute / unmute',
  'act.brightness.label': 'Brightness', 'act.brightness.desc': 'Control monitor brightness',
  'act.notify.label': 'Notification', 'act.notify.desc': 'Show a Windows notification',
  'act.set-var.label': 'Var: Set', 'act.set-var.desc': 'Assign a value to a global variable',
  'act.incr-var.label': 'Var: Add', 'act.incr-var.desc': 'Increment or decrement a numeric variable',
  'act.webhook.label': 'Webhook', 'act.webhook.desc': 'POST/GET to a URL with body and headers',
  'act.tts.label': 'Text-to-speech', 'act.tts.desc': 'Read a text out loud',
  'act.region-capture.label': 'Capture', 'act.region-capture.desc': 'Open Windows region capture',
  'act.rgb-color.label': 'RGB Color', 'act.rgb-color.desc': 'Paint a solid color on an RGB device',
  'act.rgb-mode.label': 'RGB Mode', 'act.rgb-mode.desc': 'Change the RGB mode/effect (Direct, Breathing, etc.)',
  'act.rgb-profile.label': 'RGB Profile', 'act.rgb-profile.desc': 'Apply a saved RGB profile',
  'act.window-snap.label': 'Snap Window', 'act.window-snap.desc': 'Move and resize a window to a quadrant',
  'act.branch.label': 'If / Else', 'act.branch.desc': 'Run action A or B based on a variable value',
  'act.countdown.label': 'Timer', 'act.countdown.desc': 'Wait N ms then run an action',
  'act.media-shuffle.label': 'Shuffle', 'act.media-shuffle.desc': 'Toggle shuffle on the active player (SMTC)',
  'act.media-repeat.label': 'Repeat', 'act.media-repeat.desc': 'Cycle repeat mode (none → list → track)',
  'act.macro.label': 'Macro', 'act.macro.desc': 'Recorded or configured key and mouse-click sequence',

  // ── RGB manager ──
  'rgb.connFailed': 'Connection failed: {err}',
  'rgb.connFailedNoServer': 'Connection failed (is the OpenRGB server running?)',
  'rgb.profilePartial': 'Some devices did not accept the profile.',
  'rgb.resizeFailed': 'The zone could not be resized.',
  'rgb.disconnect': 'DISCONNECT',
  'rgb.connect': 'CONNECT',
  'rgb.rescan': 'Rescan devices',
  'rgb.notConnected': 'NOT CONNECTED',
  'rgb.setPath': '· Set the path to OpenRGB.exe in the settings flyout (⚙ icon on the main screen → RGB section).',
  'rgb.serverHint': '· Make sure the SDK server is running (port {port}). VirtualDeck starts OpenRGB in --server mode, with no interface, so the zone-size dialog never appears.',
  'rgb.lastError': 'Last error: {err}',
  'rgb.devices': 'DEVICES',
  'rgb.noDevices': 'No devices detected.',
  'rgb.connectToSee': 'Connect to see devices.',
  'rgb.quickActions': 'QUICK ACTIONS',
  'rgb.allOff': 'ALL OFF',
  'rgb.allWhite': 'ALL WHITE',
  'rgb.accentColor': 'ACCENT COLOR',
  'rgb.profiles': 'RGB PROFILES',
  'rgb.noProfiles': 'No profiles yet.',
  'rgb.apply': 'APPLY',
  'rgb.save': 'SAVE',
  'rgb.newProfile': 'New profile...',
  'rgb.connected': 'CONNECTED · {n} DEV',
  'rgb.serverUp': 'SERVER RUNNING',
  'rgb.disconnected': 'DISCONNECTED',
  'rgb.color': 'COLOR',
  'rgb.mode': 'MODE',
  'rgb.speed': 'SPEED · {n}%',
  'rgb.zones': 'ZONES',
  'rgb.zoneLeds': '{n} LEDS',
  'rgb.zoneResizable': ' · {min}-{max} RESIZ.',
  'rgb.paintLeds': 'PAINT INDIVIDUAL LEDs',
  'rgb.hide': 'HIDE',
  'rgb.show': 'SHOW',
  'rgb.noLeds': 'No LEDs reported for this device.',
  'rgb.notPerLed': '⚠ The current mode ({mode}) is not per-LED. Switch to Direct or Custom to see the changes.',
  'rgb.ledsHint': '{n} LEDs · Click = paint with the selected color',
  'rgb.calibrator': 'ARGB ZONE CALIBRATOR',
  'rgb.calibratorHelp': 'For each resizable zone: press IDENTIFY to light one LED white travelling down the whole chain. Count how many LEDs you saw and save that number. This replaces the OpenRGB dialog and persists in the local config.',
  'rgb.noResizable': 'No resizable zones detected.',
  'rgb.range': 'RANGE {min}–{max} · CURRENT {cur}',
  'rgb.saved': ' · SAVED {n}',
  'rgb.suggestion': '◆ Suggestion: {note}',
  'rgb.identify': 'IDENTIFY',
  'rgb.hint.unifan': 'Lian Li UNI Fan SL (16 LEDs per fan)',
  'rgb.hint.strimer24': 'Strimer Plus 24-pin',
  'rgb.hint.strimer8': 'Strimer Plus 8-pin',
  'rgb.hint.argb': 'Generic ARGB header (estimate)',
  // ── Floating bar ──
  'bar.short': 'BAR',
  'bar.close': 'Close the floating bar',
  'weather.loading': 'Loading weather...',
  'panel.noMedia': 'Nothing playing',
  'ed.pickSensor': '— Pick a sensor —',
  'brand.search': 'Search icon...',
  'cell.editShort': 'Edit',
  'macro.scrollHint': '(+ up, − down)',
  'ed.cancelCapture': '✕ cancel',
  'bulk.move': '↗ MOVE',
  'bulk.clear': '✕ CLEAR',
  'panel.openRgb': 'Open the RGB manager',
  'panel.clearLog': 'Clear the log',
  'ui.back': '← BACK',
  'brand.clearAll': 'CLEAR ALL',
  'brand.activeColor': 'ACTIVE COLOR',
  'brand.hint': '17×17 · Supports multi-colour · Animations follow the dot pattern',
  'brand.saveIcon': 'SAVE ICON ✓',
  'glyph.fromFont': 'LOAD FROM FONT',
  'glyph.empty': 'Empty — saving will remove it from the button',
  'ui.saveShort': 'SAVE',
  'set.noProfiles': 'No saved profiles.',
  'macro.recording': 'REC • press keys and click...',
  'macro.noSteps': 'No steps. Record a macro or add steps by hand.',
  'ed.killHint': 'Use the exact executable name. Equivalent to taskkill /IM name /F.',
  'ed.volumeHint': 'Sets the system master volume to the given percentage.',
  'ed.noRgbProfiles': 'No saved RGB profiles. Open the RGB screen and save one with the current state of your devices.',
  'ed.snapHint': 'With no process name, it snaps whichever window has focus when it runs.',
  'ed.radioHint': 'Every toggle in the same group turns off when this one turns on.',
  'ed.triggers': 'EXTERNAL TRIGGERS',
  'ed.thresholdHint': 'Warn paints the value amber, Crit red. Same units as the sensor.',
  'folder.empty': 'No buttons configured. Edit this button to add them.',
  'folder.esc': 'ESC TO CLOSE',
  'rgb.pickDevice': 'Pick a device on the left.',
  // ── Single interface words ──
  'ui.none': 'NONE',
  'ui.cancel': 'CANCEL',
  'ui.clear': 'CLEAR',
  'ui.fill': 'FILL',
  'ui.save': 'SAVE ✓',
  'ui.port': 'PORT',
  'ui.wallpaper': 'WALLPAPER',
  'ui.import': 'IMPORT',
  'ui.load': 'LOAD',
  'ui.repeat': 'REPEAT',
  'ui.times': 'TIMES',
  'ui.mouseL': 'L',
  'ui.mouseR': 'R',
  'ui.mouseM': 'M',
  'ui.units': 'UNITS',
  'ui.pause': 'PAUSE',
  'full.title': 'VIRTUALDECK · FULLSCREEN MODE',
  'ui.columns': 'COLUMNS',
  'ui.rows': 'ROWS',
  'ui.moveTo': 'MOVE TO...',
  // ── Settings, pages and menus ──
  'undo.duplicate': 'duplicate button',
  'undo.clear': 'clear button',
  'undo.addPage': 'add page',
  'undo.delPage': 'delete page',
  'undo.movePage': 'reorder pages',
  'undo.importPage': 'import page',
  'cell.edit': 'Edit button',
  'cell.duplicate': 'Duplicate',
  'cell.clear': 'Clear button',
  'set.accent': 'ACCENT COLOR',
  'set.scale': 'INTERFACE SCALE',
  'set.tiles': 'CELL SHAPE',
  'set.chime': 'CHIME',
  'set.profiles': 'PROFILES',
  'set.sound': 'SOUND ON PRESS',
  'set.profileName': 'Profile name...',
  'set.rgb': 'RGB (OPENRGB)',
  'set.rgbPath': 'OPENRGB.EXE PATH',
  'set.enabled': 'ENABLED',
  'set.rgbSpawn': 'LAUNCH OPENRGB ON START',
  'set.rgbAuto': 'AUTO-CONNECT',
  'set.sensors': 'SENSORS (LIBRE HARDWARE MONITOR)',
  'set.lhmPath': 'LHM PATH (empty = bundled)',
  'set.categories': 'VISIBLE CATEGORIES',
  'set.sensorWidget': 'SHOW SENSOR WIDGET',
  'set.lhmStart': 'START LHM WITH VIRTUALDECK',
  'set.lhmAdmin': 'START LHM AS ADMINISTRATOR (UAC)',
  'set.urlAcl': 'Registers a URL ACL reservation in Windows (one UAC prompt). After that LHM can run without admin.',
  'page.noRoom': 'No free slot on "{pagina}".',
  'page.tip': 'Click · Double-click to rename · Drag to reorder · Right-click for options',
  'page.add': 'Add page',
  'page.export': 'Export current page',
  'page.import': 'Import page from file',
  'page.rename': 'Rename',
  'page.delete': 'Delete page',
  'media.diagnose': 'Diagnose the music widget',
  'panel.weather': 'WEATHER',
  'panel.sensors': 'SENSORS',
  'panel.log': 'LOG',
  'panel.playing': 'NOW PLAYING',
  'full.clock': 'LOCAL TIME',
  'full.page': 'PAGE',
  'full.noMedia': 'NOTHING PLAYING',
  'brand.none': 'No brand icon',
  'brand.title': 'ANIMATED BRAND ICONS',
  'weather.none': 'No weather data',
  'glyph.title': '5×7 GLYPH EDITOR',
  'rgb.calibPending': '⚠ CALIBRATION PENDING',
  'ed.noSensors': '(no sensors: enable LHM and connect from the title bar)',
  // ── Action errors and labels ──
  'act.err.sinManejador': 'The "{tipo}" action is not implemented.',
  'act.err.noAppPath': 'The program path is missing.',
  'act.err.launch': 'Could not start: {que}. Check the path.',
  'act.err.noUrl': 'The URL is missing.',
  'act.err.openUrl': 'Could not open: {url}',
  'act.err.noShortcut': 'The shortcut is missing.',
  'act.err.shortcut': 'Could not open the shortcut.',
  'act.err.noDevice': 'The audio device is missing.',
  'act.err.deviceNotFound': 'Device "{name}" not found. Check the name in Settings → Sound.',
  'act.err.switchAudio': 'Could not switch audio to "{name}".',
  'act.err.noHotkey': 'The key combination is missing.',
  'act.err.hotkey': 'Could not send the shortcut {hotkey}.',
  'act.err.noBrightness': 'The brightness level is missing.',
  'act.err.brightness': 'Could not set the brightness (monitor without WMI support?).',
  'act.err.noClipText': 'The text to copy is missing.',
  'act.err.clipboard': 'Could not copy to the clipboard.',
  'act.err.noTypeText': 'The text to type is missing.',
  'act.err.type': 'Could not type the text.',
  'act.err.noProcess': 'The process name is missing.',
  'act.err.kill': 'Could not close "{name}". Is it running?',
  'act.err.noVolume': 'The volume level is missing.',
  'act.err.volume': 'Could not set the volume.',
  'act.err.notify': 'Could not show the notification.',
  'act.err.media': 'Could not send the media control ({cmd}).',
  'act.err.shuffle': 'Could not toggle shuffle (is a player running?).',
  'act.err.repeat': 'Could not change the repeat mode.',
  'act.err.macroEmpty': 'The macro has no steps.',
  'act.err.mediaKey': 'Could not send the media key ({tipo}).',
  'act.err.noVar': 'The variable name is missing.',
  'act.err.noWebhookUrl': 'The webhook URL is missing.',
  'act.err.headers': 'Invalid headers (malformed JSON).',
  'act.err.webhookStatus': 'Webhook {method} {url} → {status} {statusText}',
  'act.err.webhook': 'Webhook failed: {msg}',
  'act.err.noTtsText': 'The text to read is missing.',
  'act.err.tts': 'Could not play the text-to-speech.',
  'act.err.capture': 'Could not open the capture tool.',
  'act.err.noRgbColor': 'The RGB color is missing.',
  'act.err.rgbColor': 'Could not apply the RGB color (is OpenRGB connected?).',
  'act.err.noRgbMode': 'The RGB mode is missing.',
  'act.err.rgbMode': 'Could not apply the "{modo}" mode.',
  'act.err.noRgbProfile': 'The RGB profile name is missing.',
  'act.err.rgbProfileMissing': 'RGB profile "{name}" does not exist.',
  'act.err.rgbProfile': 'Could not apply the RGB profile.',
  'act.err.noRgbPreset': 'The RGB preset ID is missing.',
  'act.err.rgbPreset': 'Could not apply the "{id}" preset (is OpenRGB connected?).',
  'act.err.noSnap': 'The snap position is missing.',
  'act.err.snap': 'Could not snap the window (process not found?).',
  'act.err.unexpected': 'Unexpected error in {que}: {msg}',
  'act.err.script': 'The script ended with an error.',
  'act.err.macro': 'The macro failed.',
  'act.err.countdown': 'The timer sub-action failed.',
  'act.lbl.app': 'App',
  'act.lbl.web': 'Open URL',
  'act.lbl.shortcut': 'Shortcut',
  'act.lbl.audio': 'Switch audio',
  'act.lbl.hotkey': 'Shortcut',
  'act.lbl.clipboard': 'Copy to clipboard',
  'act.lbl.type': 'Type text',
  'act.lbl.kill': 'Close process',
  'act.lbl.notify': 'Notification',
  'act.lbl.webhook': 'Webhook',
  'act.lbl.tts': 'Text-to-speech',
  'act.lbl.capture': 'Region capture',
  'act.lbl.rgbMode': 'RGB mode',
  'act.lbl.rgbProfile': 'RGB profile',
  'act.lbl.rgbPreset': 'RGB preset',
  'act.lbl.snap': 'Window snap',
  'act.lbl.shuffle': 'Toggle shuffle',
  'act.lbl.repeat': 'Cycle repeat',
  'act.lbl.open': 'Open',
  'act.lbl.brightness': 'Brightness',
  'act.lbl.volume': 'Volume',
  'act.lbl.macro': 'Macro ({n} steps)',
  'bar.max': '{n} fit at this tile size',
  'bar.title': 'FLOATING BAR',
  'bar.back': '← BACK',
  'bar.enabled': 'SHOW THE BAR',
  'bar.column': 'COLUMN',
  'bar.dragHint': 'Drag a button from the right into a slot. The same button can only appear once.',
  'bar.remove': 'Remove from the bar',
  'bar.side': 'SCREEN SIDE',
  'bar.side.left': 'LEFT',
  'bar.side.right': 'RIGHT',
  'bar.opacity': 'OPACITY · {n}%',
  'bar.tileSize': 'TILE SIZE · {n} PX',
  'bar.position': 'POSITION',
  'bar.center': 'CENTER',
  'bar.available': 'CONFIGURED BUTTONS',
  'bar.noButtons': 'No configured buttons to drag yet.',
  'rgb.startupOn': 'Applied when VirtualDeck opens — click to unset',
  'rgb.startupOff': 'Apply this profile when VirtualDeck opens',
  'rgb.startupHint': '◉ = applied automatically when VirtualDeck opens.',
  'import.rejected': 'Import rejected: {motivo}',
  'import.badShape': 'invalid shape',
  'cell.tipEmpty': 'Click to configure · Right-click for more options',
  'cell.tipFilled': '{etiqueta} — click to run · Ctrl+click to select',
  'glyph.load': 'Load "{ch}"',
  'settings.tile.square': 'SQUARE',
  'settings.tile.fill': 'FILL AREA',
  'settings.tile.squareHelp': 'Cells always square; leaves a margin when the window is not proportional to the grid.',
  'settings.tile.fillHelp': 'Cells fill the whole area; they may become slightly rectangular.',
  'rgb.spawnFailed': 'Spawn failed: {error}',
  'rgb.connectFailed': 'Failed: {error}',
  'rgb.noServer': 'no server',
  'rgb.okDevices': 'OK · {n} devices',
  'rgb.testing': 'TESTING...',
  'rgb.test': 'TEST CONNECTION',
  'rgb.profileSaved': 'Profile "{nombre}" saved.',
  'sensors.lhmFailed': 'Could not start LHM: {error}',
  'sensors.unknown': 'unknown',
  'sensors.okCount': 'OK · {n} sensors',
  'sensors.noWebServer': 'Web server did not respond after 12s: {error}. Try running VirtualDeck as administrator.',
  'sensors.aclOk': 'URL ACL registered: {url} — LHM no longer needs admin.',
  'sensors.aclFailed': 'URL ACL registration failed: {error}',
  'sensors.noReply': 'no reply',
  'sensors.connectedCount': '● {n} sensors connected',
  'sensors.enabledNoConn': '○ enabled · not connected',
  'sensors.disabledDot': '○ disabled',
  'sensors.noData': 'No data. Check that LibreHardwareMonitor is running.',
  'sensors.offHint': 'Sensors disabled. Set up LHM from the title bar.',
  'macro.step.key': 'Key',
  'macro.step.hotkey': 'Hotkey',
  'macro.step.text': 'Text',
  'macro.step.click': 'Mouse click',
  'macro.step.move': 'Mouse move',
  'macro.step.delay': 'Delay (ms)',
  'macro.step.scroll': 'Scroll',
  'pin.setTitle': 'SET A 4-DIGIT PIN',
  'pin.exitTitle': 'ENTER PIN TO EXIT',
  'pin.setHelp': 'Needed once to turn kiosk mode on. It is stored in your config.',
  'pin.exitHelp': 'Kiosk mode is on. ESC asks for the PIN to leave.',
  'pin.save': 'SAVE',
  'pin.confirm': 'CONFIRM',
  'media.prev': 'Previous',
  'media.playPause': 'Play/Pause',
  'media.next': 'Next',
  'media.playing': 'Playing',
  'media.paused': 'Paused',
  'media.diagTitle': 'SMTC diagnostics:',
  'act.err.timeout': 'Action took over 60s and is treated as hung.',
  'settings.scaleRange': 'Range: 75% – 175%',
  'sensors.testing': 'TESTING...',
  'sensors.test': 'TEST',
  'sensors.registering': 'REGISTERING...',
  'sensors.registerAcl': 'REGISTER URL ACL',
  'sensors.adminHint': 'LHM ships with VirtualDeck. Sensors such as CPU/SMBus need admin — if data is missing, run VirtualDeck as administrator.',
  'macro.fieldText': 'TEXT',
  'macro.fieldKey': 'KEY',
  'macro.textPlaceholder': 'Text to type',
  'editor.previewHint': 'HOVER ✎ → EDIT',
  'editor.previewHint2': 'CLICK → RUN',
  'sound.click': 'Mechanical click',
  'sound.tick': 'Tick',
  'sound.thud': 'Thud',
  'sound.off': 'Silent',
  'validate.notObject': 'The file does not contain a valid JSON object.',
  'validate.missingPages': 'Missing the "pages" field (array).',
  'validate.emptyPages': '"pages" cannot be empty.',
  'validate.badPage': 'Page #{n} has an invalid shape (missing id/name).',
  'validate.missingButtons': 'Missing the "buttons" field (array).',
  'validate.badButton': 'Button #{n} has an invalid shape (missing id/page/label/action).',
  'validate.missingAccent': 'Missing the "accent" field (hex color).',
  'validate.missingWallpaper': 'Missing the "wallpaper" field.',
  'validate.badProfiles': '"profiles" must be an array.',
  'validate.badSound': '"soundOnPress" must be a boolean.',
  'undo.done': '↶ Undone: {label}',
  'undo.configChange': 'Configuration change',
  'undo.copyBetweenPages': 'copy between pages',
  'undo.moveBetweenPages': 'move between pages',
  'undo.renameTo': 'rename to "{nombre}"',
  'undo.loadProfile': 'load profile',
  'page.defaultName': 'PAGE {n}',
  'bug.sectionDesc': '## Description',
  'bug.descPlaceholder': '<!-- Describe the problem: what you were doing, what you expected, what happened -->',
  'bug.sectionSteps': '## Steps to reproduce',
  'bug.sectionEnv': '## Environment',
  'bug.envUnavailable': '- (not available)',
  'bug.sectionLog': '## Recent log',
  'bug.logTrimmed': '(Attach the exported log: "Export log" button under Help → About)',
  'rgb.preset.off': 'OFF',
  'rgb.preset.gaming': 'GAMING',
  'rgb.preset.cinema': 'CINEMA',
  'rgb.preset.work': 'WORK',
  'rgb.preset.rainbow': 'RAINBOW',
  'rgb.preset.night-blue': 'NIGHT BLUE',
  'rgb.preset.alert-red': 'ALERT RED',
  'editor.applyPreset': 'Apply preset: {nombre}',
  'full.kioskBadge': '🔒 KIOSK',
  'full.exit': 'EXIT ⤡',
  'page.importRejected': 'That file is not a VirtualDeck page export.',
  'page.importedName': 'IMPORTED',
  'ed.actionSequence': 'ACTION SEQUENCE (OPTIONAL)',
  'ed.snapHint2': 'Works best with global hotkeys, without going through VirtualDeck.',
  'cat.APPS': 'APPS',
  'cat.WEB': 'WEB',
  'cat.MEDIA': 'MEDIA',
  'cat.SISTEMA': 'SYSTEM',
  'cat.CREATIVO': 'CREATIVE',
  'cat.RGB': 'RGB',
  'act.err.noDelta': 'The adjust button has no step configured.',
  'act.err.noReadBrightness': 'Could not read the current brightness. External monitors usually do not expose it.',
  'act.err.noReadVolume': 'Could not read the current volume.',
  'act.adjust.label': 'Step up / down',
  'act.adjust.desc': 'Raises or lowers brightness or volume from wherever it is',
};
