import type { Dict } from './tipos';

/**
 * Fragmento del diccionario ingles: catalogo de tipos de accion, errores y etiquetas.
 *
 * Se fusiona en `en.ts`. Las claves son estables (no el texto).
 */
export const EN_ACCIONES: Dict = {
  // — Action types (editor picker) —
  'act.none.label': 'None', 'act.none.desc': 'No action assigned',
  'act.app.label': 'Open App', 'act.app.desc': 'Launch an application',
  'act.web.label': 'Website', 'act.web.desc': 'Open a URL in the browser',
  'act.shortcut.label': 'Shortcut', 'act.shortcut.desc': 'Open a file or folder',
  'act.script.label': 'Script', 'act.script.desc': 'Run PowerShell or CMD',
  'act.audio-device.label': 'Audio', 'act.audio-device.desc': 'Switch output device',
  'act.hotkey.label': 'Hotkey', 'act.hotkey.desc': 'Send a key combination',
  'act.clipboard.label': 'Clipboard', 'act.clipboard.desc': 'Copy text to clipboard',
  'act.type-text.label': 'Type Text', 'act.type-text.desc': 'Type text automatically',
  'act.kill-process.label': 'Kill App', 'act.kill-process.desc': 'Terminate a process by name',
  'act.volume-set.label': 'Exact Vol.', 'act.volume-set.desc': 'Set volume to an exact %',
  'act.folder.label': 'Folder', 'act.folder.desc': 'Open a sub-deck of buttons',
  'act.media-play-pause.label': 'Play/Pause', 'act.media-play-pause.desc': 'Play / Pause',
  'act.media-next.label': 'Next', 'act.media-next.desc': 'Next track',
  'act.media-prev.label': 'Previous', 'act.media-prev.desc': 'Previous track',
  'act.volume-up.label': 'Vol. ＋', 'act.volume-up.desc': 'Volume up',
  'act.volume-down.label': 'Vol. −', 'act.volume-down.desc': 'Volume down',
  'act.mute.label': 'Mute', 'act.mute.desc': 'Mute / unmute',
  'act.brightness.label': 'Brightness', 'act.brightness.desc': 'Control monitor brightness',
  'act.notify.label': 'Notification', 'act.notify.desc': 'Show a Windows notification',
  'act.set-var.label': 'Var: Set', 'act.set-var.desc': 'Assign a value to a global variable',
  'act.incr-var.label': 'Var: Add', 'act.incr-var.desc': 'Increment or decrement a numeric variable',
  'act.webhook.label': 'Webhook', 'act.webhook.desc': 'POST/GET to a URL with body and headers',
  'act.tts.label': 'Text-to-speech', 'act.tts.desc': 'Read a text out loud',
  'act.region-capture.label': 'Capture', 'act.region-capture.desc': 'Open Windows region capture',
  'act.rgb-color.label': 'RGB Color', 'act.rgb-color.desc': 'Paint a solid color on an RGB device',
  'act.rgb-mode.label': 'RGB Mode', 'act.rgb-mode.desc': 'Change the RGB mode/effect (Direct, Breathing, etc.)',
  'act.rgb-profile.label': 'RGB Profile', 'act.rgb-profile.desc': 'Apply a saved RGB profile',
  'act.rgb-preset.label': 'RGB Preset', 'act.rgb-preset.desc': 'Apply one of the 18 ready-made moods (Gaming, Cinema, Work…)',
  'act.window-snap.label': 'Snap Window', 'act.window-snap.desc': 'Move and resize a window to a quadrant',
  'act.branch.label': 'If / Else', 'act.branch.desc': 'Run action A or B based on a variable value',
  'act.countdown.label': 'Timer', 'act.countdown.desc': 'Wait N ms then run an action',
  'act.media-shuffle.label': 'Shuffle', 'act.media-shuffle.desc': 'Toggle shuffle on the active player (SMTC)',
  'act.media-repeat.label': 'Repeat', 'act.media-repeat.desc': 'Cycle repeat mode (none → list → track)',
  'act.macro.label': 'Macro', 'act.macro.desc': 'Recorded or configured key and mouse-click sequence',
  // ── Action errors and labels ──
  'act.err.sinManejador': 'The "{tipo}" action is not implemented.',
  'act.err.noAppPath': 'The program path is missing.',
  'act.err.launch': 'Could not start: {que}. Check the path.',
  'act.err.noUrl': 'The URL is missing.',
  'act.err.openUrl': 'Could not open: {url}',
  'act.err.noShortcut': 'The shortcut is missing.',
  'act.err.shortcut': 'Could not open the shortcut.',
  'act.err.noDevice': 'The audio device is missing.',
  'act.err.deviceNotFound': 'Device "{name}" not found. Check the name in Settings → Sound.',
  'act.err.switchAudio': 'Could not switch audio to "{name}".',
  'act.err.noHotkey': 'The key combination is missing.',
  'act.err.hotkey': 'Could not send the shortcut {hotkey}.',
  'act.err.noBrightness': 'The brightness level is missing.',
  'act.err.brightness': 'Could not set the brightness (monitor without WMI support?).',
  'act.err.noClipText': 'The text to copy is missing.',
  'act.err.clipboard': 'Could not copy to the clipboard.',
  'act.err.noTypeText': 'The text to type is missing.',
  'act.err.type': 'Could not type the text.',
  'act.err.noProcess': 'The process name is missing.',
  'act.err.kill': 'Could not close "{name}". Is it running?',
  'act.err.noVolume': 'The volume level is missing.',
  'act.err.volume': 'Could not set the volume.',
  'act.err.notify': 'Could not show the notification.',
  'act.err.media': 'Could not send the media control ({cmd}).',
  'act.err.shuffle': 'Could not toggle shuffle (is a player running?).',
  'act.err.repeat': 'Could not change the repeat mode.',
  'act.err.macroEmpty': 'The macro has no steps.',
  'act.err.mediaKey': 'Could not send the media key ({tipo}).',
  'act.err.noVar': 'The variable name is missing.',
  'act.err.noWebhookUrl': 'The webhook URL is missing.',
  'act.err.headers': 'Invalid headers (malformed JSON).',
  'act.err.webhookStatus': 'Webhook {method} {url} → {status} {statusText}',
  'act.err.webhook': 'Webhook failed: {msg}',
  'act.err.noTtsText': 'The text to read is missing.',
  'act.err.tts': 'Could not play the text-to-speech.',
  'act.err.capture': 'Could not open the capture tool.',
  'act.err.noRgbColor': 'The RGB color is missing.',
  'act.err.rgbColor': 'Could not apply the RGB color (is OpenRGB connected?).',
  'act.err.noRgbMode': 'The RGB mode is missing.',
  'act.err.rgbMode': 'Could not apply the "{modo}" mode.',
  'act.err.noRgbProfile': 'The RGB profile name is missing.',
  'act.err.rgbProfileMissing': 'RGB profile "{name}" does not exist.',
  'act.err.rgbProfile': 'Could not apply the RGB profile.',
  'act.err.noRgbPreset': 'The RGB preset ID is missing.',
  'act.err.rgbPreset': 'Could not apply the "{id}" preset (is OpenRGB connected?).',
  'act.err.noSnap': 'The snap position is missing.',
  'act.err.snap': 'Could not snap the window (process not found?).',
  'act.err.unexpected': 'Unexpected error in {que}: {msg}',
  'act.err.script': 'The script ended with an error.',
  'act.err.macro': 'The macro failed.',
  'act.err.countdown': 'The timer sub-action failed.',
  'act.lbl.app': 'App',
  'act.lbl.web': 'Open URL',
  'act.lbl.shortcut': 'Shortcut',
  'act.lbl.audio': 'Switch audio',
  'act.lbl.hotkey': 'Shortcut',
  'act.lbl.clipboard': 'Copy to clipboard',
  'act.lbl.type': 'Type text',
  'act.lbl.kill': 'Close process',
  'act.lbl.notify': 'Notification',
  'act.lbl.webhook': 'Webhook',
  'act.lbl.tts': 'Text-to-speech',
  'act.lbl.capture': 'Region capture',
  'act.lbl.rgbColor': 'RGB color',
  'act.lbl.rgbMode': 'RGB mode',
  'act.lbl.rgbProfile': 'RGB profile',
  'act.lbl.rgbPreset': 'RGB preset',
  'act.lbl.snap': 'Window snap',
  'act.lbl.shuffle': 'Toggle shuffle',
  'act.lbl.repeat': 'Cycle repeat',
  'act.lbl.open': 'Open',
  'act.lbl.brightness': 'Brightness',
  'act.lbl.volume': 'Volume',
  'act.lbl.macro': 'Macro ({n} steps)',
  'act.err.timeout': 'Action took over 60s and is treated as hung.',
  'cat.APPS': 'APPS',
  'cat.WEB': 'WEB',
  'cat.MEDIA': 'MEDIA',
  'cat.SISTEMA': 'SYSTEM',
  'cat.CREATIVO': 'CREATIVE',
  'cat.RGB': 'RGB',
  'act.err.noDelta': 'The adjust button has no step configured.',
  'act.err.noReadBrightness': 'Could not read the current brightness. External monitors usually do not expose it.',
  'act.err.noReadVolume': 'Could not read the current volume.',
  'act.adjust.label': 'Step up / down',
  'act.adjust.desc': 'Raises or lowers brightness or volume from wherever it is',
  'act.err.noRemoteHost': 'No machine to send to.',
  'act.err.noRemoteToken': "The other machine's token is missing.",
  'act.err.remote': 'The other machine refused the order: {error}',
  'act.remote.label': 'Remote deck (other PC)',
  'act.remote.desc': 'Press a button on another VirtualDeck on the local network',
  'act.mobile-remote.label': 'Mobile remote',
  'act.mobile-remote.desc': 'Generate pairing code or toggle the mobile web server',
  'act.err.mobileCode': 'Could not generate pairing code.',
  'act.mobile.pairCodeToast': 'Pairing code: {code} (copied to clipboard, valid for 5 min)',
  'act.mobile.serverStarted': 'Mobile remote server started on port {port}',
  'act.mobile.serverStopped': 'Mobile remote server stopped',
  // 5.0 — Third-party integrations (Discord & Spotify)
  'act.discord.label': 'Discord',
  'act.discord.desc': 'Discord voice control: mute or deafen via local Named Pipe',
  'act.spotify.label': 'Spotify',
  'act.spotify.desc': 'Play playlists, tracks, or albums directly on Spotify or transfer playback',
  'act.err.discord': 'Could not communicate with Discord. Make sure it is running.',
  'act.err.spotifyNoUri': 'You must provide a Spotify URI or link to play.',
  'act.err.spotifyNoDevice': 'You must specify a Spotify device ID.',
  'act.err.spotify': 'Could not play on Spotify.',
};
