import type { Dict } from './tipos';

/**
 * Fragmento del diccionario ingles: panel de ajustes, sensores, RGB, galeria e integraciones.
 *
 * Se fusiona en `en.ts`. Las claves son estables (no el texto).
 */
export const EN_AJUSTES: Dict = {

  // ── RGB manager ──
  'rgb.connFailed': 'Connection failed: {err}',
  'rgb.connFailedNoServer': 'Connection failed (is the OpenRGB server running?)',
  'rgb.profilePartial': 'Some devices did not accept the profile.',
  'rgb.resizeFailed': 'The zone could not be resized.',
  'rgb.disconnect': 'DISCONNECT',
  'rgb.connect': 'CONNECT',
  'rgb.rescan': 'Rescan devices',
  'rgb.notConnected': 'NOT CONNECTED',
  'rgb.setPath': '· Set the path to OpenRGB.exe in the settings flyout (settings button on the main screen → RGB section).',
  'rgb.serverHint': '· Make sure the SDK server is running (port {port}). VirtualDeck starts OpenRGB in --server mode, with no interface, so the zone-size dialog never appears.',
  'rgb.lastError': 'Last error: {err}',
  'rgb.devices': 'DEVICES',
  'rgb.noDevices': 'No devices detected.',
  'rgb.connectToSee': 'Connect to see devices.',
  'rgb.quickActions': 'QUICK ACTIONS',
  'rgb.allOff': 'ALL OFF',
  'rgb.allWhite': 'ALL WHITE',
  'rgb.accentColor': 'ACCENT COLOR',
  'rgb.profiles': 'RGB PROFILES',
  'rgb.presets': 'PRESETS',
  'rgb.noProfiles': 'No profiles yet.',
  'rgb.apply': 'APPLY',
  'rgb.save': 'SAVE',
  'rgb.newProfile': 'New profile...',
  'rgb.connected': 'CONNECTED · {n} DEV',
  'rgb.serverUp': 'SERVER RUNNING',
  'rgb.disconnected': 'DISCONNECTED',
  'rgb.deviceOne': 'DEVICE',
  'rgb.deviceMany': 'DEVICES',
  'rgb.color': 'COLOR',
  'rgb.mode': 'MODE',
  'rgb.speed': 'SPEED · {n}%',
  'rgb.zones': 'ZONES',
  'rgb.zoneLeds': '{n} LEDS',
  'rgb.zoneResizable': ' · {min}-{max} RESIZ.',
  'rgb.paintLeds': 'PAINT INDIVIDUAL LEDs',
  'rgb.hide': 'HIDE',
  'rgb.show': 'SHOW',
  'rgb.noLeds': 'No LEDs reported for this device.',
  'rgb.notPerLed': 'The current mode ({mode}) is not per-LED. Switch to Direct or Custom to see the changes.',
  'rgb.ledsHint': '{n} LEDs · Click = paint with the selected color',
  'rgb.calibrator': 'ARGB ZONE CALIBRATOR',
  'rgb.calibratorHelp': 'For each resizable zone: press IDENTIFY to light one LED white travelling down the whole chain. Count how many LEDs you saw and save that number. This replaces the OpenRGB dialog and persists in the local config.',
  'rgb.noResizable': 'No resizable zones detected.',
  'rgb.range': 'RANGE {min}–{max} · CURRENT {cur}',
  'rgb.saved': ' · SAVED {n}',
  'rgb.suggestion': '◆ Suggestion: {note}',
  'rgb.identify': 'IDENTIFY',
  'rgb.hint.unifan': 'Lian Li UNI Fan SL (16 LEDs per fan)',
  'rgb.hint.strimer24': 'Strimer Plus 24-pin',
  'rgb.hint.strimer8': 'Strimer Plus 8-pin',
  'rgb.hint.argb': 'Generic ARGB header (estimate)',
  'set.noProfiles': 'No saved profiles.',
  'rgb.pickDevice': 'Pick a device on the left.',
  'set.appearance': 'APPEARANCE & THEME',
  'set.system': 'SYSTEM & WINDOW',
  'set.accent': 'ACCENT COLOR',
  'set.scale': 'INTERFACE SCALE',
  'set.tiles': 'CELL SHAPE',
  'set.chime': 'CHIME',
  'set.profiles': 'PROFILES',
  'set.sound': 'SOUND ON PRESS',
  'set.profileName': 'Profile name...',
  'set.rgb': 'RGB (OPENRGB)',
  'set.rgbPath': 'OPENRGB.EXE PATH',
  'set.enabled': 'ENABLED',
  'set.rgbSpawn': 'LAUNCH OPENRGB ON START',
  'set.rgbAuto': 'AUTO-CONNECT',
  'set.gallery': 'PROFILE GALLERY',
  'gal.load': 'LOAD',
  'gal.loading': 'LOADING...',
  'gal.hint': 'The project gallery opens with the button above. Any other one you or someone you trust hosts works too: paste the address of its manifest.json. Either way you are shown what the profile will run before importing.',
  'gal.official': 'PROJECT GALLERY',
  'gal.failed': 'Could not load: {error}',
  'gal.empty': 'That manifest has no valid profiles.',
  'gal.notADeck': 'That file does not look like a deck: it has no pages or no buttons.',
  'gal.unknownTypes': 'This profile uses actions this version does not know ({tipos}). Its buttons would do nothing. Update VirtualDeck, or ask the author for a compatible profile.',
  'gal.warn': 'A profile is not just data. What you see below will run on your computer when you press those buttons. Review it before importing.',
  'gal.counts': 'It brings {n} buttons.',
  'gal.launches': 'It opens these programs or files:',
  'gal.runs': 'It runs these scripts:',
  'gal.sends': 'Sends data to these addresses when pressed:',
  'gal.types': 'Types or presses this on your machine (typing is running, too):',
  'gal.hotkeys': 'It registers these global hotkeys: {list}',
  'gal.nothingRisky': 'It launches no programs and runs no scripts.',
  'gal.import': 'IMPORT AS PROFILE',
  'gal.importAndAppend': '+ ADD TO DECK (NEW PAGE)',
  'gal.importAndAppendHint': 'Creates a new page with these buttons without wiping your current deck.',
  'gal.importOnly': 'SAVE TO PROFILES',
  'gal.importOnlyHint': 'Only saves it into your profile list to use later.',
  'gal.kind.page': 'PAGE',
  'gal.kind.profile': 'PROFILE',
  'gal.requires': 'Requires: ',
  'gal.addPage': '+ ADD PAGE',
  'gal.addPageHint': 'Creates a new page with these buttons without wiping your current deck.',
  'gal.notAPage': 'That file is not a standalone VirtualDeck page (missing page or buttons).',
  'gal.hotkeysStripped': 'Page added. Removed {n} global hotkeys that clashed with yours.',
  'gal.needsUpdate': 'That content needs VirtualDeck {version} or later. Update the app to install it.',
  'gal.auto': 'Runs on its own, without pressing:',
  'gal.integrations': 'Other effects on press:',
  'set.remote': 'MOBILE REMOTE & WEB SERVER',
  'set.remoteStep1': '1. Open this address in your phone browser:',
  'set.remoteWifiHint': 'Your phone and this PC must be connected to the same Wi-Fi network.',
  'set.remoteStep2': '2. Pairing code:',
  'set.remotePairCodeHint': 'Type this 6-digit code on your phone screen. Expires in {min} min.',
  'set.remoteAdvanced': 'Advanced settings & API',
  'set.remoteLocalOnly': 'Only answer this computer (disable Wi-Fi)',
  'set.remoteToken': 'TOKEN',
  'set.remoteTokenHint': 'Click to show or hide the token.',
  'set.remoteNewToken': 'NEW TOKEN',
  'set.remoteCopyToken': 'COPY',
  'set.remotePair': 'GET PAIRING CODE',
  'set.remotePairHint': 'On your phone, open {url} and type the code. It expires in {min} min.',
  'set.remotePairNeedsLan': 'For the phone to reach it you must turn on ALLOW LOCAL NETWORK.',
  'set.remoteLan': 'ALLOW LOCAL NETWORK',
  'set.remoteLanWarn': 'Off, it only answers this computer. On, anyone on your network holding the token can press buttons, including ones that run scripts. The connection is not encrypted.',
  'set.remoteListening': 'Listening on {url}',
  'set.remoteStopped': 'Stopped.',
  'set.remoteCopyUrl': 'COPY LINK',
  'set.remoteMdns': 'Or by network name (mDNS): {url}',
  'set.remoteFirewallOk': 'Windows Firewall: Rule active (port {port})',
  'set.remoteFirewallWarn': 'Windows Firewall: Port {port} may be blocked on local network.',
  'set.remoteFirewallBtn': 'OPEN IN FIREWALL',
  'set.remoteFirewallOpening': 'CONFIGURING...',
  'set.remoteFirewallDone': 'Rule created in Windows Firewall.',
  'set.remoteFirewallFailed': 'Could not create rule: {error}',
  'set.remoteHint': 'The token goes in the X-VD-Token header, not in the address. Routes: /api/ping, /api/buttons, /api/press/<id>, /api/press?label=<label>, /api/page/<n>.',
  'set.musicPanel': 'MUSIC PANEL',
  'set.musicPanelHint': 'Appears next to the grid only while something is playing, with large cover art and finger-sized buttons.',
  'set.sensors': 'SENSORS (LIBRE HARDWARE MONITOR)',
  'set.lhmPath': 'LHM PATH (empty = auto-detect)',
  'sensors.catOther': 'OTHER',
  'set.categories': 'VISIBLE CATEGORIES',
  'set.sensorWidget': 'SHOW SENSOR WIDGET',
  'set.lhmStart': 'START LHM WITH VIRTUALDECK',
  'set.lhmAdmin': 'START LHM AS ADMINISTRATOR (UAC)',
  'set.urlAcl': 'Registers a URL ACL reservation in Windows (one UAC prompt). After that LHM can run without admin.',
  'rgb.calibPending': 'CALIBRATION PENDING',
  'rgb.pickProfile': '— Pick a profile —',
  'rgb.startupOn': 'Applied when VirtualDeck opens — click to unset',
  'rgb.startupOff': 'Apply this profile when VirtualDeck opens',
  'rgb.startupHint': 'Checked = applied automatically when VirtualDeck opens.',
  'rgb.spawnFailed': 'Spawn failed: {error}',
  'rgb.connectFailed': 'Failed: {error}',
  'rgb.noServer': 'no server',
  'rgb.okDevices': 'OK · {n} devices',
  'rgb.testing': 'TESTING...',
  'rgb.test': 'TEST CONNECTION',
  'rgb.profileSaved': 'Profile "{nombre}" saved.',
  'rgb.profileUpdated': 'Profile "{nombre}" overwritten.',
  'rgb.calibrate': 'CALIBRATE',
  'rgb.zoneCount': '{n} ZONE',
  'rgb.zoneCountN': '{n} ZONES',
  'rgb.ledCount': '{n} LEDS',
  'sensors.lhmFailed': 'Could not start LHM: {error}',
  'sensors.unknown': 'unknown',
  'sensors.okCount': 'OK · {n} sensors',
  'sensors.noWebServer': 'Web server did not respond after 12s: {error}. Try running VirtualDeck as administrator.',
  'sensors.aclOk': 'URL ACL registered: {url} — LHM no longer needs admin.',
  'sensors.aclFailed': 'URL ACL registration failed: {error}',
  'sensors.noReply': 'no reply',
  'sensors.connectedCount': '{n} SENSORS CONNECTED',
  'sensors.enabledNoConn': 'ENABLED · NOT CONNECTED',
  'sensors.disabledDot': 'DISABLED',
  'sensors.noData': 'No data. Check that LibreHardwareMonitor is running.',
  'sensors.offHint': 'Sensors disabled. Set up LHM from the title bar.',
  'sensors.testing': 'TESTING...',
  'sensors.test': 'TEST',
  'sensors.lhmStart': 'START LHM',
  'sensors.lhmStarting': 'STARTING...',
  'sensors.lhmRunning': 'LHM RUNNING',
  'sensors.lhmStop': 'STOP LHM',
  'sensors.lhmMissing': 'LibreHardwareMonitor is not installed. Download it, open it and enable Options → Remote Web Server → Run, on port 8085.',
  'sensors.lhmDownload': 'Download LHM',
  'sensors.lhmFound': 'Found at {ruta}',
  'set.tablet': 'TOUCHSCREEN',
  'set.tabletOpen': 'SET UP TOUCHSCREEN',
  'set.tabletHelp': 'Opens the Windows tool where you tell it which monitor responds to touch. Press "Setup" and follow the prompt on the screen you plan to use.',
  'set.tabletFailed': 'Could not open it. This machine may not have a touchscreen.',
  'sensors.registering': 'REGISTERING...',
  'sensors.registerAcl': 'REGISTER URL ACL',
  'sensors.hostHint0000': '0.0.0.0 means "listen on all network cards". To connect VirtualDeck on this PC, use 127.0.0.1.',
  'sensors.adminHint': 'LHM is installed separately, like OpenRGB. Some sensors, such as CPU or SMBus, need administrator rights: if data is missing, run LibreHardwareMonitor as administrator.',
  'sound.click': 'Mechanical click',
  'sound.tick': 'Tick',
  'sound.thud': 'Thud',
  'sound.off': 'Silent',
  'rgb.preset.off': 'OFF',
  'rgb.preset.gaming': 'GAMING',
  'rgb.preset.cinema': 'CINEMA',
  'rgb.preset.work': 'WORK',
  'rgb.preset.rainbow': 'RAINBOW',
  'rgb.preset.night-blue': 'NIGHT BLUE',
  'rgb.preset.alert-red': 'ALERT RED',
  'rgb.preset.reading': 'READING',
  'rgb.preset.focus': 'FOCUS',
  'rgb.preset.dim': 'DIM',
  'rgb.preset.sunset': 'SUNSET',
  'rgb.preset.ocean': 'OCEAN',
  'rgb.preset.forest': 'FOREST',
  'rgb.preset.candle': 'CANDLE',
  'rgb.preset.violet': 'VIOLET',
  'rgb.preset.party': 'PARTY',
  'rgb.preset.wave': 'WAVE',
  'rgb.preset.strobe': 'STROBE',
  'rgb.uncalibrated': '{n} ARGB zones with no saved size.',
  'set.support': 'SUPPORT THE PROJECT',
  'set.autoProfiles': 'AUTOMATIC PROFILES & PAGES',
  'set.autoProfileSwitch': 'AUTO-SWITCH ON ACTIVE WINDOW',
  'set.autoProfileRestoreDefault': 'RESTORE PAGE 1 ON NO MATCH',
  'set.autoProfileHint': 'Automatically switches to the bound page or profile when that window comes into the foreground in Windows.',
  'set.profileTargetApp': 'Bound app (e.g. obs64)',
  'set.monitors': 'MONITORS & MULTI-DISPLAY',
  'set.monRefresh': 'Refresh monitor list',
  'set.monRefreshShort': 'REFRESH',
  'set.monPrimary': 'PRIMARY',
  'set.monCurrent': 'CURRENT',
  'set.monKioskTarget': 'KIOSK',
  'set.monTouch': 'TOUCH',
  'set.monMoveHere': 'Move window here',
  'set.monSetKiosk': 'Set for kiosk',
  'set.monIsKioskTarget': 'Kiosk display',
  'set.monNoDisplays': 'No additional displays detected.',
  'set.monitorsHint': 'VirtualDeck detects connected and disconnected displays in real time. Move the window to any secondary screen or configure which display opens full screen / kiosk mode.',
  'set.monSwitchQuick': 'Display {current} of {total} (click to switch)',
  'spotify.tokenRequired': 'Access token required for this operation',
};
