import type { Dict } from './tipos';

/**
 * Fragmento del diccionario ingles: chrome general, paginas, celdas, fondos, ayuda y tutorial.
 *
 * Se fusiona en `en.ts`. Las claves son estables (no el texto).
 */
export const EN_COMUN: Dict = {
  'settings.theme': 'THEME',
  'settings.theme.dark': 'DARK',
  'settings.theme.light': 'LIGHT',
  'settings.theme.dot480': 'DOT/480',
  'settings.theme.system': 'SYSTEM',
  'settings.language': 'LANGUAGE',
  'settings.language.system': 'SYSTEM',
  // Los nombres de idioma van cada uno en el suyo en los dos diccionarios:
  // quien busca "English" no lo encuentra bajo "Ingles".
  'settings.language.es': 'ESPAÑOL',
  'settings.language.en': 'ENGLISH',
  'settings.autostart': 'START WITH WINDOWS',
  'settings.alwaysOnTop': 'ALWAYS ON TOP',
  'settings.uiscale': 'INTERFACE SCALE',
  'settings.tiles': 'BUTTON SHAPE',
  'settings.tiles.square': 'SQUARE',
  'settings.tiles.fill': 'FILL',
  'main.search.placeholder': 'Label, app, URL, shortcut...',
  'main.search.title': 'FIND BUTTON',
  'main.search.empty': 'No buttons configured',
  'main.search.nomatch': 'No matches',
  'main.search.nav': '↑↓ NAVIGATE',
  'main.search.edit': '↵ EDIT',
  'main.search.exit': 'ESC CLOSE',
  'update.ready': 'Update {version} ready.',
  'update.restart': 'RESTART',
  'update.later': 'LATER',
  'onb.step': 'STEP {n} / 0{total}',
  'onb.skip': 'Skip',
  'onb.back': 'Back',
  'onb.next': 'Next',
  'onb.start': 'Get started',
  'onb.1.title': 'IDIOMA · LANGUAGE',
  'onb.1.body': 'Choose the application language. The rest of this tutorial and the entire interface will be shown in the language you select.',
  'onb.1.hint': 'SYSTEM follows your Windows language. You can change it any time in SETTINGS → LANGUAGE.',
  'onb.2.title': 'APPEARANCE',
  'onb.2.body': 'Choose the theme and accent color. Changes apply instantly, so you can see the result before continuing.',
  'onb.2.hint': 'The deck background is picked separately, with the WALLPAPER button in the top bar.',
  'onb.backup.export': 'EXPORT',
  'onb.backup.import': 'IMPORT',
  'onb.3.title': 'VIRTUALDECK',
  'onb.3.body': 'Your software Stream Deck. A grid of buttons that fire actions: open apps, websites and folders, switch audio, control music, run shortcuts, macros and more.',
  'onb.3.hint': 'Everything saves itself. No cloud, no accounts: 100% local.',
  'onb.4.title': 'YOUR BUTTONS',
  'onb.4.body': 'Click any empty cell to set it up. Pick a label, an icon and the action it should run. A normal click fires it; the context menu (right-click) edits, duplicates or clears it.',
  'onb.4.hint': 'Ctrl+click selects multiple buttons for bulk operations.',
  'onb.5.title': 'PAGES & GRID',
  'onb.5.body': 'Organize your buttons across several pages (tabs at the top). Switch between them with keys 1-9 or by swiping. Each page can have its own grid size.',
  'onb.5.hint': 'Drag a button onto another page tab to move it there.',
  'onb.6.title': 'WIDGETS & FULLSCREEN',
  'onb.6.body': 'A button can show a clock, weather, PC sensors, a variable or the music playing right now. Go fullscreen to use VirtualDeck as a dedicated panel on a tablet or second monitor.',
  'onb.6.hint': 'The music widget detects Spotify, YouTube, browsers and more.',
  'onb.7.title': 'BACKUP & HELP',
  'onb.7.body': 'Your whole setup lives in a single local file. Export it to keep a copy or move it to another PC, or import an existing one to start with the buttons you already had. Ctrl+K finds any button instantly, and Settings → Help & About has the docs, bug reporting and this tutorial.',
  'onb.7.hint': 'A fresh install has nothing to export yet: the button is here for when it does. Ready? Create your first button.',
  'hint.firstButton': 'Click an empty cell to create your first button.',
  'hint.settings': 'Theme, language, scale and more live here in Settings.',
  'hint.search': 'Tip: Ctrl+K finds any button instantly.',
  'hint.dismiss': 'Got it',
  'help.title': 'HELP & ABOUT',
  'help.docs': 'DOCUMENTATION',
  'help.report': 'REPORT BUG',
  'help.check': 'CHECK FOR UPDATES',
  'help.checking': 'CHECKING…',
  'help.support': 'SUPPORT',
  'help.donateIntro': 'VirtualDeck is free. If it helps you, you can support its development:',
  'help.openLog': 'OPEN LOG',
  'help.exportLog': 'EXPORT LOG',
  'help.noLog': 'There is no log to export yet: it is created when the first error happens.',
  'help.replay': 'REPLAY TUTORIAL',
  'help.credits': 'CREDITS & LICENSES',
  'help.bundled': ' (bundled)',
  'help.upd.ready': 'Update {version} ready — restart to apply.',
  'help.upd.downloading': 'Downloading update {version}…',
  'help.upd.error': 'Could not check for updates.',
  'help.upd.store': 'This copy came from the Microsoft Store: the Store delivers its updates.',
  'help.upd.disabled': 'Auto-update not available in this build (dev mode).',
  'help.upd.checkError': 'Error checking for updates.',
  'help.upd.checking': 'Checking for updates…',
  'tip.export': 'Export configuration',
  'tip.import': 'Import configuration',
  'tip.bar': 'Floating column of tiles over the desktop',
  'tip.rgb': 'RGB manager',
  'tip.settings': 'Settings',
  'tip.fullscreen': 'Fullscreen mode',
  'tip.minimize': 'Minimize',
  'tip.close': 'Close (minimizes to tray)',
  'wp.back': 'BACK',
  'wp.preview': 'PREVIEW',
  'wp.select': 'SELECT WALLPAPER',
  'wp.applied': 'APPLIED',
  'wp.apply': 'APPLY',
  'wp.selected': 'SELECTED',
  'wp.autosave': 'Changes are saved automatically when you press Apply.',
  'wp.name.solid': 'Solid',
  'wp.name.gradient': 'Blue Gradient',
  'wp.name.dotgrid': 'Dot Grid',
  'wp.name.scanlines': 'Scanlines',
  'wp.name.crt': 'CRT',
  'wp.name.mesh': 'Tech Mesh',
  'wp.name.photo': 'Neon',
  'wp.name.grid-blue': 'Blue Grid',
  'sidebar.hide': 'Hide sidebar',
  'sidebar.show': 'Show sidebar',
  // ── Floating bar ──
  'bar.short': 'BAR',
  'bar.close': 'Close the floating bar',
  // Las 23 condiciones WMO del widget de clima. Estaban escritas en espanol
  // dentro del propio componente: con la app en ingles el tooltip decia
  // «Parcial. nub.».
  'wx.0': 'Clear',
  'wx.1': 'Mostly clear',
  'wx.2': 'Partly cloudy',
  'wx.3': 'Overcast',
  'wx.45': 'Fog',
  'wx.48': 'Rime fog',
  'wx.51': 'Light drizzle',
  'wx.53': 'Moderate drizzle',
  'wx.55': 'Heavy drizzle',
  'wx.61': 'Light rain',
  'wx.63': 'Moderate rain',
  'wx.65': 'Heavy rain',
  'wx.71': 'Light snow',
  'wx.73': 'Moderate snow',
  'wx.75': 'Heavy snow',
  'wx.77': 'Snow grains',
  'wx.80': 'Light showers',
  'wx.81': 'Moderate showers',
  'wx.82': 'Heavy showers',
  'wx.85': 'Snow showers',
  'wx.95': 'Thunderstorm',
  'wx.96': 'Storm w/ hail',
  'wx.99': 'Severe storm',
  'wx.unknown': 'Unknown',
  'weather.loading': 'Loading weather...',
  'panel.noMedia': 'Nothing playing',
  'cell.editShort': 'Edit',
  'cell.quickVolumeSlider': 'Touch volume slider',
  'cell.quickBrightnessSlider': 'Touch brightness slider',
  'bulk.move': 'MOVE',
  'bulk.clear': 'CLEAR',
  'panel.openRgb': 'Open the RGB manager',
  'panel.clearLog': 'Clear the log',
  'ui.back': 'BACK',
  'ui.saveShort': 'SAVE',
  // ── Single interface words ──
  'ui.none': 'NONE',
  'ui.cancel': 'CANCEL',
  'ui.clear': 'CLEAR',
  'ui.fill': 'FILL',
  'ui.save': 'SAVE',
  'ui.port': 'PORT',
  'ui.wallpaper': 'WALLPAPER',
  'ui.import': 'IMPORT',
  'ui.load': 'LOAD',
  'ui.appendPages': '+ PAGE',
  'ui.appendPagesHint': 'Append buttons as a new page without replacing current deck',
  'ui.repeat': 'REPEAT',
  'ui.times': 'TIMES',
  'ui.mouseL': 'L',
  'ui.mouseR': 'R',
  'ui.mouseM': 'M',
  'ui.units': 'UNITS',
  'ui.pause': 'PAUSE',
  'full.title': 'VIRTUALDECK · FULLSCREEN MODE',
  'ui.columns': 'COLUMNS',
  'page.grid': 'GRID',
  'ui.rows': 'ROWS',
  'ui.moveTo': 'MOVE TO...',
  // ── Settings, pages and menus ──
  'undo.duplicate': 'duplicate button',
  'undo.clear': 'clear button',
  'undo.action': 'UNDO',
  'undo.addPage': 'add page',
  'undo.delPage': 'delete page',
  'undo.movePage': 'reorder pages',
  'undo.importPage': 'import page',
  'cell.edit': 'Edit button',
  'cell.duplicate': 'Duplicate',
  'cell.copy': 'Copy button',
  'cell.paste': 'Paste button',
  'cell.copied': 'Button copied to clipboard',
  'cell.pasted': 'Button pasted',
  'cell.clear': 'Clear button',
  'page.duplicate': 'Duplicate page',
  'undo.paste': 'paste button',
  'undo.duplicatePage': 'duplicate page',
  'config.repaired': 'The configuration had malformed parts ({partes}) and they were repaired so the app could open. Check your pages and buttons; if something is missing, restore a backup from Settings.',
  'config.damaged': 'The configuration could not be read: the file was damaged. A copy was saved to {ruta}. If you had buttons, restore them from Settings → Backups before carrying on.',
  'panel.music': 'MUSIC',
  'music.hide': 'Hide the panel',
  'media.unsupported': '{que} — the source does not support it',
  'media.noSkip': '{fuente} does not support skipping tracks for this playback. That is a limit of the app that is playing, not of the deck.',
  'media.shuffle': 'SHUFFLE',
  'media.repeat': 'REPEAT',
  'ui.left': 'LEFT',
  'ui.right': 'RIGHT',
  'page.noRoom': 'No free slot on "{pagina}".',
  'page.tip': 'Click · Double-click to rename · Drag to reorder · Right-click for options',
  'page.add': 'Add page',
  'page.export': 'Export current page',
  'page.import': 'Import page from file',
  'page.rename': 'Rename',
  'page.delete': 'Delete page',
  'media.diagnose': 'Diagnose the music widget',
  'panel.weather': 'WEATHER',
  'panel.sensors': 'SENSORS',
  'panel.log': 'LOG',
  'panel.noActivity': 'No activity',
  'panel.playing': 'NOW PLAYING',
  'full.clock': 'LOCAL TIME',
  'full.page': 'PAGE',
  'full.noMedia': 'NOTHING PLAYING',
  'weather.none': 'No weather data',
  'bar.max': '{n} fit at this tile size',
  'bar.title': 'FLOATING BAR',
  'bar.back': '← BACK',
  'bar.enabled': 'SHOW THE BAR',
  'bar.column': 'COLUMN',
  'bar.dragHint': 'Drag a button from the right into a slot. The same button can only appear once.',
  'bar.remove': 'Remove from the bar',
  'bar.side': 'SCREEN SIDE',
  'bar.side.left': 'LEFT',
  'bar.side.right': 'RIGHT',
  'bar.opacity': 'OPACITY · {n}%',
  'bar.tileSize': 'TILE SIZE · {n} PX',
  'bar.position': 'POSITION',
  'bar.center': 'CENTER',
  'bar.available': 'CONFIGURED BUTTONS',
  'bar.noButtons': 'No configured buttons to drag yet.',
  'import.rejected': 'Import rejected: {motivo}',
  'import.badShape': 'invalid shape',
  'cell.tipEmpty': 'Click to configure · Right-click for more options',
  'cell.tipFilled': '{etiqueta} — click to run · Ctrl+click to select',
  'settings.tile.square': 'SQUARE',
  'settings.tile.fill': 'FILL AREA',
  'settings.tile.squareHelp': 'Cells always square; leaves a margin when the window is not proportional to the grid.',
  'settings.tile.fillHelp': 'Cells fill the whole area; they may become slightly rectangular.',
  'pin.setTitle': 'SET A 4-DIGIT PIN',
  'pin.exitTitle': 'ENTER PIN TO EXIT',
  'pin.setHelp': 'Needed once to turn kiosk mode on. It is stored in your config.',
  'pin.exitHelp': 'Kiosk mode is on. ESC asks for the PIN to leave.',
  'pin.save': 'SAVE',
  'pin.confirm': 'CONFIRM',
  'media.prev': 'Previous',
  'media.playPause': 'Play/Pause',
  'media.next': 'Next',
  'media.playing': 'Playing',
  'media.paused': 'Paused',
  'media.diagTitle': 'SMTC diagnostics:',
  'settings.scaleRange': 'Range: 75% – 175%',
  'validate.notObject': 'The file does not contain a valid JSON object.',
  'validate.missingPages': 'Missing the "pages" field (array).',
  'validate.emptyPages': '"pages" cannot be empty.',
  'validate.badPage': 'Page #{n} has an invalid shape (missing id/name).',
  'validate.missingButtons': 'Missing the "buttons" field (array).',
  'validate.badButton': 'Button #{n} has an invalid shape (missing id/page/label/action).',
  'validate.missingAccent': 'Missing the "accent" field (hex color).',
  'validate.missingWallpaper': 'Missing the "wallpaper" field.',
  'validate.badProfiles': '"profiles" must be an array.',
  'validate.badSound': '"soundOnPress" must be a boolean.',
  'undo.done': 'Undone: {label}',
  'undo.configChange': 'Configuration change',
  'undo.copyBetweenPages': 'copy between pages',
  'undo.moveBetweenPages': 'move between pages',
  'undo.renameTo': 'rename to "{nombre}"',
  'undo.loadProfile': 'load profile',
  'page.defaultName': 'PAGE {n}',
  'bug.sectionDesc': '## Description',
  'bug.descPlaceholder': '<!-- Describe the problem: what you were doing, what you expected, what happened -->',
  'bug.sectionSteps': '## Steps to reproduce',
  'bug.sectionEnv': '## Environment',
  'bug.envUnavailable': '- (not available)',
  'bug.sectionLog': '## Recent log',
  'bug.logTrimmed': '(Attach the exported log: "Export log" button under Help → About)',
  'full.kioskBadge': 'KIOSK',
  'full.exit': 'EXIT',
  'page.importRejected': 'That file is not a VirtualDeck page export.',
  'page.importedName': 'IMPORTED',
  'undo.clearMany': 'clear {n} buttons',
  'undo.edit': 'edit "{nombre}"',
  'undo.gridSize': 'change grid to {tam}',
  'undo.reorder': 'reorder buttons',
  'undo.saveProfile': 'save profile "{nombre}"',
  'undo.appendProfile': 'append pages from "{nombre}"',
  'undo.updateProfile': 'overwrite profile "{nombre}"',
  'undo.deleteProfile': 'delete profile "{nombre}"',
  'bulk.selected': '{n} SELECTED',
  'bulk.selectedOne': '1 SELECTED',
  'bulk.copy': 'COPY',
  'bulk.partial': 'Only {n} of {total} fit: the target page ran out of empty slots.',
  'icons.count': '{n} icons · 17×17 dot-matrix · Hover to animate',
  'help.donateFree': 'It is free and stays free: donating unlocks nothing.',
  'btn.pin': 'PIN BUTTON',
  'btn.unpin': 'UNPIN BUTTON',
  'btn.pinnedHint': 'Global pinned button',
  'page.bindApp': 'BIND APPLICATION',
  'page.unbindApp': 'UNBIND',
  'page.targetApp': 'BOUND APPLICATION',
  'page.boundApp': 'Bound to',
  'page.bindTitle': 'BIND PAGE TO APPLICATION',
  'page.bindDesc': 'When the application comes into the foreground, VirtualDeck will automatically switch to this page.',
  'page.runningApps': 'RUNNING APPLICATIONS',
  'page.customAppPlaceholder': 'Process name (e.g. obs64, photoshop, code)',
  'undo.setPageTargetApp': 'bind app to page',
  'settings.integrations': 'THIRD-PARTY INTEGRATIONS',
  'settings.integrations.desc': 'Configuration and live status for Discord and Spotify Web API.',
  'settings.discord.title': 'DISCORD DESKTOP',
  'settings.spotify.title': 'SPOTIFY WEB API',
  'settings.spotify.token': 'WEB API ACCESS TOKEN (GLOBAL)',
  'settings.spotify.tokenDesc': 'Enables transferring playback and querying active devices from any cell.',
};
