import type { Dict } from './tipos';

/**
 * Fragmento del diccionario: pantalla de dispositivos (controladores físicos como el Stream Dock N3).
 *
 * Se fusiona en `en.ts`. Las claves son estables (no el texto).
 */
export const EN_DISPOSITIVOS: Dict = {
  'disp.nav': 'DEV',
  'disp.titulo': 'Devices',
  'disp.volver': 'Back',
  'disp.breadcrumb.config': 'Settings',
  'disp.detectados': 'Detected devices',
  'disp.conectado': 'Connected',
  'disp.desconectado': 'Disconnected',
  'disp.sinDispositivos': 'No devices configured',
  'disp.sinDispositivosDesc': 'Connect a Stream Dock N3 via USB to get started.',
  'disp.resumenN3': '6 LCD keys (64×64) · 3 buttons · 3 knobs',
  'disp.brillo': 'LCD Brightness',
  'disp.serial': 'Serial No.',
  'disp.pagina': 'Linked page',
  'disp.vacio': 'Empty',
  'disp.tecla': 'LCD Key {n}',
  'disp.boton': 'Button {n}',
  'disp.perilla': 'Knob {n}',
  'disp.izq': 'Turn left',
  'disp.pulsar': 'Press',
  'disp.der': 'Turn right',
  'disp.editar': 'Edit action',
  'disp.inspector.titulo': 'Control properties',
  'disp.inspector.tipo': 'Control type',
  'disp.inspector.accion': 'Assigned action',
  'disp.inspector.sinAccion': 'No action assigned',
  'disp.inspector.ayuda': 'Click any key, button or knob action to edit its action.',
  'disp.avisoDesconectado': 'Device disconnected. You can configure its actions; they will sync when connected.',
  'disp.avisoSinPagina': 'This device does not have an assigned deck page yet.',
  'disp.tipo.tecla': 'LCD screen (64×64) with switch',
  'disp.tipo.boton': 'Physical mechanical button',
  'disp.tipo.perilla': 'Rotary encoder (3 actions)',
  'disp.tipo.tira': 'Touch strip (2 actions)',
  'disp.experimental': 'Unverified',
  'disp.experimentalDesc': 'This model has not been tested with physical hardware.',
  'disp.rotacion': 'Rotation',
  'disp.rotacionAyuda': 'If images appear rotated, change it.',
  'disp.modeloDesconocido': 'Unknown model',
  'disp.modeloDesconocidoDesc': 'No physical layout available for this model.',
  'disp.tira': 'Touch strip {n}',
  'disp.deslizarIzq': 'Swipe left',
  'disp.deslizarDer': 'Swipe right',
  'disp.resumen.teclas': '{n} LCD keys',
  'disp.resumen.botones': '{n} buttons',
  'disp.resumen.perillas': '{n} knobs',
  'disp.resumen.tiras': '{n} touch strips',
  'disp.paginas': 'Device pages',
  'disp.paginaNueva': 'New device page',
  'disp.paginaPredeterminada': 'Default',
  'disp.paginaEnAparato': 'On device',
  'disp.renombrarPagina': 'Rename page',
  'disp.borrarPagina': 'Delete page',
  'disp.borrarUltima': 'Cannot delete: it is the last page of the device',
  'disp.vincularApp': 'Bind application',
  'disp.panel.dispositivos': 'Devices',
  'disp.panel.inspector': 'Inspector',
  'disp.cerrar': 'Close',

  // Dock control gestures (roadmap 66)
  'disp.gesto.giroIzq': 'TURN LEFT',
  'disp.gesto.pulsar': 'PRESS',
  'disp.gesto.giroDer': 'TURN RIGHT',
  'disp.gesto.deslizar': 'SWIPE LEFT/RIGHT',
  'disp.gesto.deslizarIzq': 'SWIPE LEFT',
  'disp.gesto.deslizarDer': 'SWIPE RIGHT',

  // Control inspector (roadmap 66)
  'disp.inspector.otrosGestos': 'Other knob gestures',

  // Action descriptions for dock controls (roadmap 66)
  'disp.desc.sinAccion': 'NO ACTION',
  'disp.desc.mute': 'MUTE AUDIO',
  'disp.desc.mediaNext': 'NEXT TRACK',
  'disp.desc.mediaPrev': 'PREVIOUS TRACK',
  'disp.desc.mediaPlayPause': 'PLAY / PAUSE',
  'disp.desc.bajarVolumen': 'LOWER VOLUME {n} %',
  'disp.desc.subirVolumen': 'RAISE VOLUME {n} %',
  'disp.desc.volumen': 'VOLUME',
  'disp.desc.bajarBrillo': 'LOWER BRIGHTNESS {n} %',
  'disp.desc.subirBrillo': 'RAISE BRIGHTNESS {n} %',
  'disp.desc.brillo': 'BRIGHTNESS',
  'disp.desc.fijarBrillo': 'SET BRIGHTNESS {n} %',
  'disp.desc.ajustarGenerico': 'ADJUST {target} {delta}',
  'disp.desc.discordMute': 'DISCORD: MUTE MICROPHONE',
  'disp.desc.discordDeaf': 'DISCORD: DEAFEN',
  'disp.desc.discordGenerico': 'DISCORD: {accion}',
  'disp.desc.incrVar': '{nombre} {delta}',
  'disp.desc.setVar': '{nombre} = {valor}',
  'disp.desc.variableGenerica': 'VARIABLE',
  'disp.desc.script': 'RUN: {cmd}',
  'disp.desc.scriptVacio': 'RUN SCRIPT',
  'disp.desc.atajo': 'SHORTCUT {teclas}',
  'disp.desc.atajoVacio': 'SHORTCUT',
  'disp.desc.teclaIzq': 'LEFT ARROW',
  'disp.desc.teclaDer': 'RIGHT ARROW',
  'disp.desc.teclaArriba': 'UP ARROW',
  'disp.desc.teclaAbajo': 'DOWN ARROW',
  'disp.desc.paginaSig': 'NEXT PAGE',
  'disp.desc.paginaAnt': 'PREVIOUS PAGE',
  'disp.desc.paginaPrimera': 'FIRST PAGE',
  'disp.desc.paginaCycle': 'CYCLE PAGE',
  'disp.desc.paginaIr': 'GO TO PAGE',
  'disp.desc.ventanaAnt': 'PREVIOUS WINDOW',
  'disp.desc.ventanaSig': 'NEXT WINDOW',
  'disp.desc.otraVez': 'AGAIN: {desc}',
};
