import type { Dict } from './tipos';

/**
 * Fragmento del diccionario ingles: editor de boton, macros, iconos de marca y glifos 5x7.
 *
 * Se fusiona en `en.ts`. Las claves son estables (no el texto).
 */
export const EN_EDITOR: Dict = {
  'ed.title': 'CONFIGURE BUTTON',
  'ed.preview': 'PREVIEW',
  'ed.step.action': 'ACTION',
  'ed.step.config': 'CONFIGURE',
  'ed.step.style': 'STYLE',
  'ed.back': 'BACK',
  'ed.cancel': 'CANCEL',
  'ed.next': 'NEXT',
  'ed.save': 'SAVE',
  'ed.clear': 'CLEAR BUTTON',
  'ed.clearConfirm': 'CLEAR BUTTON?',
  'ed.confirmClear': 'CONFIRM',
  'ed.stepN': 'STEP {n} / {total}',
  'ed.toggleMode': 'TOGGLE MODE',
  'ed.mode.standard': '1×1 STANDARD',
  'ed.mode.split2x2': '2×2 QUADRANTS',
  'ed.mode.hint': 'Split cell into 4 independent mini-buttons',
  'ed.split.presets': '2×2 PRESETS',
  'ed.split.presetMedia': 'MEDIA',
  'ed.split.presetArrows': 'DIRECTIONS',
  'ed.split.presetShortcuts': 'SHORTCUTS',
  'ed.split.presetAudio': 'AUDIO',
  'ed.quadrant.selected': 'SELECTED QUADRANT',
  'ed.quadrant.tl': '01 · TOP-LEFT (TL)',
  'ed.quadrant.tr': '02 · TOP-RIGHT (TR)',
  'ed.quadrant.bl': '03 · BOTTOM-LEFT (BL)',
  'ed.quadrant.br': '04 · BOTTOM-RIGHT (BR)',
  'ed.split.action': 'QUADRANT ACTION',
  'ed.split.icon': '8×8 PHYSICAL GLYPH',
  'ed.split.label': 'MINI LABEL (MAX 8)',
  'ed.split.sublabel': 'SUB-LABEL',
  'ed.split.bgColor': 'BACKGROUND COLOR',
  'ed.split.fgColor': 'TEXT / ICON COLOR',
  'ed.split.noIcon': 'NO ICON',
  'ed.split.customColor': 'HEX',
  'ed.split.toggle': 'TOGGLE MODE',
  'ed.pickSensor': '— Pick a sensor —',
  'brand.search': 'Search icon...',
  'macro.scrollHint': '(+ up, − down)',
  'ed.cancelCapture': 'CANCEL',
  'brand.clearAll': 'CLEAR ALL',
  'brand.activeColor': 'ACTIVE COLOR',
  'brand.hint': '17×17 · Supports multi-colour · Animations follow the dot pattern',
  'brand.saveIcon': 'SAVE ICON',
  'glyph.fromFont': 'LOAD FROM FONT',
  'glyph.empty': 'Empty — saving will remove it from the button',
  'glyph.tools': 'TOOLS',
  'glyph.invert': 'Invert',
  'glyph.flipH': 'Flip H',
  'glyph.flipV': 'Flip V',
  'glyph.undo': 'Undo',
  'glyph.symbols': 'SYMBOLS',
  'glyph.preview': 'PREVIEW',
  'glyph.shift': 'Shift',
  'macro.recording': 'REC • press keys and click...',
  'macro.noSteps': 'No steps. Record a macro or add steps by hand.',
  'ed.killHint': 'Use the exact executable name. Equivalent to taskkill /IM name /F.',
  'ed.volumeHint': 'Sets the system master volume to the given percentage.',
  'ed.noRgbProfiles': 'No saved RGB profiles. Open the RGB screen and save one with the current state of your devices.',
  'ed.snapHint': 'With no process name, it snaps whichever window has focus when it runs.',
  'ed.radioHint': 'Every toggle in the same group turns off when this one turns on.',
  'ed.triggers': 'EXTERNAL TRIGGERS',
  'ed.thresholdHint': 'Warn paints the value amber, Crit red. Same units as the sensor.',
  'folder.empty': 'No buttons configured. Edit this button to add them.',
  'folder.esc': 'ESC TO CLOSE',
  'brand.none': 'No brand icon',
  'brand.g.all': 'All',
  'brand.g.design': 'Design & Production',
  'brand.g.streaming': 'Streaming & Content',
  'brand.g.dev': 'Programming & Dev',
  'brand.g.productivity': 'Productivity',
  'brand.g.media': 'Media & Leisure',
  'brand.g.system': 'Utilities & System',
  'brand.i.settings': 'Windows Settings',
  'brand.i.controlPanel': 'Control Panel',
  'brand.title': 'ANIMATED BRAND ICONS',
  'glyph.title': '5×7 GLYPH EDITOR',
  'ed.noSensors': '(no sensors: enable LHM and connect from the title bar)',
  'ed.noTempSensors': '(for CPU/motherboard temperatures, enable LibreHardwareMonitor in Settings > Sensors)',
  'icon.setPrimary': 'Set as primary color (#)',
  'glyph.load': 'Load "{ch}"',
  'macro.step.key': 'Key',
  'macro.step.hotkey': 'Hotkey',
  'macro.step.text': 'Text',
  'macro.step.click': 'Mouse click',
  'macro.step.move': 'Mouse move',
  'macro.step.delay': 'Delay (ms)',
  'macro.step.scroll': 'Scroll',
  'editor.stdoutToVar': 'The script output is stored in the variable and can be used as {ejemplo} in later steps.',
  'macro.fieldText': 'TEXT',
  'macro.fieldKey': 'KEY',
  'macro.textPlaceholder': 'Text to type',
  'macro.rec.start': 'RECORD',
  'macro.rec.stop': 'STOP',
  'macro.textDefault': 'Hello world',
  'macro.recEmpty': 'No keys or clicks were captured. Clicks on this window do not count: use the keyboard or click outside.',
  'editor.previewHint': 'HOVER → EDIT',
  'editor.previewHint2': 'CLICK → RUN',
  'editor.applyPreset': 'Apply preset: {nombre}',
  'ed.seq.delay': 'DELAY',
  'ed.seq.delayTitle': 'Milliseconds to wait before running this step. Empty = 150 ms.',
  'ed.seq.repeat': 'REPEAT',
  'ed.seq.repeatTitle': 'How many times this step runs in a row. Empty = once.',
  'ed.seq.always': 'ALWAYS',
  'ed.seq.onlyIfOk': 'ONLY IF OK',
  'ed.seq.onlyIfOkTitle': 'Run this step only if the previous one succeeded.',
  'ed.seq.onlyIfFailed': 'IF FAILED',
  'ed.seq.onlyIfFailedTitle': 'Run this step only if the previous step failed.',
  'ed.seq.continueOnError': 'CONTINUE ON ERROR',
  'ed.seq.continueOnErrorTitle': 'Do not abort the sequence if this step fails.',
  'ed.seq.moveUp': 'Move step up',
  'ed.seq.moveDown': 'Move step down',
  'ed.actionSequence': 'ACTION SEQUENCE (OPTIONAL)',
  'ed.snapHint2': 'Works best with global hotkeys, without going through VirtualDeck.',
  'ed.pinned': 'PIN TO ALL PAGES',
  'ed.pinnedHint': 'Keeps this position across all pages on the deck.',
  'ed.discord.action': 'DISCORD ACTION',
  'ed.discord.toggleMute': 'Toggle mute (Mute / Unmute)',
  'ed.discord.toggleDeaf': 'Toggle deafen (Deafen / Undeafen)',
  'ed.discord.mute': 'Mute microphone (Mute)',
  'ed.discord.unmute': 'Unmute microphone (Unmute)',
  'ed.discord.deaf': 'Deafen',
  'ed.discord.undeaf': 'Undeafen',
  'ed.discord.help': 'Automatically connects to the Discord desktop client via local Named Pipe (\\.\\pipe\\discord-ipc-0..9) with 0ms latency.',
  'ed.spotify.action': 'SPOTIFY ACTION',
  'ed.spotify.playUri': 'Play Playlist / Track / Album',
  'ed.spotify.transfer': 'Transfer playback to device',
  'ed.spotify.shuffle': 'Toggle shuffle mode',
  'ed.spotify.repeat': 'Toggle repeat mode',
  'ed.spotify.uri': 'SPOTIFY URI OR WEB LINK',
  'ed.spotify.help': 'Accepts Spotify URIs (spotify:playlist:...) or open.spotify.com links. Launched instantly in the desktop app.',
  'ed.spotify.deviceId': 'SPOTIFY DEVICE ID',
  'ed.spotify.devicePlaceholder': 'Device ID returned by the API',
  'ed.spotify.token': 'WEB API ACCESS TOKEN (OPTIONAL)',
  'ed.spotify.tokenPlaceholder': 'Spotify Web API Bearer token',
  'ed.spotify.detectDevices': 'FIND DEVICES',
  'ed.spotify.noDevices': 'No active devices found',
  'ed.discord.status': 'DISCORD STATUS',
  'ed.discord.connected': 'CONNECTED',
  'ed.discord.notRunning': 'DISCORD NOT DETECTED',
};
