import type { Dict } from './tipos';

/**
 * Fragmento del diccionario ingles: editor de boton, macros, iconos de marca y glifos 5x7.
 *
 * Se fusiona en `en.ts`. Las claves son estables (no el texto).
 */
export const EN_EDITOR: Dict = {
  'ed.title': 'CONFIGURE BUTTON',
  'ed.preview': 'PREVIEW',
  'ed.step.action': 'ACTION',
  'ed.step.config': 'CONFIGURE',
  'ed.step.style': 'STYLE',
  'ed.sec.presets': 'PRESETS',
  'ed.sec.action': 'ACTION',
  'ed.sec.appearance': 'APPEARANCE',
  'ed.sec.behavior': 'BEHAVIOR',
  'ed.sec.advanced': 'ADVANCED',
  'cat.DOCK': 'DOCK',
  'ed.dockPresets': 'DOCK PRESETS',
  'ed.searchPresets': 'Search preset...',
  'ed.noPresets': 'No results',
  'ed.addExtraAction': 'ADD ADDITIONAL ACTION',
  'ed.actionSequenceHint': 'Allows chaining up to 8 actions that execute in sequence on button press.',
  'ed.back': 'BACK',
  'ed.cancel': 'CANCEL',
  'ed.next': 'NEXT',
  'ed.save': 'SAVE',
  'ed.clear': 'CLEAR BUTTON',
  'ed.clearConfirm': 'CLEAR BUTTON?',
  'ed.confirmClear': 'CONFIRM',
  'ed.stepN': 'STEP {n} / {total}',
  'ed.toggleMode': 'TOGGLE MODE',
  'ed.mode.standard': '1×1 STANDARD',
  'ed.mode.split2x2': '2×2 QUADRANTS',
  'ed.mode.hint': 'Split cell into 4 independent mini-buttons',
  'ed.split.presets': '2×2 PRESETS',
  'ed.split.presetMedia': 'MEDIA',
  'ed.split.presetArrows': 'DIRECTIONS',
  'ed.split.presetShortcuts': 'SHORTCUTS',
  'ed.split.presetAudio': 'AUDIO',
  'ed.quadrant.selected': 'SELECTED QUADRANT',
  'ed.quadrant.tl': '01 · TOP-LEFT (TL)',
  'ed.quadrant.tr': '02 · TOP-RIGHT (TR)',
  'ed.quadrant.bl': '03 · BOTTOM-LEFT (BL)',
  'ed.quadrant.br': '04 · BOTTOM-RIGHT (BR)',
  'ed.split.action': 'QUADRANT ACTION',
  'ed.split.icon': '8×8 PHYSICAL GLYPH',
  'ed.split.label': 'MINI LABEL (MAX 8)',
  'ed.split.sublabel': 'SUB-LABEL',
  'ed.split.bgColor': 'BACKGROUND COLOR',
  'ed.split.fgColor': 'TEXT / ICON COLOR',
  'ed.split.noIcon': 'NO ICON',
  'ed.split.toggle': 'TOGGLE MODE',
  'ed.pickSensor': '— Pick a sensor —',
  'brand.search': 'Search icon...',
  'brand.loading': 'Loading icons...',
  'macro.scrollHint': '(+ up, − down)',
  'ed.cancelCapture': 'CANCEL',
  'brand.clearAll': 'CLEAR ALL',
  'brand.activeColor': 'ACTIVE COLOR',
  'brand.hint': '17×17 · Supports multi-colour · Animations follow the dot pattern',
  'brand.saveIcon': 'SAVE ICON',
  'glyph.fromFont': 'LOAD FROM FONT',
  'glyph.empty': 'Empty — saving will remove it from the button',
  'glyph.invert': 'Invert',
  'glyph.flipH': 'Flip H',
  'glyph.flipV': 'Flip V',
  'glyph.undo': 'Undo',
  'glyph.symbols': 'SYMBOLS',
  'glyph.preview': 'PREVIEW',
  'macro.recording': 'REC • press keys and click...',
  'macro.noSteps': 'No steps. Record a macro or add steps by hand.',
  'ed.killHint': 'Use the exact executable name. Equivalent to taskkill /IM name /F.',
  'ed.volumeHint': 'Sets the system master volume to the given percentage.',
  'ed.noRgbProfiles': 'No saved RGB profiles. Open the RGB screen and save one with the current state of your devices.',
  'ed.snapHint': 'With no process name, it snaps whichever window has focus when it runs.',
  'ed.radioHint': 'Every toggle in the same group turns off when this one turns on.',
  'ed.triggers': 'EXTERNAL TRIGGERS',
  'ed.thresholdHint': 'Warn paints the value amber, Crit red. Same units as the sensor.',
  'folder.empty': 'No buttons configured. Edit this button to add them.',
  'folder.esc': 'ESC TO CLOSE',
  'brand.none': 'No brand icon',
  'brand.g.all': 'All',
  'brand.g.design': 'Design & Production',
  'brand.g.streaming': 'Streaming & Content',
  'brand.g.dev': 'Programming & Dev',
  'brand.g.productivity': 'Productivity',
  'brand.g.media': 'Media & Leisure',
  'brand.g.system': 'Utilities & System',
  'brand.i.settings': 'Windows Settings',
  'brand.i.controlPanel': 'Control Panel',
  'brand.title': 'ANIMATED BRAND ICONS',
  'glyph.title': '5×7 GLYPH EDITOR',
  'ed.noSensors': '(no sensors: enable LHM and connect from the title bar)',
  'ed.noTempSensors': '(for CPU/motherboard temperatures, enable LibreHardwareMonitor in Settings > Sensors)',
  'icon.setPrimary': 'Set as primary color (#)',
  'glyph.load': 'Load "{ch}"',
  'macro.step.key': 'Key',
  'macro.step.hotkey': 'Hotkey',
  'macro.step.text': 'Text',
  'macro.step.click': 'Mouse click',
  'macro.step.move': 'Mouse move',
  'macro.step.delay': 'Delay (ms)',
  'macro.step.scroll': 'Scroll',
  'editor.stdoutToVar': 'The script output is stored in the variable and can be used as {ejemplo} in later steps.',
  'macro.fieldText': 'TEXT',
  'macro.fieldKey': 'KEY',
  'macro.textPlaceholder': 'Text to type',
  'macro.rec.start': 'RECORD',
  'macro.rec.stop': 'STOP',
  'macro.textDefault': 'Hello world',
  'macro.recEmpty': 'No keys or clicks were captured. Clicks on this window do not count: use the keyboard or click outside.',
  'editor.previewHint': 'HOVER → EDIT',
  'editor.previewHint2': 'CLICK → RUN',
  'editor.applyPreset': 'Apply preset: {nombre}',
  'ed.seq.delay': 'DELAY',
  'ed.seq.delayTitle': 'Milliseconds to wait before running this step. Empty = 150 ms.',
  'ed.seq.repeat': 'REPEAT',
  'ed.seq.repeatTitle': 'How many times this step runs in a row. Empty = once.',
  'ed.seq.always': 'ALWAYS',
  'ed.seq.onlyIfOk': 'ONLY IF OK',
  'ed.seq.onlyIfOkTitle': 'Run this step only if the previous one succeeded.',
  'ed.seq.onlyIfFailed': 'IF FAILED',
  'ed.seq.onlyIfFailedTitle': 'Run this step only if the previous step failed.',
  'ed.seq.continueOnError': 'CONTINUE ON ERROR',
  'ed.seq.continueOnErrorTitle': 'Do not abort the sequence if this step fails.',
  'ed.seq.moveUp': 'Move step up',
  'ed.seq.moveDown': 'Move step down',
  'ed.actionSequence': 'ACTION SEQUENCE (OPTIONAL)',
  'ed.snapHint2': 'Works best with global hotkeys, without going through VirtualDeck.',
  'ed.discord.action': 'DISCORD ACTION',
  'ed.discord.toggleMute': 'Toggle mute (Mute / Unmute)',
  'ed.discord.toggleDeaf': 'Toggle deafen (Deafen / Undeafen)',
  'ed.discord.mute': 'Mute microphone (Mute)',
  'ed.discord.unmute': 'Unmute microphone (Unmute)',
  'ed.discord.deaf': 'Deafen',
  'ed.discord.undeaf': 'Undeafen',
  'ed.discord.help': 'Automatically connects to the Discord desktop client via local Named Pipe (\\.\\pipe\\discord-ipc-0..9) with 0ms latency.',
  'ed.spotify.action': 'SPOTIFY ACTION',
  'ed.spotify.playUri': 'Play Playlist / Track / Album',
  'ed.spotify.transfer': 'Transfer playback to device',
  'ed.spotify.shuffle': 'Toggle shuffle mode',
  'ed.spotify.repeat': 'Toggle repeat mode',
  'ed.spotify.uri': 'SPOTIFY URI OR WEB LINK',
  'ed.spotify.help': 'Accepts Spotify URIs (spotify:playlist:...) or open.spotify.com links. Launched instantly in the desktop app.',
  'ed.spotify.deviceId': 'SPOTIFY DEVICE ID',
  'ed.spotify.devicePlaceholder': 'Device ID returned by the API',
  'ed.spotify.token': 'WEB API ACCESS TOKEN (OPTIONAL)',
  'ed.spotify.tokenPlaceholder': 'Spotify Web API Bearer token',
  'ed.spotify.detectDevices': 'FIND DEVICES',
  'ed.spotify.noDevices': 'No active devices found',
  'ed.discord.connected': 'CONNECTED',
  'ed.discord.notRunning': 'DISCORD NOT DETECTED',
  // — Per-app volume (roadmap 63) —
  'ed.appVolume.mode': 'MODE',
  'ed.appVolume.adjust': 'Step up / down',
  'ed.appVolume.set': 'Set level',
  'ed.appVolume.mute': 'Mute',
  'ed.appVolume.app': 'APPLICATION',
  'ed.appVolume.active': 'Active app (whichever is in front)',
  'ed.appVolume.specific': 'A specific one',
  'ed.appVolume.sounding': 'PLAYING SOUND NOW',
  'ed.appVolume.noSessions': 'No app is playing sound right now. Open something audible and reload.',
  'ed.appVolume.muteHint': 'Toggles the app mute: if anything plays, it mutes; if all is muted, it unmutes.',
  // — Presets de controles físicos (dock) —
  'disp.presets.titulo': 'PRESET CONTROLS',
  'disp.presets.aplicar': 'Apply preset',
  'disp.presets.sinPresets': 'No presets for this control',
  'preset.dock.knob.volume': 'Master Volume',
  'preset.dock.knob.brightness': 'Screen Brightness',
  'preset.dock.knob.media': 'Media Player',
  'preset.dock.knob.zoom': 'Universal Zoom',
  'preset.dock.knob.tabs': 'Browser Tabs',
  'preset.dock.knob.history': 'Undo & Redo',
  'preset.dock.knob.jog': 'Timeline Jog',
  'preset.dock.knob.brush': 'Brush Size',
  'preset.dock.knob.desktops': 'Virtual Desktops',
  'preset.dock.knob.counter': 'Stream Counter',
  'preset.dock.knob.pages': 'Dock pages',
  'preset.dock.knob.windows': 'Open windows',
  'preset.dock.knob.appVolume': 'App Volume',
  'preset.dock.knob.spotifyVolume': 'Spotify Volume',
  'preset.dock.knob.discordVolume': 'Discord Volume',
  'preset.dock.knob.multi': 'Multi-mode knob',
  'preset.dock.button.nextPage': 'Next page',
  'preset.dock.button.prevPage': 'Previous page',
  'preset.dock.button.discordMute': 'Discord Mute',
  'preset.dock.button.discordDeaf': 'Discord Deafen',
  'preset.dock.button.systemMute': 'System Mute',
  'preset.dock.button.screenSnip': 'Screen Snip',
  'preset.dock.button.showDesktop': 'Show Desktop',
  'preset.dock.button.lockPc': 'Lock PC',
  'preset.dock.button.clipboardHistory': 'Clipboard History',
  'preset.dock.button.multitask': 'Multitask',
  'preset.dock.button.cyclePage': 'Cycle page',
  'preset.dock.button.prevWindow': 'Previous window',
  'preset.dock.button.nextWindow': 'Next window',
  'preset.dock.strip.media': 'Media Navigation',
  'preset.dock.strip.brightness': 'Brightness Control',
  'preset.dock.strip.tabs': 'Browser Tabs',
  'plantilla.app.web': 'Web browser',
  'plantilla.app.vscode': 'VS Code',
  'plantilla.app.spotify': 'Spotify',
  'plantilla.app.discord': 'Discord',
  'plantilla.app.photoshop': 'Photoshop',
  'plantilla.app.premiere': 'Premiere Pro',
  'plantilla.app.explorer': 'File Explorer',
  'undo.applyPreset': 'apply preset "{nombre}"',
};
