/**
 * Diccionario espanol.
 *
 * Vive fuera de `i18n.tsx` porque el archivo llegaba a 1135 lineas y crecia
 * con cada texto nuevo: los tres diccionarios son datos, y mezclados con el
 * proveedor hacian ilegible lo poco que ahi es logica.
 *
 * Las claves son estables (no el texto). El orden importa solo para leerlo.
 */
import type { Dict } from './tipos';

export const ES: Dict = {
  // — Chrome / settings (TitleBar) —
  'settings.theme': 'TEMA',
  'settings.theme.dark': 'OSCURO',
  'settings.theme.light': 'CLARO',
  'settings.theme.system': 'SISTEMA',
  'settings.language': 'IDIOMA',
  'settings.language.system': 'SISTEMA',
  'settings.autostart': 'INICIAR CON WINDOWS',
  'settings.alwaysOnTop': 'SIEMPRE VISIBLE',
  'settings.uiscale': 'ESCALA DE INTERFAZ',
  'settings.tiles': 'FORMA DE BOTONES',
  'settings.tiles.square': 'CUADRADOS',
  'settings.tiles.fill': 'RELLENAR',
  // — Acciones de página / barra —
  'main.search.placeholder': 'Etiqueta, app, URL, atajo...',
  'main.search.title': 'BUSCAR BOTÓN',
  'main.search.empty': 'No hay botones configurados',
  'main.search.nomatch': 'Sin coincidencias',
  'main.search.nav': '↑↓ NAVEGAR',
  'main.search.edit': '↵ EDITAR',
  'main.search.exit': 'ESC SALIR',
  // — Update banner —
  'update.ready': 'Actualización {version} lista.',
  'update.restart': 'REINICIAR',
  'update.later': 'DESPUÉS',
  // — Onboarding —
  'onb.step': 'PASO {n} / 0{total}',
  'onb.skip': 'Saltar',
  'onb.back': 'Atrás',
  'onb.next': 'Siguiente',
  'onb.start': 'Empezar',
  'onb.1.title': 'VIRTUALDECK',
  'onb.1.body': 'Tu Stream Deck por software. Una grilla de botones que disparan acciones: abrir apps, webs y carpetas, cambiar el audio, controlar la música, ejecutar atajos, macros y más.',
  'onb.1.hint': 'Todo se guarda solo. No hay nube ni cuentas: es 100% local.',
  'onb.2.title': 'TUS BOTONES',
  'onb.2.body': 'Hacé clic en cualquier celda vacía para configurarla. Elegí una etiqueta, un ícono y la acción que querés que ejecute. Un clic normal la dispara; el menú contextual (clic derecho) la edita, duplica o limpia.',
  'onb.2.hint': 'Ctrl+clic selecciona varios botones para operaciones en lote.',
  'onb.3.title': 'PÁGINAS Y GRILLA',
  'onb.3.body': 'Organizá tus botones en varias páginas (pestañas arriba). Cambiá entre ellas con las teclas 1-9 o deslizando. Cada página puede tener su propio tamaño de grilla.',
  'onb.3.hint': 'Arrastrá un botón sobre la pestaña de otra página para moverlo.',
  'onb.4.title': 'WIDGETS Y PANTALLA COMPLETA',
  'onb.4.body': 'Un botón puede mostrar reloj, clima, sensores del PC, una variable o la música que suena ahora. Entrá en pantalla completa para usar VirtualDeck como panel dedicado en una tablet o monitor secundario.',
  'onb.4.hint': 'El widget de música detecta Spotify, YouTube, navegadores y más.',
  'onb.5.title': 'AYUDA SIEMPRE A MANO',
  'onb.5.body': 'Pulsá Ctrl+K para buscar cualquier botón al instante. En ⚙ → Ayuda y Acerca de encontrás la documentación, el reporte de errores y este tutorial por si querés repetirlo.',
  'onb.5.hint': '¿Listo? Creá tu primer botón.',
  // — Hints contextuales —
  'hint.firstButton': 'Hacé clic en una celda vacía para crear tu primer botón.',
  'hint.settings': 'Tema, idioma, escala y más están acá en Configuración.',
  'hint.search': 'Tip: Ctrl+K busca cualquier botón al instante.',
  'hint.dismiss': 'Entendido',
  // — Ayuda y Acerca de —
  'help.title': 'AYUDA Y ACERCA DE',
  'help.docs': '📖 DOCUMENTACIÓN',
  'help.report': '🐞 REPORTAR ERROR',
  'help.check': '⟳ BUSCAR UPDATE',
  'help.checking': 'BUSCANDO…',
  'help.support': '♥ APOYAR',
  'help.donateIntro': 'VirtualDeck es gratis. Si te sirve, podés apoyar su desarrollo:',
  'help.openLog': 'ABRIR REGISTRO',
  'help.exportLog': 'EXPORTAR REGISTRO',
  'help.replay': '🎓 REPETIR TUTORIAL',
  'help.credits': 'CRÉDITOS Y LICENCIAS',
  'help.bundled': ' (incluido)',
  'help.upd.ready': 'Actualización {version} lista — reiniciá para aplicar.',
  'help.upd.downloading': 'Descargando actualización {version}…',
  'help.upd.error': 'No se pudo buscar actualizaciones.',
  'help.upd.disabled': 'Auto-update no disponible en este build (modo desarrollo).',
  'help.upd.checkError': 'Error al buscar actualizaciones.',
  'help.upd.checking': 'Buscando actualizaciones…',
  // — Tooltips de la barra superior —
  'tip.export': 'Exportar configuración',
  'tip.import': 'Importar configuración',
  'tip.bar': 'Columna de tiles flotante sobre el escritorio',
  'tip.rgb': 'Gestor RGB',
  'tip.settings': 'Configuración',
  'tip.fullscreen': 'Modo pantalla completa',
  'tip.minimize': 'Minimizar',
  'tip.close': 'Cerrar (minimiza a bandeja)',
  // — Pantalla de fondos (WallpaperB) —
  'wp.back': '← VOLVER',
  'wp.preview': 'VISTA PREVIA',
  'wp.select': 'SELECCIONAR FONDO',
  'wp.applied': '✓ APLICADO',
  'wp.apply': 'APLICAR →',
  'wp.selected': '● SELECCIONADO',
  'wp.autosave': 'Los cambios se guardan automáticamente al presionar Aplicar.',
  'wp.name.solid': 'Sólido',
  'wp.name.gradient': 'Gradiente Azul',
  'wp.name.dotgrid': 'Cuadrícula Dot',
  'wp.name.scanlines': 'Scanlines',
  'wp.name.crt': 'CRT',
  'wp.name.mesh': 'Mesh técnico',
  'wp.name.photo': 'Neón',
  'wp.name.grid-blue': 'Grid Azul',
  // — Editor de botón (chrome: pasos y navegación) —
  'ed.title': 'CONFIGURAR BOTÓN',
  'ed.preview': 'VISTA PREVIA',
  'ed.step.action': 'ACCIÓN',
  'ed.step.config': 'CONFIGURAR',
  'ed.step.style': 'ESTILO',
  'ed.back': '← ATRÁS',
  'ed.cancel': 'CANCELAR',
  'ed.next': 'SIGUIENTE →',
  'ed.save': 'GUARDAR ✓',
  'ed.stepN': 'PASO {n} / {total}',
  'ed.toggleMode': 'MODO TOGGLE',
  // — Tipos de acción (selector del editor) —
  'act.none.label': 'Ninguno', 'act.none.desc': 'Sin acción asignada',
  'act.app.label': 'Abrir App', 'act.app.desc': 'Ejecuta una aplicación',
  'act.web.label': 'Página Web', 'act.web.desc': 'Abre una URL en el navegador',
  'act.shortcut.label': 'Acceso Dir.', 'act.shortcut.desc': 'Abre un archivo o carpeta',
  'act.script.label': 'Script', 'act.script.desc': 'Ejecuta PowerShell o CMD',
  'act.audio-device.label': 'Audio', 'act.audio-device.desc': 'Cambia dispositivo de salida',
  'act.hotkey.label': 'Atajo', 'act.hotkey.desc': 'Envía combinación de teclas',
  'act.clipboard.label': 'Portapapeles', 'act.clipboard.desc': 'Copia texto al portapapeles',
  'act.type-text.label': 'Escribir', 'act.type-text.desc': 'Escribe texto automáticamente',
  'act.kill-process.label': 'Cerrar App', 'act.kill-process.desc': 'Termina un proceso por nombre',
  'act.volume-set.label': 'Vol. Exacto', 'act.volume-set.desc': 'Establece volumen a un % exacto',
  'act.folder.label': 'Carpeta', 'act.folder.desc': 'Abre un sub-deck de botones',
  'act.media-play-pause.label': 'Play/Pausa', 'act.media-play-pause.desc': 'Reproducir / Pausar',
  'act.media-next.label': 'Siguiente', 'act.media-next.desc': 'Siguiente pista',
  'act.media-prev.label': 'Anterior', 'act.media-prev.desc': 'Pista anterior',
  'act.volume-up.label': 'Vol. ＋', 'act.volume-up.desc': 'Sube el volumen',
  'act.volume-down.label': 'Vol. −', 'act.volume-down.desc': 'Baja el volumen',
  'act.mute.label': 'Silenciar', 'act.mute.desc': 'Silencia / activa sonido',
  'act.brightness.label': 'Brillo', 'act.brightness.desc': 'Controla brillo del monitor',
  'act.notify.label': 'Notificación', 'act.notify.desc': 'Muestra una notificación de Windows',
  'act.set-var.label': 'Var: Asignar', 'act.set-var.desc': 'Asigna valor a una variable global',
  'act.incr-var.label': 'Var: Sumar', 'act.incr-var.desc': 'Incrementa o decrementa una variable numérica',
  'act.webhook.label': 'Webhook', 'act.webhook.desc': 'POST/GET a una URL con body y headers',
  'act.tts.label': 'Texto-a-voz', 'act.tts.desc': 'Lee un texto en voz alta',
  'act.region-capture.label': 'Captura', 'act.region-capture.desc': 'Abre la captura de región de Windows',
  'act.rgb-color.label': 'RGB Color', 'act.rgb-color.desc': 'Pinta un color sólido en un dispositivo RGB',
  'act.rgb-mode.label': 'RGB Modo', 'act.rgb-mode.desc': 'Cambia el modo/efecto RGB (Direct, Breathing, etc.)',
  'act.rgb-profile.label': 'RGB Perfil', 'act.rgb-profile.desc': 'Aplica un perfil RGB guardado',
  'act.window-snap.label': 'Snap Ventana', 'act.window-snap.desc': 'Mueve y redimensiona una ventana a un cuadrante',
  'act.branch.label': 'Si / Si no', 'act.branch.desc': 'Ejecuta acción A o B según el valor de una variable',
  'act.countdown.label': 'Temporizador', 'act.countdown.desc': 'Espera N ms y luego ejecuta una acción',
  'act.media-shuffle.label': 'Shuffle', 'act.media-shuffle.desc': 'Alterna shuffle en el reproductor activo (SMTC)',
  'act.media-repeat.label': 'Repetir', 'act.media-repeat.desc': 'Cicla el modo de repetición (ninguno → lista → pista)',
  'act.macro.label': 'Macro', 'act.macro.desc': 'Secuencia de teclas y clics de ratón grabada o configurada',

  // ── Gestor RGB ──
  'rgb.connFailed': 'Conexión falló: {err}',
  'rgb.connFailedNoServer': 'Conexión falló (¿está activo el servidor de OpenRGB?)',
  'rgb.profilePartial': 'Algunos dispositivos no aceptaron el perfil.',
  'rgb.resizeFailed': 'No se pudo redimensionar la zona.',
  'rgb.disconnect': 'DESCONECTAR',
  'rgb.connect': 'CONECTAR',
  'rgb.rescan': 'Reescanear dispositivos',
  'rgb.notConnected': 'NO CONECTADO',
  'rgb.setPath': '· Configura la ruta de OpenRGB.exe en el flyout de ajustes (icono ⚙ en la pantalla principal → sección RGB).',
  'rgb.serverHint': '· Asegúrate de que el servidor SDK esté activo (puerto {port}). VirtualDeck arranca OpenRGB en modo --server, sin interfaz, así no aparece el diálogo de tamaño de zonas.',
  'rgb.lastError': 'Último error: {err}',
  'rgb.devices': 'DISPOSITIVOS',
  'rgb.noDevices': 'Ningún dispositivo detectado.',
  'rgb.connectToSee': 'Conecta para ver dispositivos.',
  'rgb.quickActions': 'ACCIONES RÁPIDAS',
  'rgb.allOff': 'APAGAR TODO',
  'rgb.allWhite': 'BLANCO TOTAL',
  'rgb.accentColor': 'COLOR ACENTO',
  'rgb.profiles': 'PERFILES RGB',
  'rgb.noProfiles': 'Sin perfiles aún.',
  'rgb.apply': 'APLICAR',
  'rgb.save': 'GUARDAR',
  'rgb.newProfile': 'Nuevo perfil...',
  'rgb.connected': 'CONECTADO · {n} DISP',
  'rgb.serverUp': 'SERVIDOR ACTIVO',
  'rgb.disconnected': 'DESCONECTADO',
  'rgb.color': 'COLOR',
  'rgb.mode': 'MODO',
  'rgb.speed': 'VELOCIDAD · {n}%',
  'rgb.zones': 'ZONAS',
  'rgb.zoneLeds': '{n} LEDS',
  'rgb.zoneResizable': ' · {min}-{max} REDIM.',
  'rgb.paintLeds': 'PINTAR LEDs INDIVIDUALES',
  'rgb.hide': 'OCULTAR',
  'rgb.show': 'MOSTRAR',
  'rgb.noLeds': 'No hay LEDs reportados para este dispositivo.',
  'rgb.notPerLed': '⚠ El modo actual ({mode}) no es per-LED. Cambia a Direct o Custom para que los cambios sean visibles.',
  'rgb.ledsHint': '{n} LEDs · Clic = pintar con el color seleccionado',
  'rgb.calibrator': 'CALIBRADOR DE ZONAS ARGB',
  'rgb.calibratorHelp': 'Para cada zona redimensionable: pulsa IDENTIFICAR para que un LED se encienda en blanco recorriendo toda la cadena. Cuenta cuántos LEDs viste y guarda ese número. Esto sustituye al diálogo de OpenRGB y persiste en la configuración local.',
  'rgb.noResizable': 'No hay zonas redimensionables detectadas.',
  'rgb.range': 'RANGO {min}–{max} · ACTUAL {cur}',
  'rgb.saved': ' · GUARDADO {n}',
  'rgb.suggestion': '◆ Sugerencia: {note}',
  'rgb.identify': 'IDENTIFICAR',
  'rgb.hint.unifan': 'Lian Li UNI Fan SL (16 LEDs por ventilador)',
  'rgb.hint.strimer24': 'Strimer Plus 24-pin',
  'rgb.hint.strimer8': 'Strimer Plus 8-pin',
  'rgb.hint.argb': 'Cabezal ARGB genérico (estimado)',
  // ── Barra flotante ──
  'bar.short': 'BARRA',
  'bar.close': 'Cerrar la barra flotante',
  'weather.loading': 'Cargando clima...',
  'panel.noMedia': 'Sin reproducción activa',
  'ed.pickSensor': '— Selecciona un sensor —',
  'brand.search': 'Buscar icono...',
  'cell.editShort': 'Editar',
  'macro.scrollHint': '(+ arriba, − abajo)',
  'ed.cancelCapture': '✕ cancelar',
  'bulk.move': '↗ MOVER',
  'bulk.clear': '✕ LIMPIAR',
  'panel.openRgb': 'Abrir Gestor RGB',
  'panel.clearLog': 'Limpiar log',
  'ui.back': '← VOLVER',
  'brand.clearAll': 'LIMPIAR TODO',
  'brand.activeColor': 'COLOR ACTIVO',
  'brand.hint': '17×17 · Soporta multi-color · Animaciones siguen el patrón de puntos',
  'brand.saveIcon': 'GUARDAR ICONO ✓',
  'glyph.fromFont': 'CARGAR DESDE TIPOGRAFÍA',
  'glyph.empty': 'Vacío — guardar lo eliminará del botón',
  'ui.saveShort': 'GUARDAR',
  'set.noProfiles': 'Sin perfiles guardados.',
  'macro.recording': 'REC • presioná teclas y hacé clics...',
  'macro.noSteps': 'Sin pasos. Grabá una macro o añadí pasos manualmente.',
  'ed.killHint': 'Usa el nombre exacto del ejecutable. Equivale a taskkill /IM nombre /F.',
  'ed.volumeHint': 'Establece el volumen maestro del sistema al porcentaje indicado.',
  'ed.noRgbProfiles': 'No hay perfiles RGB guardados. Abre la pantalla RGB y guarda un perfil con el estado actual de tus dispositivos.',
  'ed.snapHint': 'Sin nombre de proceso, snapea la ventana en foco al momento de ejecutar.',
  'ed.radioHint': 'Todos los toggles con el mismo grupo se desactivan cuando se activa este.',
  'ed.triggers': 'DISPARADORES EXTERNOS',
  'ed.thresholdHint': 'Warn pinta el valor en amarillo, Crit en rojo. Mismas unidades que el sensor.',
  'folder.empty': 'Sin botones configurados. Edita este botón para añadirlos.',
  'folder.esc': 'ESC PARA CERRAR',
  'rgb.pickDevice': 'Selecciona un dispositivo a la izquierda.',
  // ── Palabras sueltas de interfaz ──
  'ui.none': 'NINGUNO',
  'ui.cancel': 'CANCELAR',
  'ui.clear': 'LIMPIAR',
  'ui.fill': 'RELLENAR',
  'ui.save': 'GUARDAR ✓',
  'ui.port': 'PUERTO',
  'ui.wallpaper': 'FONDO',
  'ui.import': 'IMPORTAR',
  'ui.load': 'CARGAR',
  'ui.repeat': 'REPETIR',
  'ui.times': 'VECES',
  'ui.mouseL': 'Izq',
  'ui.mouseR': 'Der',
  'ui.mouseM': 'Med',
  'ui.units': 'UNIDADES',
  'ui.pause': 'PAUSA',
  'full.title': 'VIRTUALDECK · MODO PANTALLA COMPLETA',
  'ui.columns': 'COLUMNAS',
  'ui.rows': 'FILAS',
  'ui.moveTo': 'MOVER A...',
  // ── Ajustes, paginas y menus ──
  'undo.duplicate': 'duplicar botón',
  'undo.clear': 'limpiar botón',
  'undo.addPage': 'agregar página',
  'undo.delPage': 'eliminar página',
  'undo.movePage': 'reordenar páginas',
  'undo.importPage': 'importar página',
  'cell.edit': 'Editar botón',
  'cell.duplicate': 'Duplicar',
  'cell.clear': 'Limpiar botón',
  'set.accent': 'COLOR DE ACENTO',
  'set.scale': 'ESCALA DE INTERFAZ',
  'set.tiles': 'FORMA DE LAS CELDAS',
  'set.chime': 'TIMBRE',
  'set.importUrl': 'IMPORTAR DESDE URL',
  'set.profiles': 'PERFILES',
  'set.sound': 'SONIDO AL PRESIONAR',
  'set.profileName': 'Nombre del perfil...',
  'set.rgb': 'RGB (OPENRGB)',
  'set.rgbPath': 'RUTA OPENRGB.EXE',
  'set.enabled': 'HABILITADO',
  'set.rgbSpawn': 'LANZAR OPENRGB AL ARRANCAR',
  'set.rgbAuto': 'AUTOCONECTAR',
  'set.sensors': 'SENSORES (LIBRE HARDWARE MONITOR)',
  'set.lhmPath': 'RUTA LHM (vacío = bundled)',
  'set.categories': 'CATEGORÍAS VISIBLES',
  'set.sensorWidget': 'MOSTRAR WIDGET DE SENSORES',
  'set.lhmStart': 'INICIAR LHM CON VIRTUALDECK',
  'set.lhmAdmin': 'INICIAR LHM COMO ADMINISTRADOR (UAC)',
  'set.urlAcl': 'Registra una reserva URL ACL en Windows (1 sola UAC). Después LHM puede correr sin admin.',
  'page.noRoom': 'No hay hueco libre en "{pagina}".',
  'page.tip': 'Clic · Doble clic para renombrar · Arrastrar para reordenar · Clic derecho para opciones',
  'page.add': 'Agregar página',
  'page.export': 'Exportar página actual',
  'page.import': 'Importar página desde archivo',
  'page.rename': 'Renombrar',
  'page.delete': 'Eliminar página',
  'media.diagnose': 'Diagnosticar widget de música',
  'panel.weather': 'CLIMA',
  'panel.sensors': 'SENSORES',
  'panel.log': 'LOG',
  'panel.playing': 'REPRODUCIENDO',
  'full.clock': 'HORA LOCAL',
  'full.page': 'PÁGINA',
  'full.noMedia': 'SIN REPRODUCCIÓN',
  'brand.none': 'Sin icono de marca',
  'brand.title': 'ICONOS DE MARCA ANIMADOS',
  'weather.none': 'Sin datos de clima',
  'glyph.title': 'EDITOR DE GLIFO 5×7',
  'rgb.calibPending': '⚠ CALIBRACIÓN PENDIENTE',
  'ed.noSensors': '(sin sensores: habilita LHM y conecta en TitleBar)',
  // ── Errores y etiquetas de acciones ──
  'act.err.sinManejador': 'La accion "{tipo}" no esta implementada.',
  'act.err.noAppPath': 'Falta la ruta del programa.',
  'act.err.launch': 'No se pudo iniciar: {que}. Verifica la ruta.',
  'act.err.noUrl': 'Falta la URL.',
  'act.err.openUrl': 'No se pudo abrir: {url}',
  'act.err.noShortcut': 'Falta el acceso directo.',
  'act.err.shortcut': 'No se pudo abrir el acceso directo.',
  'act.err.noDevice': 'Falta el dispositivo de audio.',
  'act.err.deviceNotFound': 'Dispositivo "{name}" no encontrado. Verifica el nombre en Configuración → Sonido.',
  'act.err.switchAudio': 'No se pudo cambiar el audio a "{name}".',
  'act.err.noHotkey': 'Falta la combinación de teclas.',
  'act.err.hotkey': 'No se pudo enviar el atajo {hotkey}.',
  'act.err.noBrightness': 'Falta el nivel de brillo.',
  'act.err.brightness': 'No se pudo ajustar el brillo (¿monitor sin soporte WMI?).',
  'act.err.noClipText': 'Falta el texto a copiar.',
  'act.err.clipboard': 'No se pudo copiar al portapapeles.',
  'act.err.noTypeText': 'Falta el texto a escribir.',
  'act.err.type': 'No se pudo escribir el texto.',
  'act.err.noProcess': 'Falta el nombre del proceso.',
  'act.err.kill': 'No se pudo cerrar "{name}". ¿Está activo?',
  'act.err.noVolume': 'Falta el nivel de volumen.',
  'act.err.volume': 'No se pudo ajustar el volumen.',
  'act.err.notify': 'No se pudo mostrar la notificación.',
  'act.err.media': 'No se pudo enviar el control de media ({cmd}).',
  'act.err.shuffle': 'No se pudo alternar shuffle (¿hay un reproductor activo?).',
  'act.err.repeat': 'No se pudo cambiar el modo de repetición.',
  'act.err.macroEmpty': 'La macro no tiene pasos.',
  'act.err.mediaKey': 'No se pudo enviar la tecla multimedia ({tipo}).',
  'act.err.noVar': 'Falta nombre de variable.',
  'act.err.noWebhookUrl': 'Falta la URL del webhook.',
  'act.err.headers': 'Headers inválidos (JSON malformado).',
  'act.err.webhookStatus': 'Webhook {method} {url} → {status} {statusText}',
  'act.err.webhook': 'Webhook falló: {msg}',
  'act.err.noTtsText': 'Falta el texto a leer.',
  'act.err.tts': 'No se pudo reproducir el texto-a-voz.',
  'act.err.capture': 'No se pudo abrir la herramienta de captura.',
  'act.err.noRgbColor': 'Falta el color RGB.',
  'act.err.rgbColor': 'No se pudo aplicar el color RGB (¿OpenRGB conectado?).',
  'act.err.noRgbMode': 'Falta el modo RGB.',
  'act.err.rgbMode': 'No se pudo aplicar el modo "{modo}".',
  'act.err.noRgbProfile': 'Falta el nombre del perfil RGB.',
  'act.err.rgbProfileMissing': 'Perfil RGB "{name}" no existe.',
  'act.err.rgbProfile': 'No se pudo aplicar el perfil RGB.',
  'act.err.noRgbPreset': 'Falta el ID del preset RGB.',
  'act.err.rgbPreset': 'No se pudo aplicar el preset "{id}" (¿OpenRGB conectado?).',
  'act.err.noSnap': 'Falta la posición de snap.',
  'act.err.snap': 'No se pudo snapear la ventana (¿proceso no encontrado?).',
  'act.err.unexpected': 'Error inesperado en {que}: {msg}',
  'act.err.script': 'El script terminó con error.',
  'act.err.macro': 'La macro falló.',
  'act.err.countdown': 'Countdown sub-acción falló.',
  'act.lbl.app': 'App',
  'act.lbl.web': 'Abrir URL',
  'act.lbl.shortcut': 'Acceso directo',
  'act.lbl.audio': 'Cambiar audio',
  'act.lbl.hotkey': 'Atajo',
  'act.lbl.clipboard': 'Copiar al portapapeles',
  'act.lbl.type': 'Escribir texto',
  'act.lbl.kill': 'Cerrar proceso',
  'act.lbl.notify': 'Notificación',
  'act.lbl.webhook': 'Webhook',
  'act.lbl.tts': 'Texto-a-voz',
  'act.lbl.capture': 'Captura de región',
  'act.lbl.rgbMode': 'RGB modo',
  'act.lbl.rgbProfile': 'RGB perfil',
  'act.lbl.rgbPreset': 'RGB preset',
  'act.lbl.snap': 'Window snap',
  'act.lbl.shuffle': 'Toggle shuffle',
  'act.lbl.repeat': 'Ciclar repetición',
  'act.lbl.open': 'Abrir',
  'act.lbl.brightness': 'Brillo',
  'act.lbl.volume': 'Volumen',
  'act.lbl.macro': 'Macro ({n} pasos)',
  'bar.max': 'Caben {n} con este tamano de tile',
  'bar.title': 'BARRA FLOTANTE',
  'bar.back': '← VOLVER',
  'bar.enabled': 'MOSTRAR LA BARRA',
  'bar.column': 'COLUMNA',
  'bar.dragHint': 'Arrastra un boton de la derecha a un hueco. El mismo boton solo puede estar una vez.',
  'bar.remove': 'Quitar de la barra',
  'bar.side': 'LADO DE LA PANTALLA',
  'bar.side.left': 'IZQUIERDA',
  'bar.side.right': 'DERECHA',
  'bar.opacity': 'OPACIDAD · {n}%',
  'bar.tileSize': 'TAMANO DEL TILE · {n} PX',
  'bar.position': 'POSICION',
  'bar.center': 'CENTRAR',
  'bar.available': 'BOTONES CONFIGURADOS',
  'bar.noButtons': 'Todavia no hay botones configurados que arrastrar.',
  'rgb.startupOn': 'Se aplica al abrir VirtualDeck — clic para quitarlo',
  'rgb.startupOff': 'Aplicar este perfil al abrir VirtualDeck',
  'rgb.startupHint': '◉ = se aplica solo al abrir VirtualDeck.',
  'import.rejected': 'Importación rechazada: {motivo}',
  'import.badShape': 'shape inválido',
  'cell.tipEmpty': 'Clic para configurar · Clic derecho para más opciones',
  'cell.tipFilled': '{etiqueta} — clic para ejecutar · Ctrl+clic para seleccionar',
  'glyph.load': 'Cargar "{ch}"',
  'settings.tile.square': 'CUADRADAS',
  'settings.tile.fill': 'LLENAR ÁREA',
  'settings.tile.squareHelp': 'Celdas siempre cuadradas; deja margen si la ventana no es proporcional a la grilla.',
  'settings.tile.fillHelp': 'Celdas ocupan toda el área; pueden volverse ligeramente rectangulares.',
  'rgb.spawnFailed': 'Spawn falló: {error}',
  'rgb.connectFailed': 'Falló: {error}',
  'rgb.noServer': 'sin server',
  'rgb.okDevices': 'OK · {n} dispositivos',
  'rgb.testing': 'PROBANDO...',
  'rgb.test': 'PROBAR CONEXIÓN',
  'rgb.profileSaved': 'Perfil "{nombre}" guardado.',
  'sensors.lhmFailed': 'Falló al iniciar LHM: {error}',
  'sensors.unknown': 'desconocido',
  'sensors.okCount': 'OK · {n} sensores',
  'sensors.noWebServer': 'Web server no responde tras 12s: {error}. Intentá ejecutar VirtualDeck como administrador.',
  'sensors.aclOk': 'URL ACL registrado: {url} — LHM ya no necesita admin.',
  'sensors.aclFailed': 'Falló registro URL ACL: {error}',
  'sensors.noReply': 'sin respuesta',
  'sensors.connectedCount': '● {n} sensores conectado',
  'sensors.enabledNoConn': '○ habilitado · sin conexión',
  'sensors.disabledDot': '○ deshabilitado',
  'sensors.noData': 'Sin datos. Verifica que LibreHardwareMonitor esté corriendo.',
  'sensors.offHint': 'Sensores deshabilitados. Configura LHM en TitleBar.',
  'macro.step.key': 'Tecla',
  'macro.step.hotkey': 'Combinación',
  'macro.step.text': 'Texto',
  'macro.step.click': 'Clic ratón',
  'macro.step.move': 'Mover ratón',
  'macro.step.delay': 'Pausa (ms)',
  'macro.step.scroll': 'Scroll',
  'pin.setTitle': 'ESTABLECER PIN DE 4 DÍGITOS',
  'pin.exitTitle': 'INGRESA PIN PARA SALIR',
  'pin.setHelp': 'Necesario una vez para activar el modo kiosko. Lo guardamos en tu config.',
  'pin.exitHelp': 'Modo kiosko activo. ESC desactiva con PIN.',
  'pin.save': 'GUARDAR',
  'pin.confirm': 'CONFIRMAR',
  'media.prev': 'Anterior',
  'media.playPause': 'Play/Pausa',
  'media.next': 'Siguiente',
  'media.playing': 'Reproduciendo',
  'media.paused': 'Pausado',
  'media.diagTitle': 'SMTC diagnóstico:',
  'act.err.timeout': 'Acción excedió 60s y se considera colgada.',
  'settings.scaleRange': 'Rango: 75% – 175%',
  'sensors.testing': 'PROBANDO...',
  'sensors.test': 'PROBAR',
  'sensors.registering': 'REGISTRANDO...',
  'sensors.registerAcl': 'REGISTRAR URL ACL',
  'sensors.adminHint': 'LHM viene incluido en VirtualDeck. Sensores como CPU/SMBus requieren admin — si faltan datos, abrí VirtualDeck como administrador.',
  'macro.fieldText': 'TEXTO',
  'macro.fieldKey': 'TECLA',
  'macro.textPlaceholder': 'Texto a escribir',
  'editor.previewHint': 'HOVER ✎ → EDITAR',
  'editor.previewHint2': 'CLIC → EJECUTAR',
  'sound.click': 'Click mecánico',
  'sound.tick': 'Tick',
  'sound.thud': 'Thud',
  'sound.off': 'Silencio',
  'validate.notObject': 'El archivo no contiene un objeto JSON válido.',
  'validate.missingPages': 'Falta el campo "pages" (array).',
  'validate.emptyPages': '"pages" no puede estar vacío.',
  'validate.badPage': 'Página #{n} con shape inválido (falta id/name).',
  'validate.missingButtons': 'Falta el campo "buttons" (array).',
  'validate.badButton': 'Botón #{n} con shape inválido (falta id/page/label/action).',
  'validate.missingAccent': 'Falta el campo "accent" (color hex).',
  'validate.missingWallpaper': 'Falta el campo "wallpaper".',
  'validate.badProfiles': '"profiles" debe ser un array.',
  'validate.badSound': '"soundOnPress" debe ser booleano.',
  'undo.done': '↶ Se deshizo: {label}',
  'undo.configChange': 'Cambio de configuración',
  'undo.copyBetweenPages': 'copiar entre páginas',
  'undo.moveBetweenPages': 'mover entre páginas',
  'undo.renameTo': 'renombrar a "{nombre}"',
  'undo.loadProfile': 'cargar perfil',
  'page.defaultName': 'PÁGINA {n}',
  'bug.sectionDesc': '## Descripción',
  'bug.descPlaceholder': '<!-- Describe el problema: qué hacías, qué esperabas, qué pasó -->',
  'bug.sectionSteps': '## Pasos para reproducir',
  'bug.sectionEnv': '## Entorno',
  'bug.envUnavailable': '- (no disponible)',
  'bug.sectionLog': '## Registro reciente',
  'bug.logTrimmed': '(Adjuntá el log exportado: botón "Exportar registro" en Ayuda → Acerca de)',
  'rgb.preset.off': 'APAGADO',
  'rgb.preset.gaming': 'GAMING',
  'rgb.preset.cinema': 'CINE',
  'rgb.preset.work': 'TRABAJO',
  'rgb.preset.rainbow': 'ARCOÍRIS',
  'rgb.preset.night-blue': 'AZUL NOCHE',
  'rgb.preset.alert-red': 'ALERTA ROJA',
  'editor.applyPreset': 'Aplicar preset: {nombre}',
  'full.kioskBadge': '🔒 KIOSKO',
  'full.exit': 'SALIR ⤡',
  'import.downloadFailed': 'No se pudo descargar ({motivo})',
  'import.downloadError': 'Error de descarga: {motivo}',
  'page.importRejected': 'Ese archivo no es una página exportada de VirtualDeck.',
  'page.importedName': 'IMPORTADA',
  'ed.actionSequence': 'SECUENCIA DE ACCIONES (OPCIONAL)',
  'ed.snapHint2': 'Funciona mejor con atajos globales, sin pasar por VirtualDeck.',
  'cat.APPS': 'APPS',
  'cat.WEB': 'WEB',
  'cat.MEDIA': 'MEDIA',
  'cat.SISTEMA': 'SISTEMA',
  'cat.CREATIVO': 'CREATIVO',
  'cat.RGB': 'RGB',
};
