/**
 * Diccionario espanol.
 *
 * Vive fuera de `i18n.tsx` porque el archivo llegaba a 1135 lineas y crecia
 * con cada texto nuevo: los tres diccionarios son datos, y mezclados con el
 * proveedor hacian ilegible lo poco que ahi es logica.
 *
 * Las claves son estables (no el texto). El orden importa solo para leerlo.
 */
import type { Dict } from './tipos';

export const ES: Dict = {
  // — Chrome / settings (TitleBar) —
  'settings.theme': 'TEMA',
  'settings.theme.dark': 'OSCURO',
  'settings.theme.light': 'CLARO',
  'settings.theme.system': 'SISTEMA',
  'settings.language': 'IDIOMA',
  'settings.language.system': 'SISTEMA',
  // Los nombres de idioma van cada uno en el suyo en los dos diccionarios:
  // quien busca "English" no lo encuentra bajo "Ingles".
  'settings.language.es': 'ESPAÑOL',
  'settings.language.en': 'ENGLISH',
  'settings.autostart': 'INICIAR CON WINDOWS',
  'settings.alwaysOnTop': 'SIEMPRE VISIBLE',
  'settings.uiscale': 'ESCALA DE INTERFAZ',
  'settings.tiles': 'FORMA DE BOTONES',
  'settings.tiles.square': 'CUADRADOS',
  'settings.tiles.fill': 'RELLENAR',
  // — Acciones de página / barra —
  'main.search.placeholder': 'Etiqueta, app, URL, atajo...',
  'main.search.title': 'BUSCAR BOTÓN',
  'main.search.empty': 'No hay botones configurados',
  'main.search.nomatch': 'Sin coincidencias',
  'main.search.nav': '↑↓ NAVEGAR',
  'main.search.edit': '↵ EDITAR',
  'main.search.exit': 'ESC SALIR',
  // — Update banner —
  'update.ready': 'Actualización {version} lista.',
  'update.restart': 'REINICIAR',
  'update.later': 'DESPUÉS',
  // — Onboarding —
  'onb.step': 'PASO {n} / 0{total}',
  'onb.skip': 'Saltar',
  'onb.back': 'Atrás',
  'onb.next': 'Siguiente',
  'onb.start': 'Empezar',
  'onb.1.title': 'IDIOMA · LANGUAGE',
  'onb.1.body': 'Elija el idioma de la aplicación. El resto del tutorial y toda la interfaz se mostrarán en el idioma que seleccione.',
  'onb.1.hint': 'Con SISTEMA se usa el idioma de Windows. Puede cambiarlo en cualquier momento en ⚙ → IDIOMA.',
  'onb.2.title': 'APARIENCIA',
  'onb.2.body': 'Elija el tema y el color de acento. Los cambios se aplican al instante, de modo que puede ver el resultado antes de continuar.',
  'onb.2.hint': 'El fondo se elige por separado, con el botón FONDO de la barra superior.',
  'onb.backup.export': 'EXPORTAR',
  'onb.backup.import': 'IMPORTAR',
  'onb.3.title': 'VIRTUALDECK',
  'onb.3.body': 'Su Stream Deck por software. Una cuadrícula de botones que ejecutan acciones: abrir aplicaciones, páginas web y carpetas, cambiar el audio, controlar la música, lanzar atajos, macros y más.',
  'onb.3.hint': 'Todo se guarda solo. No hay nube ni cuentas: es 100% local.',
  'onb.4.title': 'SUS BOTONES',
  'onb.4.body': 'Haga clic en cualquier celda vacía para configurarla. Elija una etiqueta, un icono y la acción que debe ejecutar. Un clic normal la lanza; el menú contextual (clic derecho) permite editarla, duplicarla o vaciarla.',
  'onb.4.hint': 'Ctrl+clic selecciona varios botones para operaciones en lote.',
  'onb.5.title': 'PÁGINAS Y CUADRÍCULA',
  'onb.5.body': 'Organice sus botones en varias páginas (pestañas superiores). Cambie entre ellas con las teclas 1-9 o deslizando. Cada página puede tener su propio tamaño de cuadrícula.',
  'onb.5.hint': 'Arrastre un botón sobre la pestaña de otra página para moverlo.',
  'onb.6.title': 'WIDGETS Y PANTALLA COMPLETA',
  'onb.6.body': 'Un botón puede mostrar reloj, clima, sensores del equipo, una variable o la música en reproducción. Acceda al modo de pantalla completa para usar VirtualDeck como panel dedicado en una tableta o un monitor secundario.',
  'onb.6.hint': 'El widget de música detecta Spotify, YouTube, navegadores y más.',
  'onb.7.title': 'RESPALDO Y AYUDA',
  'onb.7.body': 'Toda su configuración reside en un único archivo local. Expórtela para conservar una copia o trasladarla a otro equipo, o importe una existente para empezar con sus botones habituales. Ctrl+K busca cualquier botón al instante, y en ⚙ → Ayuda están la documentación, el informe de errores y este tutorial.',
  'onb.7.hint': 'En una instalación nueva todavía no hay nada que exportar: el botón está aquí para cuando lo haya. ¿Todo listo? Cree su primer botón.',
  // — Hints contextuales —
  'hint.firstButton': 'Haga clic en una celda vacía para crear su primer botón.',
  'hint.settings': 'El tema, el idioma, la escala y demás opciones están en Configuración.',
  'hint.search': 'Sugerencia: Ctrl+K busca cualquier botón al instante.',
  'hint.dismiss': 'Entendido',
  // — Ayuda y Acerca de —
  'help.title': 'AYUDA Y ACERCA DE',
  'help.docs': '📖 DOCUMENTACIÓN',
  'help.report': '🐞 REPORTAR ERROR',
  'help.check': '⟳ BUSCAR UPDATE',
  'help.checking': 'BUSCANDO…',
  'help.support': '♥ APOYAR',
  'help.donateIntro': 'VirtualDeck es gratuito. Si le resulta útil, puede apoyar su desarrollo:',
  'help.openLog': 'ABRIR REGISTRO',
  'help.exportLog': 'EXPORTAR REGISTRO',
  'help.noLog': 'Todavía no hay registro que exportar: se crea cuando ocurre el primer error.',
  'help.replay': '🎓 REPETIR TUTORIAL',
  'help.credits': 'CRÉDITOS Y LICENCIAS',
  'help.bundled': ' (incluido)',
  'help.upd.ready': 'Actualización {version} lista: reinicie para aplicarla.',
  'help.upd.downloading': 'Descargando actualización {version}…',
  'help.upd.error': 'No se pudo buscar actualizaciones.',
  'help.upd.disabled': 'La actualización automática no está disponible en esta compilación (modo desarrollo).',
  'help.upd.checkError': 'Error al buscar actualizaciones.',
  'help.upd.checking': 'Buscando actualizaciones…',
  // — Tooltips de la barra superior —
  'tip.export': 'Exportar configuración',
  'tip.import': 'Importar configuración',
  'tip.bar': 'Columna de tiles flotante sobre el escritorio',
  'tip.rgb': 'Gestor RGB',
  'tip.settings': 'Configuración',
  'tip.fullscreen': 'Modo pantalla completa',
  'tip.minimize': 'Minimizar',
  'tip.close': 'Cerrar (minimiza a bandeja)',
  // — Pantalla de fondos (WallpaperB) —
  'wp.back': '← VOLVER',
  'wp.preview': 'VISTA PREVIA',
  'wp.select': 'SELECCIONAR FONDO',
  'wp.applied': '✓ APLICADO',
  'wp.apply': 'APLICAR →',
  'wp.selected': '● SELECCIONADO',
  'wp.autosave': 'Los cambios se guardan automáticamente al pulsar Aplicar.',
  'wp.name.solid': 'Sólido',
  'wp.name.gradient': 'Gradiente Azul',
  'wp.name.dotgrid': 'Cuadrícula Dot',
  'wp.name.scanlines': 'Scanlines',
  'wp.name.crt': 'CRT',
  'wp.name.mesh': 'Mesh técnico',
  'wp.name.photo': 'Neón',
  'wp.name.grid-blue': 'Grid Azul',
  // — Editor de botón (chrome: pasos y navegación) —
  'ed.title': 'CONFIGURAR BOTÓN',
  'ed.preview': 'VISTA PREVIA',
  'ed.step.action': 'ACCIÓN',
  'ed.step.config': 'CONFIGURAR',
  'ed.step.style': 'ESTILO',
  'ed.back': '← ATRÁS',
  'ed.cancel': 'CANCELAR',
  'ed.next': 'SIGUIENTE →',
  'ed.save': 'GUARDAR ✓',
  'ed.stepN': 'PASO {n} / {total}',
  'ed.toggleMode': 'MODO TOGGLE',
  // — Tipos de acción (selector del editor) —
  'act.none.label': 'Ninguno', 'act.none.desc': 'Sin acción asignada',
  'act.app.label': 'Abrir App', 'act.app.desc': 'Ejecuta una aplicación',
  'act.web.label': 'Página Web', 'act.web.desc': 'Abre una URL en el navegador',
  'act.shortcut.label': 'Acceso Dir.', 'act.shortcut.desc': 'Abre un archivo o carpeta',
  'act.script.label': 'Script', 'act.script.desc': 'Ejecuta PowerShell o CMD',
  'act.audio-device.label': 'Audio', 'act.audio-device.desc': 'Cambia dispositivo de salida',
  'act.hotkey.label': 'Atajo', 'act.hotkey.desc': 'Envía combinación de teclas',
  'act.clipboard.label': 'Portapapeles', 'act.clipboard.desc': 'Copia texto al portapapeles',
  'act.type-text.label': 'Escribir', 'act.type-text.desc': 'Escribe texto automáticamente',
  'act.kill-process.label': 'Cerrar App', 'act.kill-process.desc': 'Termina un proceso por nombre',
  'act.volume-set.label': 'Vol. Exacto', 'act.volume-set.desc': 'Establece volumen a un % exacto',
  'act.folder.label': 'Carpeta', 'act.folder.desc': 'Abre un sub-deck de botones',
  'act.media-play-pause.label': 'Play/Pausa', 'act.media-play-pause.desc': 'Reproducir / Pausar',
  'act.media-next.label': 'Siguiente', 'act.media-next.desc': 'Siguiente pista',
  'act.media-prev.label': 'Anterior', 'act.media-prev.desc': 'Pista anterior',
  'act.volume-up.label': 'Vol. ＋', 'act.volume-up.desc': 'Sube el volumen',
  'act.volume-down.label': 'Vol. −', 'act.volume-down.desc': 'Baja el volumen',
  'act.mute.label': 'Silenciar', 'act.mute.desc': 'Silencia / activa sonido',
  'act.brightness.label': 'Brillo', 'act.brightness.desc': 'Controla brillo del monitor',
  'act.notify.label': 'Notificación', 'act.notify.desc': 'Muestra una notificación de Windows',
  'act.set-var.label': 'Var: Asignar', 'act.set-var.desc': 'Asigna valor a una variable global',
  'act.incr-var.label': 'Var: Sumar', 'act.incr-var.desc': 'Incrementa o decrementa una variable numérica',
  'act.webhook.label': 'Webhook', 'act.webhook.desc': 'POST/GET a una URL con body y headers',
  'act.tts.label': 'Texto-a-voz', 'act.tts.desc': 'Lee un texto en voz alta',
  'act.region-capture.label': 'Captura', 'act.region-capture.desc': 'Abre la captura de región de Windows',
  'act.rgb-color.label': 'RGB Color', 'act.rgb-color.desc': 'Pinta un color sólido en un dispositivo RGB',
  'act.rgb-mode.label': 'RGB Modo', 'act.rgb-mode.desc': 'Cambia el modo/efecto RGB (Direct, Breathing, etc.)',
  'act.rgb-profile.label': 'RGB Perfil', 'act.rgb-profile.desc': 'Aplica un perfil RGB guardado',
  'act.window-snap.label': 'Snap Ventana', 'act.window-snap.desc': 'Mueve y redimensiona una ventana a un cuadrante',
  'act.branch.label': 'Si / Si no', 'act.branch.desc': 'Ejecuta acción A o B según el valor de una variable',
  'act.countdown.label': 'Temporizador', 'act.countdown.desc': 'Espera N ms y luego ejecuta una acción',
  'act.media-shuffle.label': 'Shuffle', 'act.media-shuffle.desc': 'Alterna shuffle en el reproductor activo (SMTC)',
  'act.media-repeat.label': 'Repetir', 'act.media-repeat.desc': 'Cicla el modo de repetición (ninguno → lista → pista)',
  'act.macro.label': 'Macro', 'act.macro.desc': 'Secuencia de teclas y clics de ratón grabada o configurada',

  // ── Gestor RGB ──
  'rgb.connFailed': 'Conexión falló: {err}',
  'rgb.connFailedNoServer': 'Conexión falló (¿está activo el servidor de OpenRGB?)',
  'rgb.profilePartial': 'Algunos dispositivos no aceptaron el perfil.',
  'rgb.resizeFailed': 'No se pudo redimensionar la zona.',
  'rgb.disconnect': 'DESCONECTAR',
  'rgb.connect': 'CONECTAR',
  'rgb.rescan': 'Reescanear dispositivos',
  'rgb.notConnected': 'NO CONECTADO',
  'rgb.setPath': '· Configure la ruta de OpenRGB.exe en el panel de ajustes (icono ⚙ de la pantalla principal → sección RGB).',
  'rgb.serverHint': '· Asegúrese de que el servidor SDK esté activo (puerto {port}). VirtualDeck inicia OpenRGB en modo --server, sin interfaz, de modo que no aparece el diálogo de tamaño de zonas.',
  'rgb.lastError': 'Último error: {err}',
  'rgb.devices': 'DISPOSITIVOS',
  'rgb.noDevices': 'Ningún dispositivo detectado.',
  'rgb.connectToSee': 'Conecte para ver los dispositivos.',
  'rgb.quickActions': 'ACCIONES RÁPIDAS',
  'rgb.allOff': 'APAGAR TODO',
  'rgb.allWhite': 'BLANCO TOTAL',
  'rgb.accentColor': 'COLOR ACENTO',
  'rgb.profiles': 'PERFILES RGB',
  'rgb.presets': 'PRESETS',
  'rgb.noProfiles': 'Sin perfiles aún.',
  'rgb.apply': 'APLICAR',
  'rgb.save': 'GUARDAR',
  'rgb.newProfile': 'Nuevo perfil...',
  'rgb.connected': 'CONECTADO · {n} DISP',
  'rgb.serverUp': 'SERVIDOR ACTIVO',
  'rgb.disconnected': 'DESCONECTADO',
  'rgb.deviceOne': 'DISPOSITIVO',
  'rgb.deviceMany': 'DISPOSITIVOS',
  'rgb.color': 'COLOR',
  'rgb.mode': 'MODO',
  'rgb.speed': 'VELOCIDAD · {n}%',
  'rgb.zones': 'ZONAS',
  'rgb.zoneLeds': '{n} LEDS',
  'rgb.zoneResizable': ' · {min}-{max} REDIM.',
  'rgb.paintLeds': 'PINTAR LEDs INDIVIDUALES',
  'rgb.hide': 'OCULTAR',
  'rgb.show': 'MOSTRAR',
  'rgb.noLeds': 'No hay LEDs reportados para este dispositivo.',
  'rgb.notPerLed': '⚠ El modo actual ({mode}) no es por LED. Cambie a Direct o Custom para que los cambios sean visibles.',
  'rgb.ledsHint': '{n} LED · Clic para pintar con el color seleccionado',
  'rgb.calibrator': 'CALIBRADOR DE ZONAS ARGB',
  'rgb.calibratorHelp': 'Para cada zona redimensionable: pulse IDENTIFICAR para que un LED se encienda en blanco recorriendo toda la cadena. Cuente cuántos LED ha visto y guarde ese número. Esto sustituye al diálogo de OpenRGB y se conserva en la configuración local.',
  'rgb.noResizable': 'No hay zonas redimensionables detectadas.',
  'rgb.range': 'RANGO {min}–{max} · ACTUAL {cur}',
  'rgb.saved': ' · GUARDADO {n}',
  'rgb.suggestion': '◆ Sugerencia: {note}',
  'rgb.identify': 'IDENTIFICAR',
  'rgb.hint.unifan': 'Lian Li UNI Fan SL (16 LEDs por ventilador)',
  'rgb.hint.strimer24': 'Strimer Plus 24-pin',
  'rgb.hint.strimer8': 'Strimer Plus 8-pin',
  'rgb.hint.argb': 'Cabezal ARGB genérico (estimado)',
  // ── Barra flotante ──
  'bar.short': 'BARRA',
  'bar.close': 'Cerrar la barra flotante',
  // Las 23 condiciones WMO del widget de clima. Estaban escritas en espanol
  // dentro del propio componente: con la app en ingles el tooltip decia
  // «Parcial. nub.».
  'wx.0': 'Despejado',
  'wx.1': 'Mayorm. desp.',
  'wx.2': 'Parcial. nub.',
  'wx.3': 'Cubierto',
  'wx.45': 'Niebla',
  'wx.48': 'Niebla c/escar.',
  'wx.51': 'Llovizna leve',
  'wx.53': 'Llovizna mod.',
  'wx.55': 'Llovizna fuerte',
  'wx.61': 'Lluvia leve',
  'wx.63': 'Lluvia moderada',
  'wx.65': 'Lluvia fuerte',
  'wx.71': 'Nieve leve',
  'wx.73': 'Nieve moderada',
  'wx.75': 'Nieve fuerte',
  'wx.77': 'Granizo fino',
  'wx.80': 'Chubascos lev.',
  'wx.81': 'Chubascos mod.',
  'wx.82': 'Chubascos fuer.',
  'wx.85': 'Nieve chubascos',
  'wx.95': 'Tormenta',
  'wx.96': 'Tormenta/granizo',
  'wx.99': 'Tormenta fuerte',
  'wx.unknown': 'Desconocido',
  'weather.loading': 'Cargando clima...',
  'panel.noMedia': 'Sin reproducción activa',
  'ed.pickSensor': '— Seleccione un sensor —',
  'brand.search': 'Buscar icono...',
  'cell.editShort': 'Editar',
  'macro.scrollHint': '(+ arriba, − abajo)',
  'ed.cancelCapture': '✕ cancelar',
  'bulk.move': '↗ MOVER',
  'bulk.clear': '✕ LIMPIAR',
  'panel.openRgb': 'Abrir Gestor RGB',
  'panel.clearLog': 'Limpiar log',
  'ui.back': '← VOLVER',
  'brand.clearAll': 'LIMPIAR TODO',
  'brand.activeColor': 'COLOR ACTIVO',
  'brand.hint': '17×17 · Admite varios colores · Las animaciones siguen el patrón de puntos',
  'brand.saveIcon': 'GUARDAR ICONO ✓',
  'glyph.fromFont': 'CARGAR DESDE TIPOGRAFÍA',
  'glyph.empty': 'Vacío: al guardar se eliminará del botón',
  'ui.saveShort': 'GUARDAR',
  'set.noProfiles': 'Sin perfiles guardados.',
  'macro.recording': 'REC • pulse teclas y haga clics...',
  'macro.noSteps': 'Sin pasos. Grabe una macro o añada pasos manualmente.',
  'ed.killHint': 'Use el nombre exacto del ejecutable. Equivale a taskkill /IM nombre /F.',
  'ed.volumeHint': 'Establece el volumen maestro del sistema al porcentaje indicado.',
  'ed.noRgbProfiles': 'No hay perfiles RGB guardados. Abra la pantalla RGB y guarde un perfil con el estado actual de sus dispositivos.',
  'ed.snapHint': 'Sin nombre de proceso, ajusta la ventana que esté en primer plano al ejecutarse.',
  'ed.radioHint': 'Todos los toggles con el mismo grupo se desactivan cuando se activa este.',
  'ed.triggers': 'DISPARADORES EXTERNOS',
  'ed.thresholdHint': 'Warn pinta el valor en amarillo, Crit en rojo. Mismas unidades que el sensor.',
  'folder.empty': 'Sin botones configurados. Edite este botón para añadirlos.',
  'folder.esc': 'ESC PARA CERRAR',
  'rgb.pickDevice': 'Seleccione un dispositivo en la lista de la izquierda.',
  // ── Palabras sueltas de interfaz ──
  'ui.none': 'NINGUNO',
  'ui.cancel': 'CANCELAR',
  'ui.clear': 'LIMPIAR',
  'ui.fill': 'RELLENAR',
  'ui.save': 'GUARDAR ✓',
  'ui.port': 'PUERTO',
  'ui.wallpaper': 'FONDO',
  'ui.import': 'IMPORTAR',
  'ui.load': 'CARGAR',
  'ui.repeat': 'REPETIR',
  'ui.times': 'VECES',
  'ui.mouseL': 'Izq',
  'ui.mouseR': 'Der',
  'ui.mouseM': 'Med',
  'ui.units': 'UNIDADES',
  'ui.pause': 'PAUSA',
  'full.title': 'VIRTUALDECK · MODO PANTALLA COMPLETA',
  'ui.columns': 'COLUMNAS',
  'page.grid': 'CUADRÍCULA',
  'ui.rows': 'FILAS',
  'ui.moveTo': 'MOVER A...',
  // ── Ajustes, paginas y menus ──
  'undo.duplicate': 'duplicar botón',
  'undo.clear': 'limpiar botón',
  'undo.addPage': 'agregar página',
  'undo.delPage': 'eliminar página',
  'undo.movePage': 'reordenar páginas',
  'undo.importPage': 'importar página',
  'cell.edit': 'Editar botón',
  'cell.duplicate': 'Duplicar',
  'cell.clear': 'Limpiar botón',
  'set.accent': 'COLOR DE ACENTO',
  'set.scale': 'ESCALA DE INTERFAZ',
  'set.tiles': 'FORMA DE LAS CELDAS',
  'set.chime': 'TIMBRE',
  'set.profiles': 'PERFILES',
  'set.sound': 'SONIDO AL PULSAR',
  'set.profileName': 'Nombre del perfil...',
  'set.rgb': 'RGB (OPENRGB)',
  'set.rgbPath': 'RUTA OPENRGB.EXE',
  'set.enabled': 'HABILITADO',
  'set.rgbSpawn': 'LANZAR OPENRGB AL ARRANCAR',
  'set.rgbAuto': 'AUTOCONECTAR',
  'set.gallery': 'GALERIA DE PERFILES',
  'gal.load': 'CARGAR',
  'gal.loading': 'CARGANDO...',
  'gal.hint': 'Pegue la direccion de un manifest.json. Todavia no hay galeria oficial publicada: por ahora sirve cualquiera que usted o alguien de confianza aloje.',
  'gal.failed': 'No se pudo cargar: {error}',
  'gal.empty': 'Ese manifiesto no trae ningun perfil valido.',
  'gal.notADeck': 'Ese archivo no parece un deck: le faltan las paginas o los botones.',
  'gal.warn': 'Un perfil no son solo datos. Lo que aparece abajo se ejecutara en su equipo cuando pulse esos botones. Reviselo antes de importar.',
  'gal.counts': 'Trae {n} botones.',
  'gal.launches': 'Abre estos programas o archivos:',
  'gal.runs': 'Ejecuta estos scripts:',
  'gal.hotkeys': 'Registra estos atajos globales: {list}',
  'gal.nothingRisky': 'No lanza programas ni ejecuta scripts.',
  'gal.import': 'IMPORTAR COMO PERFIL',
  'set.remote': 'SERVIDOR LOCAL (HTTP)',
  'set.remoteToken': 'TOKEN',
  'set.remoteTokenHint': 'Pulse para ver u ocultar el token.',
  'set.remoteNewToken': 'NUEVO TOKEN',
  'set.remoteCopyToken': 'COPIAR',
  'set.remotePair': 'EMPAREJAR TELEFONO',
  'set.remotePairHint': 'En el telefono, abra {url} y escriba el codigo. Caduca en {min} min.',
  'set.remotePairNeedsLan': 'Para que el telefono llegue hace falta activar PERMITIR LA RED LOCAL.',
  'set.remoteLan': 'PERMITIR LA RED LOCAL',
  'set.remoteLanWarn': 'Sin activar, solo responde a este equipo. Activado, cualquiera en su red que tenga el token puede pulsar botones, incluidos los que ejecutan scripts. La conexion no va cifrada.',
  'set.remoteListening': 'Escuchando en {url}',
  'set.remoteStopped': 'Detenido.',
  'set.remoteHint': 'El token va en la cabecera X-VD-Token, no en la direccion. Rutas: /api/ping, /api/buttons, /api/press/<id>, /api/press?label=<etiqueta>, /api/page/<n>.',
  'set.musicPanel': 'PANEL DE MUSICA',
  'set.musicPanelHint': 'Aparece al lado de la cuadricula solo cuando hay algo sonando, con la caratula grande y botones pensados para el dedo.',
  'panel.music': 'MUSICA',
  'music.hide': 'Ocultar el panel',
  'media.shuffle': 'ALEATORIO',
  'media.repeat': 'REPETIR',
  'ui.left': 'IZQUIERDA',
  'ui.right': 'DERECHA',
  'set.sensors': 'SENSORES (LIBRE HARDWARE MONITOR)',
  'set.lhmPath': 'RUTA DE LHM (vacío = se busca sola)',
  'sensors.catOther': 'OTROS',
  'set.categories': 'CATEGORÍAS VISIBLES',
  'set.sensorWidget': 'MOSTRAR WIDGET DE SENSORES',
  'set.lhmStart': 'INICIAR LHM CON VIRTUALDECK',
  'set.lhmAdmin': 'INICIAR LHM COMO ADMINISTRADOR (UAC)',
  'set.urlAcl': 'Registra una reserva URL ACL en Windows (una sola confirmación de UAC). Después LHM puede ejecutarse sin permisos de administrador.',
  'page.noRoom': 'No hay hueco libre en "{pagina}".',
  'page.tip': 'Clic para cambiar · Doble clic para renombrar · Arrastrar para reordenar · Clic derecho para más opciones',
  'page.add': 'Agregar página',
  'page.export': 'Exportar página actual',
  'page.import': 'Importar página desde archivo',
  'page.rename': 'Renombrar',
  'page.delete': 'Eliminar página',
  'media.diagnose': 'Diagnosticar widget de música',
  'panel.weather': 'CLIMA',
  'panel.sensors': 'SENSORES',
  'panel.log': 'LOG',
  'panel.playing': 'REPRODUCIENDO',
  'full.clock': 'HORA LOCAL',
  'full.page': 'PÁGINA',
  'full.noMedia': 'SIN REPRODUCCIÓN',
  'brand.none': 'Sin icono de marca',
  'brand.g.all': 'Todos',
  'brand.g.design': 'Diseño y Producción',
  'brand.g.streaming': 'Streaming y Contenido',
  'brand.g.dev': 'Programación y Dev',
  'brand.g.productivity': 'Productividad',
  'brand.g.media': 'Multimedia y Ocio',
  'brand.g.system': 'Utilidades y Sistema',
  'brand.i.settings': 'Configuración',
  'brand.i.controlPanel': 'Panel de Control',
  'brand.title': 'ICONOS DE MARCA ANIMADOS',
  'weather.none': 'Sin datos de clima',
  'glyph.title': 'EDITOR DE GLIFO 5×7',
  'rgb.calibPending': '⚠ CALIBRACIÓN PENDIENTE',
  'ed.noSensors': '(sin sensores: habilite LHM y conéctelo desde la barra de título)',
  // ── Errores y etiquetas de acciones ──
  'act.err.sinManejador': 'La acción "{tipo}" no está implementada.',
  'act.err.noAppPath': 'Falta la ruta del programa.',
  'act.err.launch': 'No se pudo iniciar: {que}. Compruebe la ruta.',
  'act.err.noUrl': 'Falta la URL.',
  'act.err.openUrl': 'No se pudo abrir: {url}',
  'act.err.noShortcut': 'Falta el acceso directo.',
  'act.err.shortcut': 'No se pudo abrir el acceso directo.',
  'act.err.noDevice': 'Falta el dispositivo de audio.',
  'act.err.deviceNotFound': 'No se encontró el dispositivo "{name}". Compruebe el nombre en Configuración → Sonido.',
  'act.err.switchAudio': 'No se pudo cambiar el audio a "{name}".',
  'act.err.noHotkey': 'Falta la combinación de teclas.',
  'act.err.hotkey': 'No se pudo enviar el atajo {hotkey}.',
  'act.err.noBrightness': 'Falta el nivel de brillo.',
  'act.err.brightness': 'No se pudo ajustar el brillo (¿monitor sin soporte WMI?).',
  'act.err.noClipText': 'Falta el texto a copiar.',
  'act.err.clipboard': 'No se pudo copiar al portapapeles.',
  'act.err.noTypeText': 'Falta el texto a escribir.',
  'act.err.type': 'No se pudo escribir el texto.',
  'act.err.noProcess': 'Falta el nombre del proceso.',
  'act.err.kill': 'No se pudo cerrar "{name}". ¿Está en ejecución?',
  'act.err.noVolume': 'Falta el nivel de volumen.',
  'act.err.volume': 'No se pudo ajustar el volumen.',
  'act.err.notify': 'No se pudo mostrar la notificación.',
  'act.err.media': 'No se pudo enviar el control de media ({cmd}).',
  'act.err.shuffle': 'No se pudo alternar la reproducción aleatoria (¿hay algún reproductor activo?).',
  'act.err.repeat': 'No se pudo cambiar el modo de repetición.',
  'act.err.macroEmpty': 'La macro no tiene pasos.',
  'act.err.mediaKey': 'No se pudo enviar la tecla multimedia ({tipo}).',
  'act.err.noVar': 'Falta nombre de variable.',
  'act.err.noWebhookUrl': 'Falta la URL del webhook.',
  'act.err.headers': 'Headers inválidos (JSON malformado).',
  'act.err.webhookStatus': 'Webhook {method} {url} → {status} {statusText}',
  'act.err.webhook': 'Webhook falló: {msg}',
  'act.err.noTtsText': 'Falta el texto a leer.',
  'act.err.tts': 'No se pudo reproducir el texto en voz alta.',
  'act.err.capture': 'No se pudo abrir la herramienta de captura.',
  'act.err.noRgbColor': 'Falta el color RGB.',
  'act.err.rgbColor': 'No se pudo aplicar el color RGB (¿OpenRGB conectado?).',
  'act.err.noRgbMode': 'Falta el modo RGB.',
  'act.err.rgbMode': 'No se pudo aplicar el modo "{modo}".',
  'act.err.noRgbProfile': 'Falta el nombre del perfil RGB.',
  'act.err.rgbProfileMissing': 'Perfil RGB "{name}" no existe.',
  'act.err.rgbProfile': 'No se pudo aplicar el perfil RGB.',
  'act.err.noRgbPreset': 'Falta el ID del preset RGB.',
  'act.err.rgbPreset': 'No se pudo aplicar el preset "{id}" (¿OpenRGB conectado?).',
  'act.err.noSnap': 'Falta la posición de snap.',
  'act.err.snap': 'No se pudo ajustar la ventana (¿no se encontró el proceso?).',
  'act.err.unexpected': 'Error inesperado en {que}: {msg}',
  'act.err.script': 'El script terminó con error.',
  'act.err.macro': 'La macro falló.',
  'act.err.countdown': 'Countdown sub-acción falló.',
  'act.lbl.app': 'App',
  'act.lbl.web': 'Abrir URL',
  'act.lbl.shortcut': 'Acceso directo',
  'act.lbl.audio': 'Cambiar audio',
  'act.lbl.hotkey': 'Atajo',
  'act.lbl.clipboard': 'Copiar al portapapeles',
  'act.lbl.type': 'Escribir texto',
  'act.lbl.kill': 'Cerrar proceso',
  'act.lbl.notify': 'Notificación',
  'act.lbl.webhook': 'Webhook',
  'act.lbl.tts': 'Texto-a-voz',
  'act.lbl.capture': 'Captura de región',
  'icon.setPrimary': 'Definir como color principal (#)',
  'rgb.pickProfile': '— Elija un perfil —',
  'act.lbl.rgbColor': 'RGB color',
  'act.lbl.rgbMode': 'RGB modo',
  'act.lbl.rgbProfile': 'RGB perfil',
  'act.lbl.rgbPreset': 'RGB preset',
  'act.lbl.snap': 'Window snap',
  'act.lbl.shuffle': 'Toggle shuffle',
  'act.lbl.repeat': 'Ciclar repetición',
  'act.lbl.open': 'Abrir',
  'act.lbl.brightness': 'Brillo',
  'act.lbl.volume': 'Volumen',
  'act.lbl.macro': 'Macro ({n} pasos)',
  'bar.max': 'Caben {n} con este tamaño de casilla',
  'bar.title': 'BARRA FLOTANTE',
  'bar.back': '← VOLVER',
  'bar.enabled': 'MOSTRAR LA BARRA',
  'bar.column': 'COLUMNA',
  'bar.dragHint': 'Arrastre un botón de la derecha hasta un hueco. El mismo botón solo puede aparecer una vez.',
  'bar.remove': 'Quitar de la barra',
  'bar.side': 'LADO DE LA PANTALLA',
  'bar.side.left': 'IZQUIERDA',
  'bar.side.right': 'DERECHA',
  'bar.opacity': 'OPACIDAD · {n}%',
  'bar.tileSize': 'TAMAÑO DE CASILLA · {n} PX',
  'bar.position': 'POSICION',
  'bar.center': 'CENTRAR',
  'bar.available': 'BOTONES CONFIGURADOS',
  'bar.noButtons': 'Todavía no hay botones configurados que arrastrar.',
  'rgb.startupOn': 'Se aplica al abrir VirtualDeck; haga clic para quitarlo',
  'rgb.startupOff': 'Aplicar este perfil al abrir VirtualDeck',
  'rgb.startupHint': '◉ = se aplica solo al abrir VirtualDeck.',
  'import.rejected': 'Importación rechazada: {motivo}',
  'import.badShape': 'shape inválido',
  'cell.tipEmpty': 'Clic para configurar · Clic derecho para más opciones',
  'cell.tipFilled': '{etiqueta} — clic para ejecutar · Ctrl+clic para seleccionar',
  'glyph.load': 'Cargar "{ch}"',
  'settings.tile.square': 'CUADRADAS',
  'settings.tile.fill': 'LLENAR ÁREA',
  'settings.tile.squareHelp': 'Celdas siempre cuadradas; deja margen si la ventana no es proporcional a la cuadrícula.',
  'settings.tile.fillHelp': 'Las celdas ocupan toda el área; pueden volverse ligeramente rectangulares.',
  'rgb.spawnFailed': 'Spawn falló: {error}',
  'rgb.connectFailed': 'Falló: {error}',
  'rgb.noServer': 'sin server',
  'rgb.okDevices': 'OK · {n} dispositivos',
  'rgb.testing': 'PROBANDO...',
  'rgb.test': 'PROBAR CONEXIÓN',
  'rgb.profileSaved': 'Perfil "{nombre}" guardado.',
  'rgb.profileUpdated': 'Perfil "{nombre}" sobrescrito.',
  'rgb.calibrate': 'CALIBRAR',
  'rgb.zoneCount': '{n} ZONA',
  'rgb.zoneCountN': '{n} ZONAS',
  'rgb.ledCount': '{n} LEDS',
  'sensors.lhmFailed': 'Falló al iniciar LHM: {error}',
  'sensors.unknown': 'desconocido',
  'sensors.okCount': 'OK · {n} sensores',
  'sensors.noWebServer': 'El servidor web no responde tras 12 s: {error}. Pruebe a ejecutar VirtualDeck como administrador.',
  'sensors.aclOk': 'Reserva URL ACL registrada: {url}. LHM ya no necesita permisos de administrador.',
  'sensors.aclFailed': 'Falló registro URL ACL: {error}',
  'sensors.noReply': 'sin respuesta',
  'sensors.connectedCount': '● {n} sensores conectado',
  'sensors.enabledNoConn': '○ habilitado · sin conexión',
  'sensors.disabledDot': '○ deshabilitado',
  'sensors.noData': 'Sin datos. Compruebe que LibreHardwareMonitor esté en ejecución.',
  'sensors.offHint': 'Sensores deshabilitados. Configure LHM desde la barra de título.',
  'macro.step.key': 'Tecla',
  'macro.step.hotkey': 'Combinación',
  'macro.step.text': 'Texto',
  'macro.step.click': 'Clic ratón',
  'macro.step.move': 'Mover ratón',
  'macro.step.delay': 'Pausa (ms)',
  'macro.step.scroll': 'Scroll',
  'pin.setTitle': 'ESTABLEZCA UN PIN DE 4 DÍGITOS',
  'pin.exitTitle': 'INTRODUZCA EL PIN PARA SALIR',
  'pin.setHelp': 'Se solicita una sola vez para activar el modo kiosko. Se guarda en su configuración.',
  'pin.exitHelp': 'Modo kiosko activo. ESC lo desactiva introduciendo el PIN.',
  'pin.save': 'GUARDAR',
  'pin.confirm': 'CONFIRMAR',
  'media.prev': 'Anterior',
  'media.playPause': 'Play/Pausa',
  'media.next': 'Siguiente',
  'media.playing': 'Reproduciendo',
  'media.paused': 'Pausado',
  'media.diagTitle': 'SMTC diagnóstico:',
  'act.err.timeout': 'La acción superó los 60 s y se considera bloqueada.',
  'settings.scaleRange': 'Rango: 75% – 175%',
  'sensors.testing': 'PROBANDO...',
  'sensors.test': 'PROBAR',
  'sensors.lhmStart': 'INICIAR LHM',
  'sensors.lhmStarting': 'INICIANDO...',
  'sensors.lhmRunning': 'LHM ACTIVO',
  'sensors.lhmStop': 'DETENER LHM',
  'sensors.lhmMissing': 'LibreHardwareMonitor no está instalado. Descárguelo, ábralo y active Options → Remote Web Server → Run, con el puerto 8085.',
  'sensors.lhmDownload': 'Descargar LHM',
  'sensors.lhmFound': 'Detectado en {ruta}',
  'set.tablet': 'PANTALLA TÁCTIL',
  'set.tabletOpen': 'CONFIGURAR PANTALLA TÁCTIL',
  'set.tabletHelp': 'Abre la herramienta de Windows donde se indica cuál de los monitores responde al tacto. Pulse «Configurar» y siga las instrucciones en la pantalla que vaya a usar.',
  'set.tabletFailed': 'No se pudo abrir. Es posible que este equipo no tenga pantalla táctil.',
  'editor.stdoutToVar': 'La salida del script se guarda en la variable y puede usarse como {ejemplo} en otros pasos.',
  'sensors.registering': 'REGISTRANDO...',
  'sensors.registerAcl': 'REGISTRAR URL ACL',
  'sensors.adminHint': 'LHM se instala aparte, igual que OpenRGB. Algunos sensores, como los de CPU o SMBus, requieren permisos de administrador: si faltan datos, abra LibreHardwareMonitor como administrador.',
  'macro.fieldText': 'TEXTO',
  'macro.fieldKey': 'TECLA',
  'macro.textPlaceholder': 'Texto a escribir',
  'macro.rec.start': 'GRABAR',
  'macro.rec.stop': 'DETENER',
  'macro.textDefault': 'Hola mundo',
  'macro.recEmpty': 'No se capturó ninguna tecla ni clic. Los clics sobre esta ventana no cuentan: use el teclado o haga clic fuera de ella.',
  'editor.previewHint': 'HOVER ✎ → EDITAR',
  'editor.previewHint2': 'CLIC → EJECUTAR',
  'sound.click': 'Click mecánico',
  'sound.tick': 'Tick',
  'sound.thud': 'Thud',
  'sound.off': 'Silencio',
  'validate.notObject': 'El archivo no contiene un objeto JSON válido.',
  'validate.missingPages': 'Falta el campo "pages" (array).',
  'validate.emptyPages': '"pages" no puede estar vacío.',
  'validate.badPage': 'La página n.º {n} tiene un formato no válido (falta id o name).',
  'validate.missingButtons': 'Falta el campo "buttons" (array).',
  'validate.badButton': 'El botón n.º {n} tiene un formato no válido (falta id, page, label o action).',
  'validate.missingAccent': 'Falta el campo "accent" (color hex).',
  'validate.missingWallpaper': 'Falta el campo "wallpaper".',
  'validate.badProfiles': '"profiles" debe ser un array.',
  'validate.badSound': '"soundOnPress" debe ser booleano.',
  'undo.done': '↶ Se deshizo: {label}',
  'undo.configChange': 'Cambio de configuración',
  'undo.copyBetweenPages': 'copiar entre páginas',
  'undo.moveBetweenPages': 'mover entre páginas',
  'undo.renameTo': 'renombrar a "{nombre}"',
  'undo.loadProfile': 'cargar perfil',
  'page.defaultName': 'PÁGINA {n}',
  'bug.sectionDesc': '## Descripción',
  'bug.descPlaceholder': '<!-- Describa el problema: qué estaba haciendo, qué esperaba y qué ocurrió -->',
  'bug.sectionSteps': '## Pasos para reproducir',
  'bug.sectionEnv': '## Entorno',
  'bug.envUnavailable': '- (no disponible)',
  'bug.sectionLog': '## Registro reciente',
  'bug.logTrimmed': '(Adjunte el registro exportado: botón "Exportar registro" en Ayuda → Acerca de)',
  'rgb.preset.off': 'APAGADO',
  'rgb.preset.gaming': 'GAMING',
  'rgb.preset.cinema': 'CINE',
  'rgb.preset.work': 'TRABAJO',
  'rgb.preset.rainbow': 'ARCOÍRIS',
  'rgb.preset.night-blue': 'AZUL NOCHE',
  'rgb.preset.alert-red': 'ALERTA ROJA',
  'editor.applyPreset': 'Aplicar preset: {nombre}',
  'full.kioskBadge': '🔒 KIOSKO',
  'full.exit': 'SALIR ⤡',
  'page.importRejected': 'Ese archivo no es una página exportada de VirtualDeck.',
  'page.importedName': 'IMPORTADA',
  'ed.seq.delay': 'ESPERA',
  'ed.seq.delayTitle': 'Milisegundos de espera antes de ejecutar este paso. Vacio = 150 ms.',
  'ed.seq.repeat': 'REPETIR',
  'ed.seq.repeatTitle': 'Cuantas veces se ejecuta este paso seguido. Vacio = una vez.',
  'ed.seq.onlyIfOk': 'SOLO SI OK',
  'ed.seq.onlyIfOkTitle': 'Ejecutar este paso solo si el anterior termino bien.',
  'ed.actionSequence': 'SECUENCIA DE ACCIONES (OPCIONAL)',
  'ed.snapHint2': 'Funciona mejor con atajos globales, sin pasar por VirtualDeck.',
  'cat.APPS': 'APPS',
  'cat.WEB': 'WEB',
  'cat.MEDIA': 'MEDIA',
  'cat.SISTEMA': 'SISTEMA',
  'cat.CREATIVO': 'CREATIVO',
  'cat.RGB': 'RGB',
  'act.err.noDelta': 'El botón de ajuste no tiene cuánto subir o bajar.',
  'act.err.noReadBrightness': 'No se pudo leer el brillo actual. Un monitor externo suele no exponerlo.',
  'act.err.noReadVolume': 'No se pudo leer el volumen actual.',
  'act.adjust.label': 'Subir / Bajar',
  'act.adjust.desc': 'Sube o baja el brillo o el volumen desde donde esté',
  'rgb.preset.reading': 'LECTURA',
  'rgb.preset.focus': 'CONCENTRACIÓN',
  'rgb.preset.dim': 'TENUE',
  'rgb.preset.sunset': 'ATARDECER',
  'rgb.preset.ocean': 'OCÉANO',
  'rgb.preset.forest': 'BOSQUE',
  'rgb.preset.candle': 'VELA',
  'rgb.preset.violet': 'VIOLETA',
  'rgb.preset.party': 'FIESTA',
  'rgb.preset.wave': 'OLA',
  'rgb.preset.strobe': 'ESTROBO',
  'undo.clearMany': 'vaciar {n} botones',
  'undo.reorder': 'reordenar botones',
  'undo.edit': 'editar "{nombre}"',
  'undo.gridSize': 'cambiar la cuadrícula a {tam}',
  'undo.saveProfile': 'guardar perfil "{nombre}"',
  'undo.updateProfile': 'sobrescribir perfil "{nombre}"',
  'undo.deleteProfile': 'eliminar perfil "{nombre}"',
  'bulk.selected': '{n} SELECCIONADOS',
  'bulk.copy': '⎘ COPIAR',
  'bulk.partial': 'Solo cupieron {n} de {total}: la página de destino se quedó sin huecos libres.',
  'icons.count': '{n} iconos · Dot-matrix 17×17 · Pase el cursor por encima para animarlos',
  'rgb.uncalibrated': '{n} zonas ARGB sin tamaño guardado.',
};
