import type { Dict } from './tipos';

/**
 * Fragmento del diccionario espanol: catalogo de tipos de accion, errores y etiquetas.
 *
 * Se fusiona en `es.ts`. Las claves son estables (no el texto).
 */
export const ES_ACCIONES: Dict = {
  // — Tipos de acción (selector del editor) —
  'act.none.label': 'Ninguno', 'act.none.desc': 'Sin acción asignada',
  'act.app.label': 'Abrir App', 'act.app.desc': 'Ejecuta una aplicación',
  'act.web.label': 'Página Web', 'act.web.desc': 'Abre una URL en el navegador',
  'act.shortcut.label': 'Acceso Dir.', 'act.shortcut.desc': 'Abre un archivo o carpeta',
  'act.script.label': 'Script', 'act.script.desc': 'Ejecuta PowerShell o CMD',
  'act.audio-device.label': 'Audio', 'act.audio-device.desc': 'Cambia dispositivo de salida',
  'act.hotkey.label': 'Atajo', 'act.hotkey.desc': 'Envía combinación de teclas',
  'act.clipboard.label': 'Portapapeles', 'act.clipboard.desc': 'Copia texto al portapapeles',
  'act.type-text.label': 'Escribir', 'act.type-text.desc': 'Escribe texto automáticamente',
  'act.kill-process.label': 'Cerrar App', 'act.kill-process.desc': 'Termina un proceso por nombre',
  'act.volume-set.label': 'Vol. Exacto', 'act.volume-set.desc': 'Establece volumen a un % exacto',
  'act.folder.label': 'Carpeta', 'act.folder.desc': 'Abre un sub-deck de botones',
  'act.media-play-pause.label': 'Play/Pausa', 'act.media-play-pause.desc': 'Reproducir / Pausar',
  'act.media-next.label': 'Siguiente', 'act.media-next.desc': 'Siguiente pista',
  'act.media-prev.label': 'Anterior', 'act.media-prev.desc': 'Pista anterior',
  'act.volume-up.label': 'Vol. ＋', 'act.volume-up.desc': 'Sube el volumen',
  'act.volume-down.label': 'Vol. −', 'act.volume-down.desc': 'Baja el volumen',
  'act.mute.label': 'Silenciar', 'act.mute.desc': 'Silencia / activa sonido',
  'act.brightness.label': 'Brillo', 'act.brightness.desc': 'Controla brillo del monitor',
  'act.notify.label': 'Notificación', 'act.notify.desc': 'Muestra una notificación de Windows',
  'act.set-var.label': 'Var: Asignar', 'act.set-var.desc': 'Asigna valor a una variable global',
  'act.incr-var.label': 'Var: Sumar', 'act.incr-var.desc': 'Incrementa o decrementa una variable numérica',
  'act.webhook.label': 'Webhook', 'act.webhook.desc': 'POST/GET a una URL con body y headers',
  'act.tts.label': 'Texto-a-voz', 'act.tts.desc': 'Lee un texto en voz alta',
  'act.region-capture.label': 'Captura', 'act.region-capture.desc': 'Abre la captura de región de Windows',
  'act.rgb-color.label': 'RGB Color', 'act.rgb-color.desc': 'Pinta un color sólido en un dispositivo RGB',
  'act.rgb-mode.label': 'RGB Modo', 'act.rgb-mode.desc': 'Cambia el modo/efecto RGB (Direct, Breathing, etc.)',
  'act.rgb-profile.label': 'RGB Perfil', 'act.rgb-profile.desc': 'Aplica un perfil RGB guardado',
  'act.rgb-preset.label': 'RGB Preset', 'act.rgb-preset.desc': 'Aplica uno de los 18 ambientes prehechos (Gaming, Cine, Trabajo…)',
  'act.window-snap.label': 'Snap Ventana', 'act.window-snap.desc': 'Mueve y redimensiona una ventana a un cuadrante',
  'act.branch.label': 'Si / Si no', 'act.branch.desc': 'Ejecuta acción A o B según el valor de una variable',
  'act.countdown.label': 'Temporizador', 'act.countdown.desc': 'Espera N ms y luego ejecuta una acción',
  'act.media-shuffle.label': 'Shuffle', 'act.media-shuffle.desc': 'Alterna shuffle en el reproductor activo (SMTC)',
  'act.media-repeat.label': 'Repetir', 'act.media-repeat.desc': 'Cicla el modo de repetición (ninguno → lista → pista)',
  'act.macro.label': 'Macro', 'act.macro.desc': 'Secuencia de teclas y clics de ratón grabada o configurada',
  // ── Errores y etiquetas de acciones ──
  'act.err.sinManejador': 'La acción "{tipo}" no está implementada.',
  'act.err.noAppPath': 'Falta la ruta del programa.',
  'act.err.launch': 'No se pudo iniciar: {que}. Compruebe la ruta.',
  'act.err.noUrl': 'Falta la URL.',
  'act.err.openUrl': 'No se pudo abrir: {url}',
  'act.err.noShortcut': 'Falta el acceso directo.',
  'act.err.shortcut': 'No se pudo abrir el acceso directo.',
  'act.err.noDevice': 'Falta el dispositivo de audio.',
  'act.err.deviceNotFound': 'No se encontró el dispositivo "{name}". Compruebe el nombre en Configuración → Sonido.',
  'act.err.switchAudio': 'No se pudo cambiar el audio a "{name}".',
  'act.err.noHotkey': 'Falta la combinación de teclas.',
  'act.err.hotkey': 'No se pudo enviar el atajo {hotkey}.',
  'act.err.noBrightness': 'Falta el nivel de brillo.',
  'act.err.brightness': 'No se pudo ajustar el brillo (¿monitor sin soporte WMI?).',
  'act.err.noClipText': 'Falta el texto a copiar.',
  'act.err.clipboard': 'No se pudo copiar al portapapeles.',
  'act.err.noTypeText': 'Falta el texto a escribir.',
  'act.err.type': 'No se pudo escribir el texto.',
  'act.err.noProcess': 'Falta el nombre del proceso.',
  'act.err.kill': 'No se pudo cerrar "{name}". ¿Está en ejecución?',
  'act.err.noVolume': 'Falta el nivel de volumen.',
  'act.err.volume': 'No se pudo ajustar el volumen.',
  'act.err.notify': 'No se pudo mostrar la notificación.',
  'act.err.media': 'No se pudo enviar el control de media ({cmd}).',
  'act.err.shuffle': 'No se pudo alternar la reproducción aleatoria (¿hay algún reproductor activo?).',
  'act.err.repeat': 'No se pudo cambiar el modo de repetición.',
  'act.err.macroEmpty': 'La macro no tiene pasos.',
  'act.err.mediaKey': 'No se pudo enviar la tecla multimedia ({tipo}).',
  'act.err.noVar': 'Falta nombre de variable.',
  'act.err.noWebhookUrl': 'Falta la URL del webhook.',
  'act.err.headers': 'Headers inválidos (JSON malformado).',
  'act.err.webhookStatus': 'Webhook {method} {url} → {status} {statusText}',
  'act.err.webhook': 'Webhook falló: {msg}',
  'act.err.noTtsText': 'Falta el texto a leer.',
  'act.err.tts': 'No se pudo reproducir el texto en voz alta.',
  'act.err.capture': 'No se pudo abrir la herramienta de captura.',
  'act.err.noRgbColor': 'Falta el color RGB.',
  'act.err.rgbColor': 'No se pudo aplicar el color RGB (¿OpenRGB conectado?).',
  'act.err.noRgbMode': 'Falta el modo RGB.',
  'act.err.rgbMode': 'No se pudo aplicar el modo "{modo}".',
  'act.err.noRgbProfile': 'Falta el nombre del perfil RGB.',
  'act.err.rgbProfileMissing': 'Perfil RGB "{name}" no existe.',
  'act.err.rgbProfile': 'No se pudo aplicar el perfil RGB.',
  'act.err.noRgbPreset': 'Falta el ID del preset RGB.',
  'act.err.rgbPreset': 'No se pudo aplicar el preset "{id}" (¿OpenRGB conectado?).',
  'act.err.noSnap': 'Falta la posición de snap.',
  'act.err.snap': 'No se pudo ajustar la ventana (¿no se encontró el proceso?).',
  'act.err.unexpected': 'Error inesperado en {que}: {msg}',
  'act.err.script': 'El script terminó con error.',
  'act.err.macro': 'La macro falló.',
  'act.err.countdown': 'Countdown sub-acción falló.',
  'act.lbl.app': 'App',
  'act.lbl.web': 'Abrir URL',
  'act.lbl.shortcut': 'Acceso directo',
  'act.lbl.audio': 'Cambiar audio',
  'act.lbl.hotkey': 'Atajo',
  'act.lbl.clipboard': 'Copiar al portapapeles',
  'act.lbl.type': 'Escribir texto',
  'act.lbl.kill': 'Cerrar proceso',
  'act.lbl.notify': 'Notificación',
  'act.lbl.webhook': 'Webhook',
  'act.lbl.tts': 'Texto-a-voz',
  'act.lbl.capture': 'Captura de región',
  'act.lbl.rgbColor': 'RGB color',
  'act.lbl.rgbMode': 'RGB modo',
  'act.lbl.rgbProfile': 'RGB perfil',
  'act.lbl.rgbPreset': 'RGB preset',
  'act.lbl.snap': 'Window snap',
  'act.lbl.shuffle': 'Toggle shuffle',
  'act.lbl.repeat': 'Ciclar repetición',
  'act.lbl.open': 'Abrir',
  'act.lbl.brightness': 'Brillo',
  'act.lbl.volume': 'Volumen',
  'act.lbl.macro': 'Macro ({n} pasos)',
  'act.err.timeout': 'La acción superó los 60 s y se considera bloqueada.',
  'cat.APPS': 'APPS',
  'cat.WEB': 'WEB',
  'cat.MEDIA': 'MEDIA',
  'cat.SISTEMA': 'SISTEMA',
  'cat.CREATIVO': 'CREATIVO',
  'cat.RGB': 'RGB',
  'act.err.noDelta': 'El botón de ajuste no tiene cuánto subir o bajar.',
  'act.err.noReadBrightness': 'No se pudo leer el brillo actual. Un monitor externo suele no exponerlo.',
  'act.err.noReadVolume': 'No se pudo leer el volumen actual.',
  'act.adjust.label': 'Subir / Bajar',
  'act.adjust.desc': 'Sube o baja el brillo o el volumen desde donde esté',
  'act.err.noRemoteHost': 'Falta el equipo al que mandar.',
  'act.err.noRemoteToken': 'Falta el token del otro equipo.',
  'act.err.remote': 'El otro equipo no acepto la orden: {error}',
  'act.remote.label': 'Deck remoto (otra PC)',
  'act.remote.desc': 'Pulsa un botón de otro VirtualDeck en la red local',
  'act.mobile-remote.label': 'Mando móvil',
  'act.mobile-remote.desc': 'Genera código de emparejamiento o activa el servidor web',
  'act.err.mobileCode': 'No se pudo generar el código de emparejamiento.',
  'act.mobile.pairCodeToast': 'Código de vinculación: {code} (copiado al portapapeles, válido 5 min)',
  'act.mobile.serverStarted': 'Servidor de mando móvil iniciado en el puerto {port}',
  'act.mobile.serverStopped': 'Servidor de mando móvil detenido',
  // 5.0 — Integraciones de terceros (Discord & Spotify)
  'act.discord.label': 'Discord',
  'act.discord.desc': 'Control de voz en Discord: silenciar micrófono o ensordecer vía Named Pipe local',
  'act.spotify.label': 'Spotify',
  'act.spotify.desc': 'Reproduce playlists, canciones o álbumes directamente en Spotify o transfiere reproducción',
  'act.err.discord': 'No se pudo comunicar con Discord. Compruebe que esté abierto.',
  'act.err.spotifyNoUri': 'Debes indicar una URI o enlace de Spotify a reproducir.',
  'act.err.spotifyNoDevice': 'Debes indicar el ID del dispositivo de Spotify.',
  'act.err.spotify': 'No se pudo reproducir en Spotify.',
};
