import type { Dict } from './tipos';

/**
 * Fragmento del diccionario espanol: panel de ajustes, sensores, RGB, galeria e integraciones.
 *
 * Se fusiona en `es.ts`. Las claves son estables (no el texto).
 */
export const ES_AJUSTES: Dict = {

  // ── Gestor RGB ──
  'rgb.connFailed': 'Conexión falló: {err}',
  'rgb.connFailedNoServer': 'Conexión falló (¿está activo el servidor de OpenRGB?)',
  'rgb.profilePartial': 'Algunos dispositivos no aceptaron el perfil.',
  'rgb.resizeFailed': 'No se pudo redimensionar la zona.',
  'rgb.disconnect': 'DESCONECTAR',
  'rgb.connect': 'CONECTAR',
  'rgb.rescan': 'Reescanear dispositivos',
  'rgb.notConnected': 'NO CONECTADO',
  'rgb.setPath': '· Configure la ruta de OpenRGB.exe en el panel de ajustes (botón de ajustes de la pantalla principal → sección RGB).',
  'rgb.serverHint': '· Asegúrese de que el servidor SDK esté activo (puerto {port}). VirtualDeck inicia OpenRGB en modo --server, sin interfaz, de modo que no aparece el diálogo de tamaño de zonas.',
  'rgb.lastError': 'Último error: {err}',
  'rgb.devices': 'DISPOSITIVOS',
  'rgb.noDevices': 'Ningún dispositivo detectado.',
  'rgb.connectToSee': 'Conecte para ver los dispositivos.',
  'rgb.quickActions': 'ACCIONES RÁPIDAS',
  'rgb.allOff': 'APAGAR TODO',
  'rgb.allWhite': 'BLANCO TOTAL',
  'rgb.accentColor': 'COLOR ACENTO',
  'rgb.profiles': 'PERFILES RGB',
  'rgb.presets': 'PRESETS',
  'rgb.noProfiles': 'Sin perfiles aún.',
  'rgb.apply': 'APLICAR',
  'rgb.save': 'GUARDAR',
  'rgb.newProfile': 'Nuevo perfil...',
  'rgb.connected': 'CONECTADO · {n} DISP',
  'rgb.serverUp': 'SERVIDOR ACTIVO',
  'rgb.disconnected': 'DESCONECTADO',
  'rgb.deviceOne': 'DISPOSITIVO',
  'rgb.deviceMany': 'DISPOSITIVOS',
  'rgb.color': 'COLOR',
  'rgb.mode': 'MODO',
  'rgb.speed': 'VELOCIDAD · {n}%',
  'rgb.zones': 'ZONAS',
  'rgb.zoneLeds': '{n} LEDS',
  'rgb.zoneResizable': ' · {min}-{max} REDIM.',
  'rgb.paintLeds': 'PINTAR LEDs INDIVIDUALES',
  'rgb.hide': 'OCULTAR',
  'rgb.show': 'MOSTRAR',
  'rgb.noLeds': 'No hay LEDs reportados para este dispositivo.',
  'rgb.notPerLed': 'El modo actual ({mode}) no es por LED. Cambie a Direct o Custom para que los cambios sean visibles.',
  'rgb.ledsHint': '{n} LED · Clic para pintar con el color seleccionado',
  'rgb.calibrator': 'CALIBRADOR DE ZONAS ARGB',
  'rgb.calibratorHelp': 'Para cada zona redimensionable: pulse IDENTIFICAR para que un LED se encienda en blanco recorriendo toda la cadena. Cuente cuántos LED ha visto y guarde ese número. Esto sustituye al diálogo de OpenRGB y se conserva en la configuración local.',
  'rgb.noResizable': 'No hay zonas redimensionables detectadas.',
  'rgb.range': 'RANGO {min}–{max} · ACTUAL {cur}',
  'rgb.saved': ' · GUARDADO {n}',
  'rgb.suggestion': '◆ Sugerencia: {note}',
  'rgb.identify': 'IDENTIFICAR',
  'rgb.hint.unifan': 'Lian Li UNI Fan SL (16 LEDs por ventilador)',
  'rgb.hint.strimer24': 'Strimer Plus 24-pin',
  'rgb.hint.strimer8': 'Strimer Plus 8-pin',
  'rgb.hint.argb': 'Cabezal ARGB genérico (estimado)',
  'set.noProfiles': 'Sin perfiles guardados.',
  'rgb.pickDevice': 'Seleccione un dispositivo en la lista de la izquierda.',
  'set.appearance': 'ASPECTO Y TEMA',
  'set.system': 'SISTEMA Y VENTANA',
  'set.accent': 'COLOR DE ACENTO',
  'set.scale': 'ESCALA DE INTERFAZ',
  'set.tiles': 'FORMA DE LAS CELDAS',
  'set.chime': 'TIMBRE',
  'set.profiles': 'PERFILES',
  'set.sound': 'SONIDO AL PULSAR',
  'set.profileName': 'Nombre del perfil...',
  'set.rgb': 'RGB (OPENRGB)',
  'set.rgbPath': 'RUTA OPENRGB.EXE',
  'set.enabled': 'HABILITADO',
  'set.rgbSpawn': 'LANZAR OPENRGB AL ARRANCAR',
  'set.rgbAuto': 'AUTOCONECTAR',
  'set.gallery': 'GALERIA DE PERFILES',
  'gal.load': 'CARGAR',
  'gal.loading': 'CARGANDO...',
  'gal.hint': 'La galeria del proyecto se abre con el boton de arriba. Tambien sirve cualquier otra que usted o alguien de confianza aloje: pegue la direccion de su manifest.json. En los dos casos se le ensena antes lo que el perfil ejecutara.',
  'gal.official': 'GALERIA DEL PROYECTO',
  'gal.failed': 'No se pudo cargar: {error}',
  'gal.empty': 'Ese manifiesto no trae ningun perfil valido.',
  'gal.notADeck': 'Ese archivo no parece un deck: le faltan las paginas o los botones.',
  'gal.unknownTypes': 'Este perfil usa acciones que esta version no conoce ({tipos}). Sus botones no harian nada. Actualice VirtualDeck o pida al autor un perfil compatible.',
  'gal.warn': 'Un perfil no son solo datos. Lo que aparece abajo se ejecutara en su equipo cuando pulse esos botones. Reviselo antes de importar.',
  'gal.counts': 'Trae {n} botones.',
  'gal.launches': 'Abre estos programas o archivos:',
  'gal.runs': 'Ejecuta estos scripts:',
  'gal.sends': 'Manda datos a estas direcciones al pulsar:',
  'gal.types': 'Teclea o pulsa esto en su equipo (teclear tambien es ejecutar):',
  'gal.hotkeys': 'Registra estos atajos globales: {list}',
  'gal.nothingRisky': 'No lanza programas ni ejecuta scripts.',
  'gal.import': 'IMPORTAR COMO PERFIL',
  'gal.importAndAppend': '+ AGREGAR AL DECK (NUEVA PÁGINA)',
  'gal.importAndAppendHint': 'Crea una página nueva con estos botones sin borrar el deck actual.',
  'gal.importOnly': 'GUARDAR EN PERFILES',
  'gal.importOnlyHint': 'Solo lo guarda en la lista de perfiles guardados para usarlo después.',
  'gal.kind.page': 'PÁGINA',
  'gal.kind.profile': 'PERFIL',
  'gal.requires': 'Requiere: ',
  'gal.addPage': '+ AGREGAR PÁGINA',
  'gal.addPageHint': 'Crea una página nueva con estos botones sin borrar el deck actual.',
  'gal.notAPage': 'Ese archivo no es una página suelta de VirtualDeck (falta page o buttons).',
  'gal.hotkeysStripped': 'Página agregada. Se quitaron {n} atajos globales que chocaban con los suyos.',
  'gal.needsUpdate': 'Ese contenido pide VirtualDeck {version} o posterior. Actualice la app para instalarlo.',
  'gal.auto': 'Se ejecuta solo, sin pulsar:',
  'gal.integrations': 'Otros efectos al pulsar:',
  'set.remote': 'MANDO MÓVIL Y SERVIDOR WEB',
  'set.remoteStep1': '1. Abre esta dirección en el navegador de tu móvil:',
  'set.remoteWifiHint': 'Tu móvil y este PC deben estar conectados a la misma red Wi-Fi.',
  'set.remoteStep2': '2. Código de vinculación:',
  'set.remotePairCodeHint': 'Escribe este código de 6 dígitos en la pantalla del móvil. Caduca en {min} min.',
  'set.remoteAdvanced': 'Ajustes avanzados y API',
  'set.remoteLocalOnly': 'Solo responder a este equipo (desactivar Wi-Fi)',
  'set.remoteToken': 'TOKEN',
  'set.remoteTokenHint': 'Pulse para ver u ocultar el token.',
  'set.remoteNewToken': 'NUEVO TOKEN',
  'set.remoteCopyToken': 'COPIAR',
  'set.remotePair': 'OBTENER CÓDIGO',
  'set.remotePairHint': 'En el teléfono, abra {url} y escriba el código. Caduca en {min} min.',
  'set.remotePairNeedsLan': 'Para que el teléfono llegue hace falta activar PERMITIR LA RED LOCAL.',
  'set.remoteLan': 'PERMITIR LA RED LOCAL',
  'set.remoteLanWarn': 'Sin activar, solo responde a este equipo. Activado, cualquiera en su red que tenga el token puede pulsar botones, incluidos los que ejecutan scripts. La conexión no va cifrada.',
  'set.remoteListening': 'Escuchando en {url}',
  'set.remoteStopped': 'Detenido.',
  'set.remoteCopyUrl': 'COPIAR ENLACE',
  'set.remoteMdns': 'O por nombre de red (mDNS): {url}',
  'set.remoteFirewallOk': 'Firewall de Windows: Regla activa (puerto {port})',
  'set.remoteFirewallWarn': 'Firewall de Windows: El puerto {port} podría estar bloqueado en la red local.',
  'set.remoteFirewallBtn': 'ABRIR EN FIREWALL',
  'set.remoteFirewallOpening': 'CONFIGURANDO...',
  'set.remoteFirewallDone': 'Regla creada en el Firewall de Windows.',
  'set.remoteFirewallFailed': 'No se pudo crear la regla: {error}',
  'set.remoteHint': 'El token va en la cabecera X-VD-Token, no en la dirección. Rutas: /api/ping, /api/buttons, /api/press/<id>, /api/press?label=<etiqueta>, /api/page/<n>.',
  'set.musicPanel': 'PANEL DE MUSICA',
  'set.musicPanelHint': 'Aparece al lado de la cuadricula solo cuando hay algo sonando, con la caratula grande y botones pensados para el dedo.',
  'set.sensors': 'SENSORES (LIBRE HARDWARE MONITOR)',
  'set.lhmPath': 'RUTA DE LHM (vacío = se busca sola)',
  'sensors.catOther': 'OTROS',
  'set.categories': 'CATEGORÍAS VISIBLES',
  'set.sensorWidget': 'MOSTRAR WIDGET DE SENSORES',
  'set.lhmStart': 'INICIAR LHM CON VIRTUALDECK',
  'set.lhmAdmin': 'INICIAR LHM COMO ADMINISTRADOR (UAC)',
  'set.urlAcl': 'Registra una reserva URL ACL en Windows (una sola confirmación de UAC). Después LHM puede ejecutarse sin permisos de administrador.',
  'rgb.calibPending': 'CALIBRACIÓN PENDIENTE',
  'rgb.pickProfile': '— Elija un perfil —',
  'rgb.startupOn': 'Se aplica al abrir VirtualDeck; haga clic para quitarlo',
  'rgb.startupOff': 'Aplicar este perfil al abrir VirtualDeck',
  'rgb.startupHint': 'Marcado = se aplica solo al abrir VirtualDeck.',
  'rgb.spawnFailed': 'Spawn falló: {error}',
  'rgb.connectFailed': 'Falló: {error}',
  'rgb.noServer': 'sin server',
  'rgb.okDevices': 'OK · {n} dispositivos',
  'rgb.testing': 'PROBANDO...',
  'rgb.test': 'PROBAR CONEXIÓN',
  'rgb.profileSaved': 'Perfil "{nombre}" guardado.',
  'rgb.profileUpdated': 'Perfil "{nombre}" sobrescrito.',
  'rgb.calibrate': 'CALIBRAR',
  'rgb.zoneCount': '{n} ZONA',
  'rgb.zoneCountN': '{n} ZONAS',
  'rgb.ledCount': '{n} LEDS',
  'sensors.lhmFailed': 'Falló al iniciar LHM: {error}',
  'sensors.unknown': 'desconocido',
  'sensors.okCount': 'OK · {n} sensores',
  'sensors.noWebServer': 'El servidor web no responde tras 12 s: {error}. Pruebe a ejecutar VirtualDeck como administrador.',
  'sensors.aclOk': 'Reserva URL ACL registrada: {url}. LHM ya no necesita permisos de administrador.',
  'sensors.aclFailed': 'Falló registro URL ACL: {error}',
  'sensors.noReply': 'sin respuesta',
  'sensors.connectedCount': '{n} SENSORES CONECTADOS',
  'sensors.enabledNoConn': 'HABILITADO · SIN CONEXIÓN',
  'sensors.disabledDot': 'DESHABILITADO',
  'sensors.noData': 'Sin datos. Compruebe que LibreHardwareMonitor esté en ejecución.',
  'sensors.offHint': 'Sensores deshabilitados. Configure LHM desde la barra de título.',
  'sensors.testing': 'PROBANDO...',
  'sensors.test': 'PROBAR',
  'sensors.lhmStart': 'INICIAR LHM',
  'sensors.lhmStarting': 'INICIANDO...',
  'sensors.lhmRunning': 'LHM ACTIVO',
  'sensors.lhmStop': 'DETENER LHM',
  'sensors.lhmMissing': 'LibreHardwareMonitor no está instalado. Descárguelo, ábralo y active Options → Remote Web Server → Run, con el puerto 8085.',
  'sensors.lhmDownload': 'Descargar LHM',
  'sensors.lhmFound': 'Detectado en {ruta}',
  'set.tablet': 'PANTALLA TÁCTIL',
  'set.tabletOpen': 'CONFIGURAR PANTALLA TÁCTIL',
  'set.tabletHelp': 'Abre la herramienta de Windows donde se indica cuál de los monitores responde al tacto. Pulse «Configurar» y siga las instrucciones en la pantalla que vaya a usar.',
  'set.tabletFailed': 'No se pudo abrir. Es posible que este equipo no tenga pantalla táctil.',
  'sensors.registering': 'REGISTRANDO...',
  'sensors.registerAcl': 'REGISTRAR URL ACL',
  'sensors.hostHint0000': '0.0.0.0 significa "escuchar en toda la red". Para conectar VirtualDeck en este mismo equipo, usa 127.0.0.1.',
  'sensors.adminHint': 'LHM se instala aparte, igual que OpenRGB. Algunos sensores, como los de CPU o SMBus, requieren permisos de administrador: si faltan datos, abra LibreHardwareMonitor como administrador.',
  'sound.click': 'Click mecánico',
  'sound.tick': 'Tick',
  'sound.thud': 'Thud',
  'sound.off': 'Silencio',
  'rgb.preset.off': 'APAGADO',
  'rgb.preset.gaming': 'GAMING',
  'rgb.preset.cinema': 'CINE',
  'rgb.preset.work': 'TRABAJO',
  'rgb.preset.rainbow': 'ARCOÍRIS',
  'rgb.preset.night-blue': 'AZUL NOCHE',
  'rgb.preset.alert-red': 'ALERTA ROJA',
  'rgb.preset.reading': 'LECTURA',
  'rgb.preset.focus': 'CONCENTRACIÓN',
  'rgb.preset.dim': 'TENUE',
  'rgb.preset.sunset': 'ATARDECER',
  'rgb.preset.ocean': 'OCÉANO',
  'rgb.preset.forest': 'BOSQUE',
  'rgb.preset.candle': 'VELA',
  'rgb.preset.violet': 'VIOLETA',
  'rgb.preset.party': 'FIESTA',
  'rgb.preset.wave': 'OLA',
  'rgb.preset.strobe': 'ESTROBO',
  'rgb.uncalibrated': '{n} zonas ARGB sin tamaño guardado.',
  'set.support': 'APOYAR EL PROYECTO',
  'set.autoProfiles': 'PERFILES Y PÁGINAS AUTOMÁTICAS',
  'set.autoProfileSwitch': 'CAMBIO AUTOMÁTICO POR VENTANA',
  'set.autoProfileRestoreDefault': 'VOLVER A PÁGINA 1 SI NO COINCIDE',
  'set.autoProfileHint': 'Cambia automáticamente a la página o perfil vinculado cuando la ventana pase al primer plano en Windows.',
  'set.profileTargetApp': 'App vinculada (ej. obs64)',
  'set.monitors': 'MONITORES Y MULTI-PANTALLA',
  'set.monRefresh': 'Actualizar lista de monitores',
  'set.monRefreshShort': 'ACTUALIZAR',
  'set.monPrimary': 'PRIMARIO',
  'set.monCurrent': 'ACTUAL',
  'set.monKioskTarget': 'KIOSKO',
  'set.monTouch': 'TÁCTIL',
  'set.monMoveHere': 'Mover ventana aquí',
  'set.monSetKiosk': 'Fijar para kiosko',
  'set.monIsKioskTarget': 'Monitor de kiosko',
  'set.monNoDisplays': 'No se detectaron monitores adicionales.',
  'set.monitorsHint': 'VirtualDeck detecta en caliente pantallas conectadas y desconectadas. Puedes enviar la ventana a una pantalla secundaria o fijar en cuál debe abrirse el modo pantalla completa / kiosko.',
  'set.monSwitchQuick': 'Monitor {current} de {total} (clic para alternar)',
  'spotify.tokenRequired': 'Se requiere token de acceso para esta operación',
};
