import type { Dict } from './tipos';

/**
 * Fragmento del diccionario espanol: catálogo de iconos (roadmap T-REV-09).
 *
 * `icat.<slug>` traduce las 41 categorías de Tabler (el slug es el título en
 * minúsculas con guiones). `ialias.<etiqueta>` da palabras españolas (con y
 * sin tilde) para las etiquetas inglesas más útiles en un deck, de modo que
 * buscar "música" o "papelera" encuentre iconos.
 *
 * Se fusiona en `es.ts`. Las claves son estables (no el texto).
 */
export const ES_CATALOGO: Dict = {
  // ── Categorías de Tabler ──
  'icat.animals': 'Animales',
  'icat.arrows': 'Flechas',
  'icat.badges': 'Insignias',
  'icat.brand': 'Marcas',
  'icat.buildings': 'Edificios',
  'icat.charts': 'Gráficos',
  'icat.communication': 'Comunicación',
  'icat.computers': 'Computadoras',
  'icat.currencies': 'Monedas',
  'icat.database': 'Bases de datos',
  'icat.design': 'Diseño',
  'icat.development': 'Desarrollo',
  'icat.devices': 'Dispositivos',
  'icat.document': 'Documentos',
  'icat.e-commerce': 'Comercio electrónico',
  'icat.electrical': 'Electricidad',
  'icat.extensions': 'Extensiones',
  'icat.food': 'Comida',
  'icat.games': 'Juegos',
  'icat.gender': 'Género',
  'icat.gestures': 'Gestos',
  'icat.health': 'Salud',
  'icat.laundry': 'Lavandería',
  'icat.letters': 'Letras',
  'icat.logic': 'Lógica',
  'icat.map': 'Mapas',
  'icat.math': 'Matemáticas',
  'icat.media': 'Multimedia',
  'icat.mood': 'Estados de ánimo',
  'icat.nature': 'Naturaleza',
  'icat.numbers': 'Números',
  'icat.photography': 'Fotografía',
  'icat.shapes': 'Formas',
  'icat.sport': 'Deportes',
  'icat.symbols': 'Símbolos',
  'icat.system': 'Sistema',
  'icat.text': 'Texto',
  'icat.vehicles': 'Vehículos',
  'icat.version-control': 'Control de versiones',
  'icat.weather': 'Clima',
  'icat.zodiac': 'Zodiaco',
  // ── Alias de búsqueda (etiqueta inglesa → palabras españolas) ──
  'ialias.music': 'música musica canción cancion',
  'ialias.volume': 'volumen',
  'ialias.play': 'reproducir reproducción reproduccion iniciar',
  'ialias.pause': 'pausa pausar',
  'ialias.microphone': 'micrófono microfono',
  'ialias.camera': 'cámara camara foto fotografía fotografia',
  'ialias.video': 'vídeo video',
  'ialias.light': 'luz iluminación iluminacion lámpara lampara',
  'ialias.sun': 'sol',
  'ialias.moon': 'luna',
  'ialias.home': 'casa hogar inicio',
  'ialias.settings': 'ajustes configuración configuracion opciones',
  'ialias.gear': 'engranaje ajustes',
  'ialias.power': 'encendido apagar energía energia',
  'ialias.lock': 'candado bloquear bloqueo',
  'ialias.user': 'usuario persona perfil',
  'ialias.mail': 'correo email',
  'ialias.message': 'mensaje',
  'ialias.chat': 'chat conversación conversacion',
  'ialias.phone': 'teléfono telefono llamada',
  'ialias.calendar': 'calendario fecha',
  'ialias.clock': 'reloj hora',
  'ialias.timer': 'temporizador cronómetro cronometro',
  'ialias.alarm': 'alarma despertador',
  'ialias.folder': 'carpeta',
  'ialias.file': 'archivo fichero documento',
  'ialias.download': 'descarga descargar bajar',
  'ialias.upload': 'subida subir cargar',
  'ialias.cloud': 'nube',
  'ialias.wifi': 'wifi inalámbrico inalambrico red',
  'ialias.bluetooth': 'bluetooth',
  'ialias.battery': 'batería bateria pila',
  'ialias.keyboard': 'teclado',
  'ialias.mouse': 'ratón raton',
  'ialias.monitor': 'monitor pantalla',
  'ialias.game': 'juego videojuego',
  'ialias.gamepad': 'mando juego',
  'ialias.controller': 'mando control',
  'ialias.brush': 'pincel brocha',
  'ialias.paint': 'pintura pintar',
  'ialias.color': 'color',
  'ialias.art': 'arte',
  'ialias.code': 'código codigo programar',
  'ialias.terminal': 'terminal consola',
  'ialias.debug': 'depurar errores',
  'ialias.search': 'buscar búsqueda busqueda lupa',
  'ialias.star': 'estrella favorito',
  'ialias.heart': 'corazón corazon amor',
  'ialias.flag': 'bandera',
  'ialias.trash': 'papelera basura eliminar',
  'ialias.recycle': 'reciclar reciclaje',
  'ialias.delete': 'eliminar borrar suprimir',
  'ialias.remove': 'quitar eliminar',
  'ialias.edit': 'editar',
  'ialias.copy': 'copiar',
  'ialias.cut': 'cortar',
  'ialias.paste': 'pegar',
  'ialias.scissors': 'tijeras cortar',
  'ialias.clipboard': 'portapapeles',
  'ialias.share': 'compartir',
  'ialias.link': 'enlace vínculo vinculo',
  'ialias.window': 'ventana',
  'ialias.layout': 'diseño diseno distribución distribucion',
  'ialias.grid': 'cuadrícula cuadricula',
  'ialias.temperature': 'temperatura',
  'ialias.fan': 'ventilador',
  'ialias.plug': 'enchufe conectar',
  'ialias.zap': 'rayo energía energia',
  'ialias.rocket': 'cohete',
  'ialias.car': 'coche carro auto',
  'ialias.coffee': 'café cafe',
  'ialias.photo': 'foto fotografía fotografia',
  'ialias.image': 'imagen',
  'ialias.picture': 'imagen foto cuadro',
  'ialias.sound': 'sonido',
  'ialias.audio': 'audio sonido',
  'ialias.speaker': 'altavoz bocina',
  'ialias.mute': 'silenciar silencio mudo',
  'ialias.song': 'canción cancion música musica',
  'ialias.movie': 'película pelicula cine',
  'ialias.screen': 'pantalla',
  'ialias.bell': 'campana timbre aviso',
  'ialias.book': 'libro',
  'ialias.print': 'imprimir impresión impresion',
  'ialias.send': 'enviar envío envio',
  'ialias.list': 'lista',
  'ialias.check': 'verificar visto marca',
  'ialias.plus': 'más mas sumar añadir anadir',
  'ialias.arrow': 'flecha',
  'ialias.compass': 'brújula brujula',
  'ialias.pin': 'chincheta marcador',
  'ialias.location': 'ubicación ubicacion lugar',
  'ialias.globe': 'globo mundo terráqueo terraqueo',
  'ialias.map': 'mapa',
  'ialias.route': 'ruta camino',
  'ialias.building': 'edificio',
  'ialias.store': 'tienda guardar',
  'ialias.cart': 'carrito compra',
  'ialias.money': 'dinero',
  'ialias.gift': 'regalo',
  'ialias.food': 'comida alimento',
  'ialias.key': 'llave clave tecla',
  'ialias.shield': 'escudo protección proteccion',
  'ialias.fire': 'fuego incendio',
  'ialias.drop': 'gota',
  'ialias.rain': 'lluvia',
  'ialias.snow': 'nieve',
  'ialias.trophy': 'trofeo premio',
  'ialias.sport': 'deporte',
  'ialias.health': 'salud',
  'ialias.pen': 'bolígrafo boligrafo pluma',
  'ialias.text': 'texto',
  'ialias.server': 'servidor',
  'ialias.database': 'base datos',
  'ialias.sync': 'sincronizar',
  'ialias.refresh': 'actualizar recargar',
  'ialias.chip': 'chip procesador',
  'ialias.processor': 'procesador',
};
