import type { Dict } from './tipos';

/**
 * Fragmento del diccionario espanol: chrome general, paginas, celdas, fondos, ayuda y tutorial.
 *
 * Se fusiona en `es.ts`. Las claves son estables (no el texto).
 */
export const ES_COMUN: Dict = {
  // — Chrome / settings (TitleBar) —
  'comun.eliminar': 'Eliminar',
  'comun.subir': 'Subir',
  'comun.bajar': 'Bajar',
  'comun.editar': 'Editar',
  'comun.moverArriba': 'Mover arriba',
  'comun.moverAbajo': 'Mover abajo',
  'comun.moverIzquierda': 'Mover izquierda',
  'comun.moverDerecha': 'Mover derecha',
  'comun.moverPuntos': 'Mover los puntos',
  'main.log.largo': '{boton} (mantenido)',
  'ed.badge.toggle': 'ALTERNAR',
  'ed.badge.fijo': 'FIJO',
  'bar.menosHuecos': 'Menos huecos',
  'bar.masHuecos': 'Más huecos',
  'settings.theme': 'TEMA',
  'settings.theme.dark': 'OSCURO',
  'settings.theme.light': 'CLARO',
  'settings.theme.system': 'SISTEMA',
  'settings.language': 'IDIOMA',
  'settings.language.system': 'SISTEMA',
  // Los nombres de idioma van cada uno en el suyo en los dos diccionarios:
  // quien busca "English" no lo encuentra bajo "Ingles".
  'settings.language.es': 'ESPAÑOL',
  'settings.language.en': 'ENGLISH',
  'settings.autostart': 'INICIAR CON WINDOWS',
  'settings.alwaysOnTop': 'SIEMPRE VISIBLE',
  // — Acciones de página / barra —
  'main.search.placeholder': 'Etiqueta, app, URL, atajo...',
  'main.search.title': 'BUSCAR BOTÓN',
  'main.search.empty': 'No hay botones configurados',
  'main.search.nomatch': 'Sin coincidencias',
  'main.search.nav': 'NAVEGAR',
  'main.search.edit': 'EDITAR',
  'main.search.exit': 'ESC SALIR',
  // — Update banner —
  'update.ready': 'Actualización {version} lista.',
  'update.restart': 'REINICIAR',
  'update.later': 'DESPUÉS',
  // — Onboarding —
  'onb.step': 'PASO {n} / 0{total}',
  'onb.skip': 'Saltar',
  'onb.back': 'Atrás',
  'onb.next': 'Siguiente',
  'onb.start': 'Empezar',
  'onb.1.title': 'IDIOMA · LANGUAGE',
  'onb.1.body': 'Elija el idioma de la aplicación. El resto del tutorial y toda la interfaz se mostrarán en el idioma que seleccione.',
  'onb.1.hint': 'Con SISTEMA se usa el idioma de Windows. Puede cambiarlo en cualquier momento en AJUSTES → IDIOMA.',
  'onb.2.title': 'APARIENCIA',
  'onb.2.body': 'Elija el tema y el color de acento. Los cambios se aplican al instante, de modo que puede ver el resultado antes de continuar.',
  'onb.2.hint': 'El fondo se elige por separado, con el botón FONDO de la barra superior.',
  'onb.backup.export': 'EXPORTAR',
  'onb.backup.import': 'IMPORTAR',
  'onb.3.title': 'VIRTUALDECK',
  'onb.3.body': 'Su Stream Deck por software. Una cuadrícula de botones que ejecutan acciones: abrir aplicaciones, páginas web y carpetas, cambiar el audio, controlar la música, lanzar atajos, macros y más.',
  'onb.3.hint': 'Todo se guarda solo. No hay nube ni cuentas: es 100% local.',
  'onb.4.title': 'SUS BOTONES',
  'onb.4.body': 'Pulse una celda vacía para crear un botón: el editor lo guía por secciones (PRESETS, ACCIÓN, APARIENCIA, COMPORTAMIENTO y AVANZADO), con catálogo de iconos, dibujo propio o imagen. El lápiz que aparece sobre el botón lo edita después, y el menú contextual (clic derecho) lo duplica o lo vacía.',
  'onb.4.hint': 'Mantener pulsado medio segundo dispara una segunda acción; Ctrl+clic selecciona varios botones.',
  'onb.5.title': 'PÁGINAS Y CUADRÍCULA',
  'onb.5.body': 'Organice sus botones en varias páginas (pestañas superiores). Cambie entre ellas con las teclas 1-9 o deslizando. Cada página puede tener su propio tamaño de cuadrícula.',
  'onb.5.hint': 'Arrastre un botón sobre la pestaña de otra página para moverlo.',
  'onb.6.title': 'WIDGETS Y PANTALLA COMPLETA',
  'onb.6.body': 'Un botón puede mostrar reloj, clima, sensores del equipo, una variable o la música en reproducción. Acceda al modo de pantalla completa para usar VirtualDeck como panel dedicado en una tableta o un monitor secundario.',
  'onb.6.hint': 'El widget de música detecta Spotify, YouTube, navegadores y más.',
  'onb.7.title': 'MÁS ALLÁ DE LA PANTALLA',
  'onb.7.body': 'Los docks físicos se configuran en la pantalla Dispositivos, con una página por aparato. El mando móvil (Ajustes → MANDO MÓVIL) lleva sus botones al teléfono, y la BARRA deja una columna flotante sobre el escritorio.',
  'onb.7.hint': 'Y la TIENDA trae decks de otras personas, listos para importar.',
  'onb.8.title': 'QUE SE DISPARE SOLO',
  'onb.8.body': 'En COMPORTAMIENTO → DISPARADORES EXTERNOS el botón se dispara solo: con un atajo global del sistema, a una hora con días de la semana, o cuando un sensor del equipo cruza un valor.',
  'onb.8.hint': 'También puede aparecer en el menú de la bandeja o mostrarse solo cuando cierta aplicación está activa.',
  'onb.9.title': 'RESPALDO Y AYUDA',
  'onb.9.body': 'Toda su configuración reside en un único archivo local. En Ajustes → PERFILES Y RESPALDO la exporta, la importa o la traslada a otro equipo. Ctrl+K busca cualquier botón al instante, y en Ajustes → Ayuda están la documentación, el informe de errores y este tutorial.',
  'onb.9.hint': 'En una instalación nueva todavía no hay nada que exportar: los botones de abajo están aquí para cuando lo haya. ¿Todo listo? Cree su primer botón.',
  // — Hints contextuales —
  'hint.firstButton': 'Haga clic en una celda vacía para crear su primer botón.',
  'hint.settings': 'El tema, el idioma, la escala y demás opciones están en Configuración.',
  'hint.search': 'Sugerencia: Ctrl+K busca cualquier botón al instante.',
  'hint.dismiss': 'Entendido',
  // — Ayuda y Acerca de —
  'help.title': 'AYUDA Y ACERCA DE',
  'help.docs': 'DOCUMENTACIÓN',
  'help.report': 'REPORTAR ERROR',
  'help.check': 'BUSCAR ACTUALIZACIÓN',
  'help.checking': 'BUSCANDO…',
  'help.donateIntro': 'VirtualDeck es gratuito. Si le resulta útil, puede apoyar su desarrollo:',
  'help.openLog': 'ABRIR REGISTRO',
  'help.exportLog': 'EXPORTAR REGISTRO',
  'help.noLog': 'Todavía no hay registro que exportar: se crea cuando ocurre el primer error.',
  'help.replay': 'REPETIR TUTORIAL',
  'help.credits': 'CRÉDITOS Y LICENCIAS',
  'help.bundled': ' (incluido)',
  'help.upd.ready': 'Actualización {version} lista: reinicie para aplicarla.',
  'help.upd.downloading': 'Descargando actualización {version}…',
  'help.upd.error': 'No se pudo buscar actualizaciones.',
  'help.upd.store': 'Esta copia viene de la Microsoft Store: las actualizaciones las reparte la Store.',
  'help.upd.disabled': 'La actualización automática no está disponible en esta compilación (modo desarrollo).',
  'help.upd.checkError': 'Error al buscar actualizaciones.',
  'help.upd.checking': 'Buscando actualizaciones…',
  // — Tooltips de la barra superior —
  'tip.export': 'Exportar configuración',
  'tip.import': 'Importar configuración',
  'tip.bar': 'Columna de tiles flotante sobre el escritorio',
  'tip.rgb': 'Gestor RGB',
  'tip.settings': 'Configuración',
  'tip.fullscreen': 'Modo pantalla completa',
  'tip.minimize': 'Minimizar',
  'tip.close': 'Cerrar (minimiza a bandeja)',
  'comun.cerrar': 'Cerrar',
  'folder.titulo': 'CARPETA',
  'full.kioskTip': 'Activar modo kiosko (oculta la interfaz; ESC pide el PIN)',
  'set.spotifyActivo': 'ACTIVO',
  'bulk.deseleccionar': 'Quitar la selección',
  'rgb.titulo': 'GESTOR RGB',
  'panel.ocultarRegistro': 'OCULTAR REGISTRO',
  'panel.verRegistro': 'VER REGISTRO',
  // — Pantalla de fondos (WallpaperB) —
  'wp.back': 'VOLVER',
  'wp.preview': 'VISTA PREVIA',
  'wp.select': 'SELECCIONAR FONDO',
  'wp.applied': 'APLICADO',
  'wp.apply': 'APLICAR',
  'wp.selected': 'SELECCIONADO',
  'wp.autosave': 'Los cambios se guardan automáticamente al pulsar Aplicar.',
  'wp.name.solid': 'Sólido',
  'wp.name.gradient': 'Gradiente Azul',
  'wp.name.dotgrid': 'Cuadrícula Dot',
  'wp.name.scanlines': 'Scanlines',
  'wp.name.crt': 'CRT',
  'wp.name.mesh': 'Mesh técnico',
  'wp.name.photo': 'Neón',
  'wp.name.grid-blue': 'Grid Azul',
  'sidebar.hide': 'Ocultar panel lateral',
  'sidebar.show': 'Mostrar panel lateral',
  // ── Barra flotante ──
  'bar.short': 'BARRA',
  'bar.close': 'Cerrar la barra flotante',
  // Las 23 condiciones WMO del widget de clima. Estaban escritas en espanol
  // dentro del propio componente: con la app en ingles el tooltip decia
  // «Parcial. nub.».
  'wx.0': 'Despejado',
  'wx.1': 'Mayorm. desp.',
  'wx.2': 'Parcial. nub.',
  'wx.3': 'Cubierto',
  'wx.45': 'Niebla',
  'wx.48': 'Niebla c/escar.',
  'wx.51': 'Llovizna leve',
  'wx.53': 'Llovizna mod.',
  'wx.55': 'Llovizna fuerte',
  'wx.61': 'Lluvia leve',
  'wx.63': 'Lluvia moderada',
  'wx.65': 'Lluvia fuerte',
  'wx.71': 'Nieve leve',
  'wx.73': 'Nieve moderada',
  'wx.75': 'Nieve fuerte',
  'wx.77': 'Granizo fino',
  'wx.80': 'Chubascos lev.',
  'wx.81': 'Chubascos mod.',
  'wx.82': 'Chubascos fuer.',
  'wx.85': 'Nieve chubascos',
  'wx.95': 'Tormenta',
  'wx.96': 'Tormenta/granizo',
  'wx.99': 'Tormenta fuerte',
  'wx.unknown': 'Desconocido',
  'weather.loading': 'Cargando clima...',
  'panel.noMedia': 'Sin reproducción activa',
  'cell.editShort': 'Editar',
  'cell.quickVolumeSlider': 'Control táctil volumen',
  'cell.quickBrightnessSlider': 'Control táctil brillo',
  'bulk.move': 'MOVER',
  'bulk.clear': 'LIMPIAR',
  'panel.openRgb': 'Abrir Gestor RGB',
  'panel.clearLog': 'Limpiar log',
  'ui.back': 'VOLVER',
  'ui.saveShort': 'GUARDAR',
  // ── Palabras sueltas de interfaz ──
  'ui.none': 'NINGUNO',
  'ui.cancel': 'CANCELAR',
  'ui.clear': 'LIMPIAR',
  'ui.fill': 'RELLENAR',
  'ui.save': 'GUARDAR',
  'ui.port': 'PUERTO',
  'ui.wallpaper': 'FONDO',
  'ui.load': 'CARGAR',
  'ui.appendPages': '+ PÁG',
  'ui.appendPagesHint': 'Agregar botones como página nueva sin reemplazar el deck actual',
  'ui.repeat': 'REPETIR',
  'ui.times': 'VECES',
  'ui.mouseL': 'Izq',
  'ui.mouseR': 'Der',
  'ui.mouseM': 'Med',
  'ui.units': 'UNIDADES',
  'ui.pause': 'PAUSA',
  'full.title': 'VIRTUALDECK · MODO PANTALLA COMPLETA',
  'ui.columns': 'COLUMNAS',
  'page.grid': 'CUADRÍCULA',
  'ui.rows': 'FILAS',
  'ui.moveTo': 'MOVER A...',
  // ── Ajustes, paginas y menus ──
  'undo.duplicate': 'duplicar botón',
  'undo.clear': 'limpiar botón',
  'undo.action': 'DESHACER',
  'undo.addPage': 'agregar página',
  'undo.addSurfacePage': 'agregar la página de {nombre}',
  'undo.bindSurfaceApp': 'vincular la página a "{nombre}"',
  'undo.unbindSurfaceApp': 'desvincular la página "{nombre}"',
  'undo.rotateSurface': 'girar la pantalla a {grados}°',
  'undo.delPage': 'eliminar página',
  'undo.movePage': 'reordenar páginas',
  'undo.importPage': 'importar página',
  'cell.edit': 'Editar botón',
  'cell.duplicate': 'Duplicar',
  'cell.copy': 'Copiar botón',
  'cell.paste': 'Pegar botón',
  'cell.copied': 'Botón copiado al portapapeles',
  'cell.pasted': 'Botón pegado',
  'cell.clear': 'Limpiar botón',
  'cell.unfix': 'Quitar fijo',
  'cell.fix': 'FIJO EN TODAS LAS PÁGINAS',
  'cell.goToPage': 'Ir a su página',
  'cell.fijoAviso': 'BOTÓN FIJO DE {pagina}: SE EDITA EN SU PÁGINA',
  'page.duplicate': 'Duplicar página',
  'undo.paste': 'pegar botón',
  'undo.duplicatePage': 'duplicar página',
  'config.repaired': 'La configuracion tenia partes con la forma dañada ({partes}) y se han reparado para poder abrir. Revise sus paginas y botones; si falta algo, restaure una copia desde Ajustes.',
  'config.damaged': 'No se pudo leer la configuracion: el archivo estaba dañado. Se guardo una copia en {ruta}. Si tenia botones, restaurelos desde Ajustes → Copias de seguridad antes de seguir trabajando.',
  'panel.music': 'MUSICA',
  'music.hide': 'Ocultar el panel',
  'media.unsupported': '{que} — la fuente no lo admite',
  'media.noSkip': '{fuente} no admite pasar de pista en esta reproduccion. Es una limitacion de la aplicacion que suena, no del deck.',
  'media.shuffle': 'ALEATORIO',
  'media.repeat': 'REPETIR',
  'media.shuffle.on': 'Aleatorio: sí',
  'media.shuffle.off': 'Aleatorio: no',
  'media.repeat.off': 'Repetir: no',
  'media.repeat.one': 'Repetir: pista',
  'media.repeat.all': 'Repetir: lista',
  'ui.left': 'IZQUIERDA',
  'ui.right': 'DERECHA',
  'page.noRoom': 'No hay hueco libre en "{pagina}".',
  'page.tip': 'Clic para cambiar · Doble clic para renombrar · Arrastrar para reordenar · Clic derecho para más opciones',
  'page.add': 'Agregar página',
  'page.export': 'Exportar página actual',
  'page.import': 'Importar página desde archivo',
  'page.rename': 'Renombrar',
  'page.delete': 'Eliminar página',
  'media.diagnose': 'Diagnosticar widget de música',
  'panel.weather': 'CLIMA',
  'panel.sensors': 'SENSORES',
  'panel.log': 'LOG',
  'panel.noActivity': 'Sin actividad',
  'panel.playing': 'REPRODUCIENDO',
  'full.clock': 'HORA LOCAL',
  'full.page': 'PÁGINA',
  'full.noMedia': 'SIN REPRODUCCIÓN',
  'weather.none': 'Sin datos de clima',
  'bar.max': 'Caben {n} con este tamaño de casilla',
  'bar.title': 'BARRA FLOTANTE',
  'bar.back': 'VOLVER',
  'bar.enabled': 'MOSTRAR LA BARRA',
  'bar.column': 'COLUMNA',
  'bar.dragHint': 'Arrastre un botón de la derecha hasta un hueco. El mismo botón solo puede aparecer una vez.',
  'bar.remove': 'Quitar de la barra',
  'bar.side': 'LADO DE LA PANTALLA',
  'bar.side.left': 'IZQUIERDA',
  'bar.side.right': 'DERECHA',
  'bar.opacity': 'OPACIDAD · {n}%',
  'bar.tileSize': 'TAMAÑO DE CASILLA · {n} PX',
  'bar.position': 'POSICION',
  'bar.center': 'CENTRAR',
  'bar.available': 'BOTONES CONFIGURADOS',
  'bar.noButtons': 'Todavía no hay botones configurados que arrastrar.',
  'import.rejected': 'Importación rechazada: {motivo}',
  'import.badShape': 'shape inválido',
  'cell.tipEmpty': 'Clic para configurar · Clic derecho para más opciones',
  'cell.tipFilled': '{etiqueta} — clic para ejecutar · Ctrl+clic para seleccionar',
  'settings.tile.square': 'CUADRADAS',
  'settings.tile.fill': 'LLENAR ÁREA',
  'pin.setTitle': 'ESTABLEZCA UN PIN DE 4 DÍGITOS',
  'pin.exitTitle': 'INTRODUZCA EL PIN PARA SALIR',
  'pin.setHelp': 'Se solicita una sola vez para activar el modo kiosko. Se guarda en su configuración.',
  'pin.exitHelp': 'Modo kiosko activo. ESC lo desactiva introduciendo el PIN.',
  'pin.save': 'GUARDAR',
  'pin.confirm': 'CONFIRMAR',
  'media.prev': 'Anterior',
  'media.playPause': 'Play/Pausa',
  'media.next': 'Siguiente',
  'media.playing': 'Reproduciendo',
  'media.paused': 'Pausado',
  'media.diagTitle': 'SMTC diagnóstico:',
  'settings.scaleRange': 'Rango: 75% – 175%',
  'validate.notObject': 'El archivo no contiene un objeto JSON válido.',
  'validate.missingPages': 'Falta el campo "pages" (array).',
  'validate.emptyPages': '"pages" no puede estar vacío.',
  'validate.badPage': 'La página n.º {n} tiene un formato no válido (falta id o name).',
  'validate.missingButtons': 'Falta el campo "buttons" (array).',
  'validate.badButton': 'El botón n.º {n} tiene un formato no válido (falta id, page, label o action).',
  'validate.missingAccent': 'Falta el campo "accent" (color hex).',
  'validate.missingWallpaper': 'Falta el campo "wallpaper".',
  'validate.badProfiles': '"profiles" debe ser un array.',
  'validate.badSound': '"soundOnPress" debe ser booleano.',
  'undo.done': 'Deshecho: {label}',
  'undo.configChange': 'Cambio de configuración',
  'undo.copyBetweenPages': 'copiar entre páginas',
  'undo.moveBetweenPages': 'mover entre páginas',
  'undo.renameTo': 'renombrar a "{nombre}"',
  'undo.loadProfile': 'cargar perfil',
  'page.defaultName': 'PÁGINA {n}',
  'bug.sectionDesc': '## Descripción',
  'bug.descPlaceholder': '<!-- Describa el problema: qué estaba haciendo, qué esperaba y qué ocurrió -->',
  'bug.sectionSteps': '## Pasos para reproducir',
  'bug.sectionEnv': '## Entorno',
  'bug.envUnavailable': '- (no disponible)',
  'bug.sectionLog': '## Registro reciente',
  'bug.logTrimmed': '(Adjunte el registro exportado: botón "Exportar registro" en Ayuda → Acerca de)',
  'full.kioskBadge': 'KIOSKO',
  'full.exit': 'SALIR',
  'page.importRejected': 'Ese archivo no es una página exportada de VirtualDeck.',
  'page.importedName': 'IMPORTADA',
  'undo.clearMany': 'vaciar {n} botones',
  'undo.reorder': 'reordenar botones',
  'undo.edit': 'editar "{nombre}"',
  'undo.knobModes': 'modos de perilla "{nombre}"',
  'undo.gridSize': 'cambiar la cuadrícula a {tam}',
  'undo.saveProfile': 'guardar perfil "{nombre}"',
  'undo.appendProfile': 'agregar páginas de "{nombre}"',
  'undo.appendPage': 'agregar página "{nombre}"',
  'undo.updateProfile': 'sobrescribir perfil "{nombre}"',
  'undo.deleteProfile': 'eliminar perfil "{nombre}"',
  'bulk.selected': '{n} SELECCIONADOS',
  'bulk.selectedOne': '1 SELECCIONADO',
  'bulk.copy': 'COPIAR',
  'bulk.partial': 'Solo cupieron {n} de {total}: la página de destino se quedó sin huecos libres.',
  'icons.count': '{n} iconos · Dot-matrix 17×17 · Pase el cursor por encima para animarlos',
  'help.donateFree': 'Es gratuito y seguirá siéndolo: donar no desbloquea nada.',
  'btn.fijoHint': 'Botón fijo: vive en {pagina}',
  'page.bindApp': 'VINCULAR APLICACIÓN',
  'page.unbindApp': 'DESVINCULAR',
  'page.targetApp': 'APLICACIÓN VINCULADA',
  'page.boundApp': 'Vinculada a',
  'page.bindTitle': 'VINCULAR PÁGINA A APLICACIÓN',
  'page.bindDesc': 'Al pasar la aplicación al primer plano, VirtualDeck cambiará automáticamente a esta página.',
  'page.runningApps': 'APLICACIONES EN EJECUCIÓN',
  'page.customAppPlaceholder': 'Nombre del proceso (ej. obs64, photoshop, code)',
  'page.buscarExe': 'BUSCAR .EXE',
  'page.refrescarApps': 'ACTUALIZAR',
  'page.sinAppsAbiertas': 'NO HAY APLICACIONES CON VENTANA DETECTADAS',
  'page.plantillaDisponible': 'PÁGINA PRECONFIGURADA DISPONIBLE: {nombre}',
  'page.crearPagina': 'CREAR PÁGINA',
  'page.valorActual': 'VALOR ACTUAL',
  'settings.integrations': 'INTEGRACIONES DE TERCEROS',
  'settings.discord.title': 'DISCORD DESKTOP',
  'settings.spotify.title': 'SPOTIFY WEB API',
  'settings.spotify.token': 'TOKEN DE ACCESO WEB API (GLOBAL)',
  'settings.spotify.tokenDesc': 'Permite transferir reproducción y consultar dispositivos activos desde cualquier celda.',
  // — Editor de puntos (un solo editor 5×7 + 17×17) —
  'puntos.titulo': 'EDITOR DE PUNTOS',
  'puntos.glifo': '5×7 MONO',
  'puntos.marca': '17×17',
  'puntos.mono': 'MONOCROMO',
  'puntos.paleta': 'PALETA',
  'puntos.vistaPrevia': 'VISTA PREVIA',
  'puntos.puntos': '{n} PUNTOS',
  'puntos.deshacer': 'DESHACER',
  'puntos.invertir': 'INVERTIR',
  'puntos.espejoH': 'ESPEJO H',
  'puntos.espejoV': 'ESPEJO V',
  'puntos.simbolos': 'SÍMBOLOS',
  'puntos.fuente': 'TIPOGRAFÍA',
  'puntos.cargarLetra': 'Cargar "{ch}"',
  'puntos.vacio': 'Vacío: al guardar se eliminará del botón',
  'puntos.ayudaTrazo': 'CLIC = PINTAR · CLIC DERECHO = BORRAR · ARRASTRAR = TRAZO',
  'puntos.restaurar': 'RESTAURAR ORIGINAL',
  'puntos.colorActivo': 'COLOR ACTIVO',
  'puntos.primario': 'PRINCIPAL',
  'puntos.primarioAyuda': 'Fijar el color activo como principal',
  'puntos.original': 'Original: {hex}',
  'puntos.base': '{letra}: {hex}',
  'puntos.enUso': 'EN USO ({n})',
  'puntos.borrador': 'BORRADOR',
  // — Atajos globales sugeridos (roadmap 96) —
  'hotkey.global.diferencia': 'Este atajo DISPARA el botón desde cualquier sitio; el de la acción es lo que el botón TECLEA.',
  'hotkey.sug.titulo': 'COMBINACIONES SUGERIDAS (SEGURAS EN WINDOWS)',
  'hotkey.sug.ocupadoPor': 'Asignado a: {boton}',
  'hotkey.sug.muteMicro': 'MUTEAR MICRO GLOBAL',
  'hotkey.sug.muteMicroDesc': 'Silenciar micrófono en Discord, OBS o Windows desde cualquier app.',
  'hotkey.sug.deafen': 'ENSORDECER AUDIO',
  'hotkey.sug.deafenDesc': 'Silenciar todo el sonido de salida rápidamente.',
  'hotkey.sug.escenaSig': 'ESCENA SIGUIENTE',
  'hotkey.sug.escenaSigDesc': 'Cambiar a la siguiente escena en OBS o software de streaming.',
  'hotkey.sug.modoConcentracion': 'MODO CONCENTRACIÓN',
  'hotkey.sug.modoConcentracionDesc': 'Pausar notificaciones y organizar el espacio de trabajo.',
  'hotkey.sug.grabarClip': 'GRABAR CLIP',
  'hotkey.sug.grabarClipDesc': 'Guardar repetición instantánea de vídeo en GeForce / OBS.',
  'hotkey.sug.playPause': 'REPRODUCIR / PAUSAR',
  'hotkey.sug.playPauseDesc': 'Controlar la música de fondo sin cambiar de ventana.',
  'hotkey.sug.pistaSig': 'PISTA SIGUIENTE',
  'hotkey.sug.pistaSigDesc': 'Avanzar a la siguiente pista de música.',
  'hotkey.sug.overlayJuego': 'OVERLAY EN JUEGO',
  'hotkey.sug.overlayJuegoDesc': 'Mostrar u ocultar capas informativas sobre el juego.',
  'hotkey.sug.perfilDeck': 'CAMBIAR PERFIL DECK',
  'hotkey.sug.perfilDeckDesc': 'Rotar perfiles o páginas de controles del deck.',
  'hotkey.sug.capturaPantalla': 'CAPTURAR PANTALLA',
  'hotkey.sug.capturaPantallaDesc': 'Tomar captura de pantalla rápida sin menús.',
  'hotkey.sug.modoStream': 'MODO TRANSMISIÓN',
  'hotkey.sug.modoStreamDesc': 'Iniciar o pausar emisión en directo.',
  'hotkey.sug.emergencia': 'BOTÓN DE PÁNICO',
  'hotkey.sug.emergenciaDesc': 'Silenciar audio y minimizar ventanas al instante.',
  'hotkey.sug.accionA': 'AUTOMATIZACIÓN A',
  'hotkey.sug.accionADesc': 'Disparar macro o secuencia auxiliar libre.',
  'hotkey.sug.accionS': 'AUTOMATIZACIÓN B',
  'hotkey.sug.accionSDesc': 'Disparar script o flujo de trabajo auxiliar.',
  'hotkey.sug.accionD': 'DISPARADOR LIBRE 1',
  'hotkey.sug.accionDDesc': 'Atajo global de 4 modificadores sin conflicto de sistema.',
  'hotkey.sug.accionX': 'DISPARADOR LIBRE 2',
  'hotkey.sug.accionXDesc': 'Atajo global libre para invocar el botón desde cualquier app.',
  'hotkey.aviso.reservadaWin': 'La combinación con la tecla Windows está reservada por el sistema.',
};
