import type { Dict } from './tipos';

/**
 * Fragmento del diccionario: pantalla de dispositivos (controladores físicos como el Stream Dock N3).
 *
 * Se fusiona en `es.ts`. Las claves son estables (no el texto).
 */
export const ES_DISPOSITIVOS: Dict = {
  'disp.nav': 'DISP',
  'disp.titulo': 'Dispositivos',
  'disp.volver': 'Atrás',
  'disp.breadcrumb.config': 'Configuración',
  'disp.detectados': 'Dispositivos detectados',
  'disp.conectado': 'Conectado',
  'disp.desconectado': 'Desconectado',
  'disp.sinDispositivos': 'No hay dispositivos configurados',
  'disp.sinDispositivosDesc': 'Conecta un Stream Dock N3 por USB para empezar a usarlo.',
  'disp.resumenN3': '6 teclas LCD (64×64) · 3 botones · 3 perillas',
  'disp.brillo': 'Brillo LCD',
  'disp.serial': 'Nº Serie',
  'disp.pagina': 'Página vinculada',
  'disp.vacio': 'Vacío',
  'disp.tecla': 'Tecla LCD {n}',
  'disp.boton': 'Botón {n}',
  'disp.perilla': 'Perilla {n}',
  'disp.izq': 'Giro izq.',
  'disp.pulsar': 'Pulsar',
  'disp.der': 'Giro der.',
  'disp.editar': 'Editar acción',
  'disp.inspector.titulo': 'Propiedades del control',
  'disp.inspector.tipo': 'Tipo de control',
  'disp.inspector.accion': 'Acción asignada',
  'disp.inspector.sinAccion': 'Sin acción asignada',
  'disp.inspector.ayuda': 'Pulsa cualquier tecla, botón o acción de perilla para editar su acción.',
  'disp.avisoDesconectado': 'Dispositivo desconectado. Puedes configurar sus acciones; se sincronizarán al conectarlo.',
  'disp.avisoSinPagina': 'Este dispositivo aún no tiene página asignada en el deck.',
  'disp.tipo.tecla': 'Pantalla LCD (64×64) con switch',
  'disp.tipo.boton': 'Botón físico mecánico',
  'disp.tipo.perilla': 'Encoder rotativo (3 acciones)',
  'disp.tipo.tira': 'Tira táctil (2 acciones)',
  'disp.experimental': 'Sin verificar',
  'disp.experimentalDesc': 'Este modelo no se ha probado con el hardware real.',
  'disp.rotacion': 'Rotación',
  'disp.rotacionAyuda': 'Si las imágenes salen giradas, cámbielo.',
  'disp.modeloDesconocido': 'Modelo desconocido',
  'disp.modeloDesconocidoDesc': 'No se dispone de la distribución física de este modelo.',
  'disp.tira': 'Tira táctil {n}',
  'disp.deslizarIzq': 'Deslizar izq.',
  'disp.deslizarDer': 'Deslizar der.',
  'disp.resumen.teclas': '{n} teclas LCD',
  'disp.resumen.botones': '{n} botones',
  'disp.resumen.perillas': '{n} perillas',
  'disp.resumen.tiras': '{n} tiras táctiles',
  'disp.paginas': 'Páginas del dispositivo',
  'disp.paginaNueva': 'Nueva página del dispositivo',
  'disp.paginaPredeterminada': 'Predeterminada',
  'disp.paginaEnAparato': 'En el aparato',
  'disp.renombrarPagina': 'Renombrar página',
  'disp.borrarPagina': 'Borrar página',
  'disp.borrarUltima': 'No se puede borrar: es la última página del dispositivo',
  'disp.vincularApp': 'Vincular aplicación',
  'disp.panel.dispositivos': 'Dispositivos',
  'disp.panel.inspector': 'Inspector',
  'disp.cerrar': 'Cerrar',

  // Gestos de controles de dock (roadmap 66)
  'disp.gesto.giroIzq': 'GIRO IZQ',
  'disp.gesto.pulsar': 'PULSAR',
  'disp.gesto.giroDer': 'GIRO DER',
  'disp.gesto.deslizar': 'DESLIZAR IZQ/DER',
  'disp.gesto.deslizarIzq': 'DESLIZAR IZQ',
  'disp.gesto.deslizarDer': 'DESLIZAR DER',

  // Inspector de controles (roadmap 66)
  'disp.inspector.otrosGestos': 'Otros gestos de la perilla',

  // Descripciones de acciones para controles de dock (roadmap 66)
  'disp.desc.sinAccion': 'SIN ACCIÓN',
  'disp.desc.mute': 'SILENCIAR AUDIO',
  'disp.desc.mediaNext': 'SIGUIENTE PISTA',
  'disp.desc.mediaPrev': 'PISTA ANTERIOR',
  'disp.desc.mediaPlayPause': 'REPRODUCIR / PAUSAR',
  'disp.desc.bajarVolumen': 'BAJAR VOLUMEN {n} %',
  'disp.desc.subirVolumen': 'SUBIR VOLUMEN {n} %',
  'disp.desc.volumen': 'VOLUMEN',
  'disp.desc.bajarBrillo': 'BAJAR BRILLO {n} %',
  'disp.desc.subirBrillo': 'SUBIR BRILLO {n} %',
  'disp.desc.brillo': 'BRILLO',
  'disp.desc.fijarBrillo': 'FIJAR BRILLO {n} %',
  'disp.desc.ajustarGenerico': 'AJUSTAR {target} {delta}',
  'disp.desc.discordMute': 'DISCORD: SILENCIAR MICRÓFONO',
  'disp.desc.discordDeaf': 'DISCORD: ENSORDECER',
  'disp.desc.discordGenerico': 'DISCORD: {accion}',
  'disp.desc.incrVar': '{nombre} {delta}',
  'disp.desc.setVar': '{nombre} = {valor}',
  'disp.desc.variableGenerica': 'VARIABLE',
  'disp.desc.script': 'EJECUTAR: {cmd}',
  'disp.desc.scriptVacio': 'EJECUTAR SCRIPT',
  'disp.desc.atajo': 'ATAJO {teclas}',
  'disp.desc.atajoVacio': 'ATAJO',
  'disp.desc.teclaIzq': 'FLECHA IZQ',
  'disp.desc.teclaDer': 'FLECHA DER',
  'disp.desc.teclaArriba': 'FLECHA ARRIBA',
  'disp.desc.teclaAbajo': 'FLECHA ABAJO',
  'disp.desc.paginaSig': 'PÁGINA SIGUIENTE',
  'disp.desc.paginaAnt': 'PÁGINA ANTERIOR',
  'disp.desc.paginaPrimera': 'PRIMERA PÁGINA',
  'disp.desc.paginaCycle': 'CAMBIAR PÁGINA',
  'disp.desc.paginaIr': 'IR A PÁGINA',
  'disp.desc.ventanaAnt': 'VENTANA ANTERIOR',
  'disp.desc.ventanaSig': 'VENTANA SIGUIENTE',
  'disp.desc.otraVez': 'OTRA VEZ: {desc}',
};
