import type { Dict } from './tipos';

/**
 * Fragmento del diccionario espanol: editor de boton, macros, iconos de marca y glifos 5x7.
 *
 * Se fusiona en `es.ts`. Las claves son estables (no el texto).
 */
export const ES_EDITOR: Dict = {
  // — Editor de botón (chrome: pasos y navegación) —
  'ed.title': 'CONFIGURAR BOTÓN',
  'ed.preview': 'VISTA PREVIA',
  'ed.step.action': 'ACCIÓN',
  'ed.step.config': 'CONFIGURAR',
  'ed.step.style': 'ESTILO',
  'ed.back': 'ATRÁS',
  'ed.cancel': 'CANCELAR',
  'ed.next': 'SIGUIENTE',
  'ed.save': 'GUARDAR',
  'ed.clear': 'VACIAR BOTÓN',
  'ed.clearConfirm': '¿VACIAR BOTÓN?',
  'ed.confirmClear': 'CONFIRMAR',
  'ed.stepN': 'PASO {n} / {total}',
  'ed.toggleMode': 'MODO TOGGLE',
  'ed.mode.standard': '1×1 ESTÁNDAR',
  'ed.mode.split2x2': '2×2 CUADRANTES',
  'ed.mode.hint': 'Divide la celda en 4 mini-botones independientes',
  'ed.split.presets': 'PLANTILLAS 2×2',
  'ed.split.presetMedia': 'MULTIMEDIA',
  'ed.split.presetArrows': 'DIRECCIONES',
  'ed.split.presetShortcuts': 'ACCESOS',
  'ed.split.presetAudio': 'AUDIO',
  'ed.quadrant.selected': 'CUADRANTE SELECCIONADO',
  'ed.quadrant.tl': '01 · SUPERIOR IZQUIERDA (TL)',
  'ed.quadrant.tr': '02 · SUPERIOR DERECHA (TR)',
  'ed.quadrant.bl': '03 · INFERIOR IZQUIERDA (BL)',
  'ed.quadrant.br': '04 · INFERIOR DERECHA (BR)',
  'ed.split.action': 'ACCIÓN DEL CUADRANTE',
  'ed.split.icon': 'GLIFO FÍSICO 8×8',
  'ed.split.label': 'ETIQUETA MINI (MÁX 8)',
  'ed.split.sublabel': 'SUB-ETIQUETA',
  'ed.split.bgColor': 'COLOR DE FONDO',
  'ed.split.fgColor': 'COLOR DE TEXTO / ICONO',
  'ed.split.noIcon': 'SIN ICONO',
  'ed.split.customColor': 'HEX',
  'ed.split.toggle': 'MODO INTERRUPTOR (TOGGLE)',
  'ed.pickSensor': '— Seleccione un sensor —',
  'brand.search': 'Buscar icono...',
  'macro.scrollHint': '(+ arriba, − abajo)',
  'ed.cancelCapture': 'CANCELAR',
  'brand.clearAll': 'LIMPIAR TODO',
  'brand.activeColor': 'COLOR ACTIVO',
  'brand.hint': '17×17 · Admite varios colores · Las animaciones siguen el patrón de puntos',
  'brand.saveIcon': 'GUARDAR ICONO',
  'glyph.fromFont': 'CARGAR DESDE TIPOGRAFÍA',
  'glyph.empty': 'Vacío: al guardar se eliminará del botón',
  'glyph.tools': 'HERRAMIENTAS',
  'glyph.invert': 'Invertir',
  'glyph.flipH': 'Espejo H',
  'glyph.flipV': 'Espejo V',
  'glyph.undo': 'Deshacer',
  'glyph.symbols': 'SÍMBOLOS',
  'glyph.preview': 'VISTA PREVIA',
  'glyph.shift': 'Desplazar',
  'macro.recording': 'REC • pulse teclas y haga clics...',
  'macro.noSteps': 'Sin pasos. Grabe una macro o añada pasos manualmente.',
  'ed.killHint': 'Use el nombre exacto del ejecutable. Equivale a taskkill /IM nombre /F.',
  'ed.volumeHint': 'Establece el volumen maestro del sistema al porcentaje indicado.',
  'ed.noRgbProfiles': 'No hay perfiles RGB guardados. Abra la pantalla RGB y guarde un perfil con el estado actual de sus dispositivos.',
  'ed.snapHint': 'Sin nombre de proceso, ajusta la ventana que esté en primer plano al ejecutarse.',
  'ed.radioHint': 'Todos los toggles con el mismo grupo se desactivan cuando se activa este.',
  'ed.triggers': 'DISPARADORES EXTERNOS',
  'ed.thresholdHint': 'Warn pinta el valor en amarillo, Crit en rojo. Mismas unidades que el sensor.',
  'folder.empty': 'Sin botones configurados. Edite este botón para añadirlos.',
  'folder.esc': 'ESC PARA CERRAR',
  'brand.none': 'Sin icono de marca',
  'brand.g.all': 'Todos',
  'brand.g.design': 'Diseño y Producción',
  'brand.g.streaming': 'Streaming y Contenido',
  'brand.g.dev': 'Programación y Dev',
  'brand.g.productivity': 'Productividad',
  'brand.g.media': 'Multimedia y Ocio',
  'brand.g.system': 'Utilidades y Sistema',
  'brand.i.settings': 'Configuración',
  'brand.i.controlPanel': 'Panel de Control',
  'brand.title': 'ICONOS DE MARCA ANIMADOS',
  'glyph.title': 'EDITOR DE GLIFO 5×7',
  'ed.noSensors': '(sin sensores: habilite LHM y conéctelo desde la barra de título)',
  'ed.noTempSensors': '(para temperaturas de CPU/placa, activa LibreHardwareMonitor en Ajustes > Sensores)',
  'icon.setPrimary': 'Definir como color principal (#)',
  'glyph.load': 'Cargar "{ch}"',
  'macro.step.key': 'Tecla',
  'macro.step.hotkey': 'Combinación',
  'macro.step.text': 'Texto',
  'macro.step.click': 'Clic ratón',
  'macro.step.move': 'Mover ratón',
  'macro.step.delay': 'Pausa (ms)',
  'macro.step.scroll': 'Scroll',
  'editor.stdoutToVar': 'La salida del script se guarda en la variable y puede usarse como {ejemplo} en otros pasos.',
  'macro.fieldText': 'TEXTO',
  'macro.fieldKey': 'TECLA',
  'macro.textPlaceholder': 'Texto a escribir',
  'macro.rec.start': 'GRABAR',
  'macro.rec.stop': 'DETENER',
  'macro.textDefault': 'Hola mundo',
  'macro.recEmpty': 'No se capturó ninguna tecla ni clic. Los clics sobre esta ventana no cuentan: use el teclado o haga clic fuera de ella.',
  'editor.previewHint': 'HOVER → EDITAR',
  'editor.previewHint2': 'CLIC → EJECUTAR',
  'editor.applyPreset': 'Aplicar preset: {nombre}',
  'ed.seq.delay': 'ESPERA',
  'ed.seq.delayTitle': 'Milisegundos de espera antes de ejecutar este paso. Vacio = 150 ms.',
  'ed.seq.repeat': 'REPETIR',
  'ed.seq.repeatTitle': 'Cuantas veces se ejecuta este paso seguido. Vacio = una vez.',
  'ed.seq.always': 'SIEMPRE',
  'ed.seq.onlyIfOk': 'SOLO SI OK',
  'ed.seq.onlyIfOkTitle': 'Ejecutar este paso solo si el anterior termino bien.',
  'ed.seq.onlyIfFailed': 'SI FALLA',
  'ed.seq.onlyIfFailedTitle': 'Ejecutar este paso solo si el paso anterior terminó con error.',
  'ed.seq.continueOnError': 'CONTINUAR SI FALLA',
  'ed.seq.continueOnErrorTitle': 'No detener la secuencia si este paso da error.',
  'ed.seq.moveUp': 'Subir paso',
  'ed.seq.moveDown': 'Bajar paso',
  'ed.actionSequence': 'SECUENCIA DE ACCIONES (OPCIONAL)',
  'ed.snapHint2': 'Funciona mejor con atajos globales, sin pasar por VirtualDeck.',
  'ed.pinned': 'ANCLAR EN TODAS LAS PÁGINAS',
  'ed.pinnedHint': 'Ocupa la misma posición en todas las páginas del deck.',
  'ed.discord.action': 'ACCIÓN DE DISCORD',
  'ed.discord.toggleMute': 'Alternar silencio (Mute / Unmute)',
  'ed.discord.toggleDeaf': 'Alternar ensordecer (Deafen / Undeafen)',
  'ed.discord.mute': 'Silenciar micrófono (Mute)',
  'ed.discord.unmute': 'Activar micrófono (Unmute)',
  'ed.discord.deaf': 'Ensordecer (Deafen)',
  'ed.discord.undeaf': 'Desensordecer (Undeafen)',
  'ed.discord.help': 'Se conecta automáticamente al cliente de escritorio de Discord vía Named Pipe local (\\.\\pipe\\discord-ipc-0..9) con 0 ms de latencia.',
  'ed.spotify.action': 'ACCIÓN DE SPOTIFY',
  'ed.spotify.playUri': 'Reproducir Playlist / Canción / Álbum',
  'ed.spotify.transfer': 'Transferir reproducción a dispositivo',
  'ed.spotify.shuffle': 'Alternar modo aleatorio (Shuffle)',
  'ed.spotify.repeat': 'Alternar repetición (Repeat)',
  'ed.spotify.uri': 'URI O ENLACE WEB DE SPOTIFY',
  'ed.spotify.help': 'Acepta URIs de Spotify (spotify:playlist:...) o enlaces de open.spotify.com. Se lanzan instantáneamente en la aplicación de escritorio.',
  'ed.spotify.deviceId': 'ID DEL DISPOSITIVO SPOTIFY',
  'ed.spotify.devicePlaceholder': 'ID de dispositivo devuelto por la API',
  'ed.spotify.token': 'TOKEN DE ACCESO WEB API (OPCIONAL)',
  'ed.spotify.tokenPlaceholder': 'Token Bearer de Spotify Web API',
  'ed.spotify.detectDevices': 'BUSCAR DISPOSITIVOS',
  'ed.spotify.noDevices': 'No se encontraron dispositivos activos',
  'ed.discord.status': 'ESTADO DE DISCORD',
  'ed.discord.connected': 'CONECTADO',
  'ed.discord.notRunning': 'DISCORD NO DETECTADO',
};
